### ISSUE TITLE
Big (and growing) temporary files

### ISSUE THREAD

**Issue by Nekromancer** [naudio/NAudio#102]
I'm building a service that listens to 20 streams all the time (and dumps it to file here and there). My problem is - system is creating a huge temporary files which can't be deleted until application is stopped (which is VERY bad, we don't want to stop this service, ever). Temporary files are in Internet Explorer Temporary directory `C:\Users\<username>\AppData\Local\Microsoft\Windows\Temporary Internet Files`. 

Strange thing is - i observe this kind of behavior only on our production server (Windows Server 2012 R2), there is no such problem on Windows 10.

Production server has low space for system files (small HD drive) and high space SSD file for our service disposal. Problem is that temporary files are constantly thrashing our hd drive. System seems to be ignoring this files. After 3 days of work whole free space (20GB) was taken by it.

My qustion is - why is that happening (it's pretty strange that stream buffer lands in IE Temporary directory) and do you know any method to avoid that? Maybe use some other place to store temporary files?

**Comment by markheath** [comment]
well it's not NAudio creating the files. Are you using MediaFoundationReader perhaps to stream from a URI?

**Comment by Nekromancer** [comment]
Yes, i am.

Those files look like that:

![http://i.imgur.com/vUl2kQd.jpg](http://i.imgur.com/vUl2kQd.jpg)

**Comment by markheath** [comment]
so I'm guessing this is how media foundation is downloading the audio internally. Not sure what can be done about that. Make sure you've patched your IE and have the desktop experience installed on the server.
