### ISSUE TITLE
Mono MP3 files play @ 2x speed

### ISSUE THREAD

**Issue by jasells** [naudio/NAudio#104]
I haven't got to the root of the issue myself, but I confirmed that a single channel file/stream will play @ 2x speed.  I have re-encoded my original mono file into a stereo file to confirm that it plays correctly when 2x channels are present.  In debugger, I can change the sample rate to 1/2 the detected rate to also "fix" the issue using the original single channel file.

Here are some examples
[Mono](http://www.westhuntsville.org/Audio/Uploaded/TestFile.mp3)
[Stereo](http://www.westhuntsville.org/Audio/Uploaded/TestFile2.mp3)

**Comment by residuum** [comment]
That is because you play the mono file with a stereo output, and the samples are deinterlaced: The audio is split into two parts, and one part goes to the left, the other part to the right.

To fix this, see https://github.com/naudio/NAudio/blob/master/NAudio/Wave/SampleProviders/MonoToStereoSampleProvider.cs

**Comment by jasells** [comment]
ok, i figured it was something like that, but it wasn't clear how to do that (without your link). This lib needs a simple Player object that works like MediaElement. Set the source and provide basic controls, the details can be encapsulated. i know, that is not exactly the point of this lib...

And just in case someone else is reading this , the reason I am looking @Naudio is because I can't get MediaElement from WPF to work with Xamarin on Windows 8.1.  Naudio is basically working for me now, minus the simple API provided by MediaElement.  If someone knows how to get MediaElement to work in Xamarin, please post a link.

**Comment by jasells** [comment]
Follow up:
I finally got MediaElement working in Xamarin UWP (it should work the same on Win8U as well).
[https://github.com/jasells/WindowsXamarinAudioTests/tree/XamarinUWP-working](url)

Summary: MediaElement *must* be part of a visual tree (i.e. the child of a View) to work.  This also means that it can be a singleton that is passed from View to View, if multiple views need to play media, and that it shouldn't be made the child of a View class that has multiple instances.
