### ISSUE TITLE
AudioClient raises 0x88890026 HResult but no entry present in AudioClientErrors

### ISSUE THREAD

**Issue by Erminh** [naudio/NAudio#105]
Seen on Windows 10, when a Wasapi input/output is disconnected a ComException is sometimes thrown with HResult 0x88890026. This error is known as AUDCLNT_E_RESOURCES_INVALIDATED but is missing from the AudioClientErrors enumeration and ErrorCodes static class.

**Comment by markheath** [comment]
many thanks for reporting this, will get this added to the list soon

**Comment by mwahh** [comment]
Still happening (to me) in Windows 10 1803 on occasion.
