### ISSUE TITLE
Wasapi DLL version mistake?

### ISSUE THREAD

**Issue by jizc** [naudio/NAudio#1065]
It appears the latest update bumped the version a lot further than intended:
https://github.com/naudio/NAudio/commit/c455f89bf1836bc0abbd082c35c8bee203f65b06#diff-93539c70eff254360a382ea643ece990ea69b3031a1384af46fab8632ad5ebcbR5

**Comment by markheath** [comment]
Yeah I know, spotted it the moment I pushed! There is actually no way to delete a version (can only "unlist" it), so not sure what the best thing to do is.

**Comment by jizc** [comment]
Probably best to unlist v2.2.0 and release a v2.2.1. I think it will only be a problem when/if you get to v22 😆 If you ever get there, I'm sure you can just skip it and go to v22.0.1.

**Comment by markheath** [comment]
Should be fixed now, please let me know if there are any issues consuming this. Everything is 2.2.1 (and NAudio.Wasapi v22.0 is unlisted but identical in functionality to 2.2.1)
