### ISSUE TITLE
NAudio.Wasapi has version 22.0.0, not 2.2.0

### ISSUE THREAD

**Issue by jwosty** [naudio/NAudio#1066]
Title.

See: https://www.nuget.org/packages/NAudio/2.2.0#dependencies-body-tab and https://www.nuget.org/packages/NAudio.Wasapi/#versions-body-tab

Should probably re-publish with the right version and unlist. Or maybe just accept fate and update everything to version 22, lol.

**Comment by jizc** [comment]
Mark responded about it here: https://github.com/naudio/NAudio/issues/1065

**Comment by markheath** [comment]
Should be fixed now, please let me know if there are any issues consuming this. Everything is 2.2.1 (and NAudio.Wasapi v22.0 is unlisted but identical in functionality to 2.2.1)
