### ISSUE TITLE
Can I change pitch while looping?

### ISSUE THREAD

**Issue by lucasheer** [naudio/NAudio#108]
I have a short loopable .wav recording of me playing an F note on my instrument. I need the note to constantly play, and be able to change the pitch of it to a G or even an A. I have successfully been able to loop it using LoopStream and overriding the functions, but I haven't been successful at using the Equalizer class. I haven't even been able to play the .wav once through the equalizer, I get NULL Exception. Is there any way I can just override a function in the LoopStream and do the pitch change there? Thank you!

**Comment by markheath** [comment]
I'm afraid NAudio doesn't have a built-in pitch shifting function. However, please check out my [varispeed playback](http://markheath.net/post/varispeed-naudio-soundtouch) article which describes how to use Soundtouch which can also do pitch shifting

**Comment by Freefall63** [comment]
You can do this now, I recently contributed a pitch shifter:

https://github.com/naudio/NAudio/blob/master/NAudio/Wave/SampleProviders/SMBPitchShiftingSampleProvider.cs

**Comment by markheath** [comment]
just to add, this will be released when NAudio 1.8 comes out (hopefully soon). Not currently on NuGet
