### ISSUE TITLE
Is it possible to generate different instruments sounds with this library?

### ISSUE THREAD

**Issue by MarcusCFarias** [naudio/NAudio#1088]
I am writing a code which receives as input a text and the selected instrument (guitar, piano, flute) and has to convert this text to a song with the respective instrumental tone. 

It is possible?

**Comment by markheath** [comment]
I'd convert the text to MIDI, and then use something like MeltySynth (https://github.com/sinshu/meltysynth) to render that to audio using a SoundFont.

**Comment by MarcusCFarias** [comment]
hm, i'm kinda rookie on sound application, could you explain this logic? i didn't understand why would I convert to MIDI file.

My program has already the equivalent note to which char, for example:

The text file "AB C" is equivalente to each note and blank space means a little pause. I have to call a function with instrument input and the respective note.

Play(Instrument, Note); => in the output it would be something like this "A", "B", pause, "C".

Understand?

**Comment by MarcusCFarias** [comment]
Mark, 

Thanks for help me, but I found what I was lookking for. 

I am providing this link [(Microsoft Article)](https://learn.microsoft.com/en-us/archive/msdn-magazine/2010/march/ui-frontiers-midi-music-in-wpf-applications) for others possible doubts.
