### ISSUE TITLE
MediaFoundationReader sample rate incorrect or something weird

### ISSUE THREAD

**Issue by wasabii** [naudio/NAudio#109]
I have a mp4 file, which I am opening with `MediaFoundationReader`, and immediately writing to a .wav file using `WaveFileWriter`. The `WaveFormat` for the `WaveFileWriter` is set to the `WaveFormat` of the `MediaFoundationReader`. So, saving as the same format it's read as.

When I play the resulting WAV file, everybody sounds like chipmunks. The WAV file is at sample rate 16000. When I check the `WaveFormat` on the `MediaFoundationReader` it is at 16000. When I play it, the player I am using says 16000. When I play the original MP4 file, the player says 16000.

Basically, everything says 16000 everywhere.

Except the WAV sounds like chipmunks, and playing the MP4 file directly does not.

If I play the WAV file at 8000 (using an override in my media player) it sounds fine.

I can't even figure out what could be going wrong here. My best guess is that the audio is in actuality 8000hz. But the MP4 shows 16000 for some unknown reason, and reports that to NAudio, which marks the WAV file with that.

The MP4 is stereo. This is a totally off the wall guess... but could the stereoness be causing something somewhere to multiple by two? Maybe? I don't know!

Since all the media players I've used work fine with this MP4 file, regardless what they show, I do believe there is SOME issue somewhere inside NAudio.

**Comment by wasabii** [comment]
Okay. New information. When I check the file on Windows with MediaInfo, it says 8000hz 2 channel. When I open it in VLC, it says 16000hz stereo.

**Comment by markheath** [comment]
OK, that explains it. Unfortunately, this is the built-in Windows media foundation reader misinterpreting the format. You could cheat by simply passing the correct WaveFormat to the WAV file writer. If you want to debug into the NAudio code, it's in MediaFoundationReader.GetCurrentWaveFormat. The only thing I can think is that maybe this MP4 contains more than one audio stream?

**Comment by wasabii** [comment]
Naw. Only one stream. What gets me is that all the apps can actually play it just fine, regardless what they report. So, somewhere, internally, it knows the proper sample rate. It just can't say so.

**Comment by shruti8789** [comment]
Will this issue be fixed in NAudio?

**Comment by markheath** [comment]
Do you have an example of a file that doesn't play correctly?

**Comment by shruti8789** [comment]
I have found a m4a file as well, that doesn't work for me.
mp4 - none of the file sworked for me.
Though when i call streamMediaReader.ReadByte();, WaveFormat of streamMediaReader is fixed.
 
To make it clear,
1using (StreamMediaFoundationReader streamMediaReader = new StreamMediaFoundationReader(inputStream))
2{
3    streamMediaReader.ReadByte();
4    ...
5}

After line 1, streamMediaReader will show the waveFormat as 16 bit PCM, 32000 Hz, 2 channel, and
after line 3, streamMediaReader will show the waveFormat as 16 bit PCM, 16000 Hz, 1 channel.

Somehow by calling readbyte, format of streamMediaReader is fixed.
Can someone please explain me how is that fixed? and why was it wrong earlier?
