### ISSUE TITLE
Resume a song

### ISSUE THREAD

**Issue by IreneArgolloDelgadillo** [naudio/NAudio#110]
Hi, whe I try to continue the song with:
private void playASong()
        {
            waveOutDevice = new WaveOut();
            audioFileReader = new AudioFileReader(@"D:\path.mp3");
            waveOutDevice.Init(audioFileReader);
            waveOutDevice.Play();
        }
 this is my pause function:
private void pause()
        {
                waveOutDevice.Pause();
         }
 I have a problem , there is not available the Resume() option, and whe i press a play, the song is rigth, but after press pause button and again press the playASong, the song sounds from the beginning, but i need to resumen, please, some can help me to do this, I consulted and search something like  http://stackoverflow.com/questions/11864079/naudio-pause-then-resume but it does not work...

**Comment by residuum** [comment]
If you call your method`playASong()` again, you instanciate a new object. You need three methods:

    private void playASong()
    {
        waveOutDevice = new WaveOut();
        audioFileReader = new AudioFileReader(@"D:\path.mp3");
        waveOutDevice.Init(audioFileReader);
        waveOutDevice.Play();
    }

    private void resume()
    {
        waveOutDevice.Play();
    }

    private void pause()
    {
        waveOutDevice.Pause();
    }

And then call `playAsong()`, `pause()` and `resume()` in that order.

**Comment by IreneArgolloDelgadillo** [comment]
thank you so much, it works , I was forget instantiated the waveOutDevice on the constructor
