### ISSUE TITLE
Volume seems unaffected for output audio

### ISSUE THREAD

**Issue by PhoenixWyllow** [naudio/NAudio#1102]
I am using these two files: 
[AudioReader.cs](https://github.com/PhoenixWyllow/Soundboard4MacroDeck2/blob/bugfix/noVolumeControl/Services/AudioReader.cs)
[SoundboardPlaybackEngine.cs](https://github.com/PhoenixWyllow/Soundboard4MacroDeck2/blob/bugfix/noVolumeControl/Services/SoundboardPlaybackEngine.cs)

It sems the volume is unaffected and will always play at device volume.
Could use a bit of help with this one. What am I doing wrong?

Edit: updated issue with links to current development files

**Comment by markheath** [comment]
in your `Read` method you need to read out of `_sampleChannel`, not `readerStream`. You'll have to convert back to waveprovider or make your AudioReader just an ISampleProvider

**Comment by PhoenixWyllow** [comment]
Many thanks for your suggestions. Leaving it just as an ISampleProvider did not seem to work (some sort of issue when passed to MMDevice that I'm too inept to figure out in a few hours before bed) but converting back to an IWaveProvider *did* work! 

Updated my sources if anyone wants to have a look at the ["fix"](https://github.com/PhoenixWyllow/Soundboard4MacroDeck2/commit/f2daa5e88069e30a2e098632a12a502f126449cf).
