### ISSUE TITLE
Invalid WAV file - No fmt chunk found 

### ISSUE THREAD

**Issue by mb2140** [naudio/NAudio#111]
Hello, I'm using the WaveFileReader to read a particular wav and keep running into this error:

Invalid WAV file - No fmt chunk found 

I'm trying to determine what could cause this or what's wrong with my .wav file.  If I look at WaveFileChunkReader Line 37 I see that 

 this.riffSize = br.ReadUInt32();

Is returning 0, as opposed to my other .wav files where this number is much larger.  I have verified that my stream is not empty and set to Position = 0.  Any ideas what would cause this or what this means?  Is there a good tool I can use to analyze the makeup of a particular wav file?  It seems to play fine in VLC.

                    using (WaveFileReader wavFileReader = new WaveFileReader(wavFile))
                    {

    }

**Comment by mb2140** [comment]
Doh!  Wasn't closing my WaveWriter properly.

**Comment by arnelambrosio** [comment]
Hi I have the same problem, what do you mean the WaveWriter is not properly closed? In my case I did this way, but still got that error message.
```catch (Exception e)
            {
                throw e;
            }
            finally
            {
                if (waveFileWriter != null)
                {
                    waveFileWriter.Dispose();
                }
            }

**Comment by markheath** [comment]
You must call `WaveFileWriter.Dispose()` to ensure that the WAV header is updated correctly with the correct chunk size.

**Comment by arnelambrosio** [comment]
> You must call `WaveFileWriter.Dispose()` to ensure that the WAV header is updated correctly with the correct chunk size.

Hi Mark, I did here is my code

``` 
IEnumerable<string> filePaths = Directory.EnumerateFiles(@"C:\temp\audio2");

            byte[] buffer = new byte[1024];
            WaveFileWriter waveFileWriter = null;
            MemoryStream outputFile = new MemoryStream();

            try
            {
                    foreach (string sourceFile in filePaths)
                    {
                        using (WaveFileReader reader = new WaveFileReader(sourceFile))
                        {
                            if (waveFileWriter == null)
                            {
                                // first time in create new Writer
                                waveFileWriter = new WaveFileWriter(outputFile, reader.WaveFormat);
                            }
                            else
                            {
                                if (!reader.WaveFormat.Equals(waveFileWriter.WaveFormat))
                                {
                                    throw new InvalidOperationException("Can't concatenate WAV Files that don't share the same format");
                                }
                            }

                            int read;
                            while ((read = reader.Read(buffer, 0, buffer.Length)) > 0)
                            {
                                waveFileWriter.Write(buffer, 0, read);
                            }
                        }
                    }

                    outputFile.Position = 0;
                    await File.WriteAllBytesAsync(@"C:\temp\audio2.wav", outputFile.ToArray());

                
            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                if (waveFileWriter != null)
                {
                    waveFileWriter.Dispose();
                }
            }

**Comment by arnelambrosio** [comment]
Hi @markheath , I tried to change that the destination of the WavefieWriter is physical file path and it is working, but in my case it should be written in Stream and I will save this stream to the cloud container.

**Comment by markheath** [comment]
Please see my reply on your other github issue
