### ISSUE TITLE
Constructor 'NAudio.Wave.MediaFoundationReader.MediaFoundationReader(string)' cannot call itself

### ISSUE THREAD

**Issue by BrianMcBrayer** [naudio/NAudio#113]
I just cloned the NAudio repository for the first time and opened it in Visual Studio 2013 (fully updated). However, it will not build and none of the demos will run because it appears that a constructor is calling itself. I'm sure this is a beginner's mistake, but I am not a beginner programmer and it looks like a coding error to me. Any help, or anything I can help with?

**Comment by markheath** [comment]
you need to open it with VS2015 as it uses some C# 6 syntax

**Comment by mattcuba** [comment]
Hi Mark, 
I'm having an issue in VS 2015 with that exact line as Brian.
It is making a primary constructor call - I don't think primary constructors made the cut for c# 6.
Definitely doesn't build as-is for me.

**Comment by markheath** [comment]
ok, will have a check. May be to do with the most recent PR.

**Comment by BrianMcBrayer** [comment]
Yes, I believe that's it after looking at the diff

**Comment by markheath** [comment]
hopefully that sorts it out. my bad for accepting the PR with just a code review shortly before going on holiday!
