### ISSUE TITLE
Request for MidiEvent.Clone

### ISSUE THREAD

**Issue by jnm2** [naudio/NAudio#114]
I want to repeat a section of a MIDI file and right now I don't see a way to do that. It would be perfect to have an abstract `Clone` method on the MidiEvent class, just like Stephen Toub did [here](https://github.com/stephentoub/MidiSharp/blob/54c5f4edafa5e0ac8110faa25fdea6a395e6f0c9/MidiSharp/Events/MidiEvent.cs#L223).

I'm willing to submit a PR as well.

**Comment by markheath** [comment]
great idea, would be a nice addition to the library
