### ISSUE TITLE
OGG file format support

### ISSUE THREAD

**Issue by ProgrammerSmarty** [naudio/NAudio#1141]
Will NAudio ever have the OGG file format?

It's well known and well used and was just wondering that you have every other format but OGG.

I just want this great library to support a great file format for my new DAW that I'm making. That's all :)

**Comment by markheath** [comment]
it doesn't have native support for ogg. But MediaFoundationReader may be able to play an ogg file depending on what codecs are installed on your machine.

**Comment by alenet444** [comment]
with  the official codec for windows and MediaFoundationReader you can read and play those files!   here is the link:    [https://downloads.xiph.org/releases/oggdsf/oggcodecs_0.83.17220-win32.exe ](url)
