### ISSUE TITLE
Anyway to do selective program recording?

### ISSUE THREAD

**Issue by robinator8** [naudio/NAudio#119]
I'd like to be able to record multiple audio files at once, for each program, including my microphone. 
Eg. If I had TS3, GTAV, and Spotify open all at once and I was recording, they would all be separate audio files. This was I could cut out the spotify stuff, and turn up the TS3 voices.

**Comment by markheath** [comment]
sadly the WASAPI API does not let you capture the output of an individual application (unless they've snuck that ability into Windows 10 somewhere).

**Comment by robinator8** [comment]
Is there anyway to do this?

**Comment by markheath** [comment]
I'm afraid not.

**Comment by robinator8** [comment]
Are you aware of any work around, like assigning virtual speakers to different programs, then running them all to your default speakers?

**Comment by markheath** [comment]
I'd suggest using a virtual audio cable for something like that. there's a few available
