### ISSUE TITLE
Release DLL is unsigned

### ISSUE THREAD

**Issue by aa-telali** [naudio/NAudio#12]
I have a signed DLL with code that uses the NAudio library. I noticed it's on nuget so tried to use the latest version from there but unfortunately it isn't signed.

To get around the problem, I build it myself from the master branch after adding a signing key which is straightforward but it'll need to be done every time I update the code base.

Many thanks for a fantastic library.

**Comment by markheath** [comment]
I get requests for this occasionally. Signing the DLL can cause issues for some people. One approach I saw recently was that one project (I forget which) issued two separate NuGet packages, a signed one and a regular one. If that would work for people that might be a good compromise solution.
