### ISSUE TITLE
Integrate NAudio into AppVeyor CI

### ISSUE THREAD

**Issue by KvanTTT** [naudio/NAudio#121]
Add continious integration for tests passing with [AppVeyor](https://www.appveyor.com/).

**Comment by markheath** [comment]
I tried a while back with travis-ci but it failed to build as it was mono on Linux. I don't know what the AppVeyor platform uses, but a number of the NAudio unit tests actually use things like MediaFoundation, and there are UWP projects to build, so it may not be possible. If someone wants to try they are more than welcome

**Comment by KvanTTT** [comment]
AppVeyor is a Windows-based system.

**Comment by markheath** [comment]
OK, that sounds more promising than travis was
