### ISSUE TITLE
Handling Exception Results in Being Unable to Close Reader

### ISSUE THREAD

**Issue by CoryZ40** [naudio/NAudio#125]
When I try to read an invalid file with Mp3FileReader, an exception is thrown. However, the file is still open and I can't close it in my catch block. I'm I going about this all wrong?

**Comment by markheath** [comment]
If the constructor for `Mp3FileReader` encounters an error loading the MP3, it will dispose the file only if it opened it. If you passed in a `Stream` object, then it's up to you to dispose that stream if the `Mp3FileReader` throws an exception.

**Comment by CoryZ40** [comment]
I'm not sure that first part is true. My code had the constructor that takes the file path as a parameter inside of a try block, and when I gave it something invalid, I wanted the program to delete the file. It couldn't delete it because it was still open. Inside the catch block there was no way of closing it since the reader would either go out of scope or it would go back to being null, depending on where the reader was declared. However, I was able to give it a file stream and dispose it myself, like you said. That solved the problem.

**Comment by markheath** [comment]
hmm looking again at the code, I wonder if `ownInputStream = true` gets set too late to dispose the opened file. I'll maybe give that a quick check and get the bug fixed if necessary

**Comment by CoryZ40** [comment]
Sounds good. I'd love to know what you come up with.

**Comment by markheath** [comment]
yes, stupid mistake. `WaveFileReader` does it right, but obviously overlooked in `Mp3FileReader`
