### ISSUE TITLE
WdlResampler upsamples nothing

### ISSUE THREAD

**Issue by martindevans** [naudio/NAudio#127]
I'm using the WdlResamplingSampleProvider to convert an audio stream from 44,100Hz to 48,000Hz with a pipeline a bit like this:

```
var input = new BufferedSampleProvider(_inputFormat);          //input at 44.1kHz
var resampler = new WdlResamplingSampleProvider(input, 48000); //convert up to 48kHz
var output = new SampleToFrameProvider(resampler, _frameSize); //Read out 48kHz data in fixed size frames
```

`BufferedSampleProvider` is my own class which has data pushed into it and writes it in an internal buffer, then implements ISampleProvider to provide the data. `SampleToFrameProvider` is also my own class which takes an ISampleProvider and reads fixed size frames from it (buffering up multiple smaller reads as necessary, until it has an entire frame).

I've encountered a problem with the resampler which was causing bad audio. Sometimes the `BufferedSampleProvider:Read` method returns zero samples, when this happens I would expect the resampler to also return zero samples. However, the resampler is resampling zero samples up to four samples (and these samples invariably sound bad).

![untitled](https://cloud.githubusercontent.com/assets/177519/19216412/916da7e0-8db2-11e6-8229-63a29358a912.png)

I have hacked a temporary fix for this by doing the following:

```
var inAvailable = _source.Read(inBuffer, inBufferOffset, inNeeded * _channels) / _channels;

//Resampler does not handle zero samples well! If we read nothing, return nothing
if (inAvailable == 0)
    return 0;

var outAvailable = _resampler.ResampleOut(buffer, offset, inAvailable, framesRequested, _channels);
```

Is this a fix you would like to add to NAudio, or am I doing something wrong?

**Comment by markheath** [comment]
there are two approaches to resampling - input driven and output driven. With input driven, every time you get new audio you give it to the resampler, and then read out what it got converted to. With output driven, you assume that the input is fully available (e.g. a file) and keep reading from the output until you get to the end. 

The `WdlResamplingSampleProvider` in NAudio is uses the output driven, but the underlying code in `WdlResampler` can do input driven too. I'm guessing that would be more appropriate for your use case.

I'd be reluctant to bring in your change as it potentially loses the last few samples off an output driven resample.

**Comment by martindevans** [comment]
The input data is arriving from a microphone and being placed into the BufferedSampleProvider as it arrives - so it definitely sounds like input driven is what I want here. I tried changing the resampler to be input driven by changing to `SetFeedMode(true)`. However this still sounds bad :(

Here's a screenshot where you can see the relevant code, as well as a time when the resampler simply made up some samples:

![untitled](https://cloud.githubusercontent.com/assets/177519/19238703/ad33cd58-8efa-11e6-8f09-eaeccd27519a.png)

You can see from the locals window that the resampler requested 1920 samples, upstream provided 0 and yet the resampler still managed to return *156* samples!

Here's an example of the kind of problem this seems to be causing:

![untitled2](https://cloud.githubusercontent.com/assets/177519/19238754/e7aad06c-8efa-11e6-9ab5-294f8bd12ce0.png)

**Comment by markheath** [comment]
with input driven, every time a buffer of data is recorded from the microphone, you add it to the resampler, and then read from the resampler. Put the data you read into a BufferedWaveProvider (or similar) and play from that. The WdlResamplingSampleProvider is inherently output driven so changing that flag won't help.

**Comment by martindevans** [comment]
Ok I've changed over to pushing data through the resampler and then writing the resampled output to the start of the pipeline. This totally breaks the audio altogether so I'm probably doing something wrong with the resampler...

The resampler is created in pretty much the same way as the output driven resampler:

```
_resampler = new WdlResampler();
_resampler.SetMode(true, 2, false);
_resampler.SetFilterParms();
_resampler.SetFeedMode(true);
_resampler.SetRates(_inputFormat.SampleRate, _encoder.SampleRate);
```

Then when I get some new data from the microphone I push it into the resampler, read out the result and write that into the pipeline:

```
ArraySegment<float> inputSamples; //we start with some input samples in here
float[] _resampled; //this is a sufficiently large array to hold a frame of input, multiplied by the resampling rate ratio

//Inform the resampler we have some samples ready to process
float[] inputBuffer;
int inputBufferOffset;
var inputCount = _resampler.ResamplePrepare(inputSamples.Count, _inputFormat.Channels, out inputBuffer, out inputBufferOffset);

//Copy input samples into the resampler
inputSamples.CopyTo(new ArraySegment<float>(inputBuffer, inputBufferOffset, inputCount));

//Read resampled data out from resampler and copy into encoding pipeline
var outputCount = _resampler.ResampleOut(_resampled, 0, inputCount, _resampled.Length, _inputFormat.Channels);

_input.Write(_resampled, 0, outputCount); // <-- write into the start of the rest of the pipeline
```

**Comment by markheath** [comment]
that looks roughly what I'd expect, although I've not used `ArraySegment` myself . If I were you I'd head over to the WDL forums over at Cockos, which is where the WDL resampler is from. Here's [a thread](http://forum.cockos.com/archive/index.php/t-86272.html) that might be useful.

**Comment by martindevans** [comment]
Thanks for the help :)
