### ISSUE TITLE
No audio capture windows IoT raspberry pi 3

### ISSUE THREAD

**Issue by jeffreynlnl** [naudio/NAudio#129]
Hello! 

I am not sure if i'm on the right place here but i encountered an error with the Naudio library.

I'm using the Naudio universal library to record -> network and network -> play sounds on a raspberry pi 3 with windows universal IoT.

when i use the out and in example seperate it all works as it should. but when i initialize them at the same time, the capture class does not send out any datreceived events, well at some random intervals it does throw an event but not as it should.

when i run this software as a build on an x64 windows installation it works fine.

Has anyone had the same problem as i do? and is there a way to solve this?
Thanks!

this is a little sample code that i wrote that runs ok on a x64 windows, but fails on a Arm IoT raspberry pi 3

`private void SimpleInit()
        {
            WasapiOutRT waveOut = new WasapiOutRT(AudioClientShareMode.Shared, 100);
            BufferedWaveProvider bufferdProvider = new BufferedWaveProvider(new WaveFormat(44100, 16, 2));
            waveOut.Init(bufferdProvider);
            waveOut.Play();

```
        WasapiCaptureRT waveIn = new WasapiCaptureRT();
        waveIn.WaveFormat = new WaveFormat(44100, 16, 2);
        waveIn.DataAvailable += (sender, e) => WaveIn_DataAvailable(sender, e, bufferdProvider);
        waveIn.StartRecording();
    }

    private void WaveIn_DataAvailable(object sender, WaveInEventArgs e, BufferedWaveProvider output)
    {
        output.AddSamples(e.Buffer, 0, e.BytesRecorded);
    }`
```

**Comment by markheath** [comment]
the UWP support in NAudio sort of works, but I'm still not really happy with it. I've certainly never tried it on ARM so there's a chance there will be some issues with that. To be honest, I'd recommend you look into the new `AudioGraph` API that's on the UWP platform. It's really nice, and [I did a pluralsight course about it recently](https://www.pluralsight.com/courses/uwp-audio-fundamentals?utm_medium=affiliate&utm_source=1036405), so if you have an account or want to sign up for a free trial then I'd recommend watching it. AudioGraph works great on IoT Raspberry Pi.

**Comment by BarryOCathain** [comment]
Just wondering if there's been any change in terms of ARM support?

Cheers.
