### ISSUE TITLE
.NET Core 1.0 apps support

### ISSUE THREAD

**Issue by staticdev** [naudio/NAudio#130]
I tried to install 1.7.3 on a new .NET Core app, but it told me it is not supported. Is there any plans for adding this support?

**Comment by markheath** [comment]
NAudio contains a large amount of interop wrappers for Windows APIs and structures, so I suspect that a .NET core version of NAudio would unfortunately be quite difficult to make. The fully managed parts of course could be used in .NET core.

**Comment by abhi18av** [comment]
@markheath , so what you are saying is that there's still a possibility that it'll work fine with `dotNET-core v2` which complies with `.net standard v2`?

**Comment by markheath** [comment]
All of the interop wrappers require you to be on Windows, so you lose the cross-platform benefits of .NET core.

**Comment by abhi18av** [comment]
Would it be a huge undertaking to find a work around for these wrappers?

**Comment by markheath** [comment]
They are wrappers for Windows API. So if you're not running on Windows, none of the APIs are there at all. There are some bits of NAudio that are not OS dependent, but all the recording, playback and most of the format conversion uses Windows APIs.

**Comment by abhi18av** [comment]
So that is to say that this layer abstracts way all the dependencies on drivers, please do so correct me if I'm mistaken.
