### ISSUE TITLE
new NuGet version

### ISSUE THREAD

**Issue by kroky-cs** [naudio/NAudio#131]
Is there any new NuGet version?, because I want to use SilenceProvider and I can't use it.

**Comment by markheath** [comment]
Sorry, not yet. A new NuGet version is long overdue I know. I'm planning to do one soon, but just need to finish testing a PR first

**Comment by StefH** [comment]
Any update?

**Comment by markheath** [comment]
Sorry, the PR in question proved more involved than I'd hoped, but would like to find time to get a new version out anyway in the near future. NAudio is just a spare time project for me, and sadly not getting a lot of that at the moment.

**Comment by StefH** [comment]
Is it possible to exclude that PR and create a nuget with latest code?

**Comment by markheath** [comment]
yes, that is the plan. just need to find the time to do it. Sorry for the inconvenience

**Comment by markheath** [comment]
NuGet version 1.8.0 is now available
