### ISSUE TITLE
Missing 'mfplat.dll' on windows xp sp3 32bit

### ISSUE THREAD

**Issue by heku** [naudio/NAudio#134]
Hi,

Great thanks for coding this component, I have to develop a product which supports windows XP as well, today I got below error, is there anyone who knows how to resolve this, thank you very much in advance.

-----------------
Unable to load DLL 'mfplat.dll': The specified module could not be found.  (Exception from HRESULT: 0x8007007E)
   at NAudio.MediaFoundation.MediaFoundationInterop.MFStartup(Int32 version, Int32 dwFlags)
   at NAudio.MediaFoundation.MediaFoundationApi.Startup()
   at NAudio.Wave.MediaFoundationReader..ctor(String file, MediaFoundationReaderSettings settings)
   at NAudio.Wave.MediaFoundationReader..ctor(String file)
   at NAudio.Wave.AudioFileReader.CreateReaderStream(String fileName)
   at NAudio.Wave.AudioFileReader..ctor(String fileName)

**Comment by markheath** [comment]
I'm afraid you can't use Media Foundation on Windows XP. Those APIs were introduced as part of Windows Vista.

**Comment by heku** [comment]
Thank you a lot for your prompt reply!
The exception seems threw in the constructor of AudioFileReader, if I cannot use the AudioFileReader, which one should I use?

Here's my code related this.

```C#
        private void CreateInputPipe()
        {
            _microphone = new WaveInEvent
            {
                WaveFormat = Configuration.DefaultWaveFormat,
                DeviceNumber = Configuration.RecorderDeviceId
            };
            _buffer = new BufferedWaveProvider(_microphone.WaveFormat);                 //PCM 16bit
            _volumeProvider = new VolumeWaveProvider16(_buffer);                        //PCM 16bit
            var meter = new MeteringSampleProvider(_volumeProvider.ToSampleProvider()); //IeeeFloat 32bit
            var wave16 = new SampleToWaveProvider16(meter);                             //32 -> 16
            _waveRecorder = new WaveRecorder(wave16, _option.File);

            _volumeProvider.Volume = _desiredVolume;
            _microphone.DataAvailable += OnMicrophoneDataAvailable;
            _microphone.RecordingStopped += OnMicrophoneRecordingStopped;
            meter.StreamVolume += OnMeteringStreamVolume;
        }
```

**Comment by heku** [comment]
Thanks for your reminder, I have resolved this after checking the AudioFileReader code, I changed my temp audio file from 'xxx.tmp' to 'xxx.wav', it works.

**Comment by markheath** [comment]
OK, should probably put something in `AudioFileReader` to stop that being tried on XP. Under the hood it tries to use `WavFileReader` first, but if it doesn't know how to play the file it falls back to `MediaFoundationReader`

**Comment by rzr** [comment]
> I'm afraid you can't use Media Foundation on Windows XP. Those APIs were introduced as part of Windows Vista.

just for curiosity has been any effort to backport this to XP or wine or even reactOS ?
