### ISSUE TITLE
Possible to get WaveForm data from MP3?

### ISSUE THREAD

**Issue by Lutando** [naudio/NAudio#135]
I am writing an application that runs on Azure that requires to extract waveform data from an mp3 file. Is this possible with NAudio if the application environment doesn't contain Media Foundation (as do all azure web apps)? basically input as mp3 and an output of an array of `x` sampled amplitudes is what i'm looking for. TIA

**Comment by markheath** [comment]
It's a bit of a pain on Azure, as you can't use `Mp3FileReader` either since that relies on ACM. Probably the best bet is to use [NLayer](http://nlayer.codeplex.com/) which is a fully managed MP3 frame decoder that can be plugged into `Mp3FileReader`

**Comment by Lutando** [comment]
Thank you so much, will give this a try.
