### ISSUE TITLE
MIDI API enhancements

### ISSUE THREAD

**Issue by jnm2** [naudio/NAudio#137]
Ideas for a number of API enhancements came up in #117. Any of the statements below are open to challenge. =)

Based on the discussion here and @markheath's ultimate decisions on each of these, I'll send targeted PRs based off preliminary work I've already done.

---

### 1. Unique `MidiEvent` subclass for every type and all classes abstract or sealed
**Benefits**: If a `MidiEvent` has command code `NoteOn`, it's definitely a `NoteOnEvent` and not just a `NoteEvent` or `MidiEvent`. The onus is always on the subclass to figure out if it's doing the right thing to clone or to export properly.
**Breaking**: `new NoteEvent` and `new MidiEvent` and `new MetaEvent` will cease working because they will be abstract.

---

### 2. Require constructors to initialize all state from parameters
**Benefits**: Cleaner and clearer.
**Breaking**: Existing constructors will have to either be removed or included as obsolete, calling the full constructor with defaults.

---

### 3. Use consistent constructor parameter order in `TempoEvent`
**Benefits**: Type (if abstract) and time are always the first parameters
**Breaking**: Parameter values are swapped without warning on upgrade

---

### 4. Convert all `BinaryReader` constructors to static `Import` methods
**Benefits**: `BinaryReader` is really an expected common pattern, importing should be done more symmetrically to the `Export` method
**Breaking**: `BinaryReader` constructors will be removed. Obsoleting is possible but undesirable because the implementation should be in `Import`, but the constructor can't utilize it from there. `MetaEvent.ReadMetaEvent` should become `MetaEvent.Import` for consistency.
`SysexEvent.ReadSysexEvent` should become `SysexEvent.Import` for consistency.

---

### 5. Remove `DeltaTime`
**Benefits**: It's not kept in sync and has no meaning outside a read-only list of events; it's an implementation detail of the file format.
**Breaking**: `DeltaTime` will be removed because it's not clear how to maintain sensible values.

---

### 6. Rename `ActiveSensing` to `AutoSensing` and `*AfterTouch` to `*Aftertouch`
**Benefits**: In the MIDI spec, 'active sensing' is the term used since it refers to constant action being taken. 'Aftertouch' is a single word.
**Breaking**: `MidiCommandCode.ActiveSensing`, `.KeyAfterTouch`, and `.ChannelAfterTouch` to remove or obsolete, `ChannelAfterTouchEvent` to be removed or replaced with dummy obsolete class so the code is compilable.

---

### 7. `NoteOnEvent.AbsoluteTime` automatically setting `OffEvent.AbsoluteTime`
**Benefits**: If `NoteLength` changes change its absolute time, why not `AbsoluteTime` changes? Or is it better not to sync at all, since we don't sync backwards to the note on event?
**Breaking**: Can't think of anything; behavior change?

---

### 8. Remove `Channel` from `MidiEvent` and create a base `ChannelEvent`?
**Benefits**: Better representation of the fact that some events simply don't have a channel.
**Breaking**: You'd have to check if in event is `ChannelEvent` before accessing `Channel`. This makes logical sense, but is it a good API?

----

Notes to self:
 * `TimeSignatureEvent`, `KeySignatureEvent` and `SmpteOffsetEvent` `byte` properties should go back to `int`
 * `NoteOnEvent.OffEvent` should be typed `NoteOffEvent` and the code check can be removed

**Comment by markheath** [comment]
thanks for this thorough analysis and sorry its taken me longer than planned to get back to you. have had a bit of winter flu recently. 

The first thing to say is that several of these can be done without any breaking changes, and that is always my preference as I take quite a conservative approach to breaking the NAudio API. I like to keep existing API in and marked obsolete for one minor version before removing where possible.

So for example, we can mostly do (2) by adding new constructors and obsoleting old ones. (6) can also be done purely with obsoleting.

I'll try to share some MIDI file parsing code I have which may help you understand why things like (5) Delta Time are in there. I have written several utilities that help manufacturers of MIDI drum grooves to perform automatic mapping and fixups of the MIDI files. Take a look at http://midifilemapper.codeplex.com/ and http://midifilesplitter.codeplex.com/ as examples, although I have several other more up to date projects as well.

Note that it's quite common to use NoteOn with velocity 0 as a `NoteOff` and NAudio needs to support using either.

(7) is an interesting one. I suspect it is safe, but will have to check it doesn't result in double-compensation in my utilities

Hold off (3) for now. That's the nastiest breaking change as it's a silent one.

(1) could be done in two phases, where the new classes are introduced but the old ones not made abstract initially.

Anyway, hopefully that gives some items we can progress quickly, and then can discuss the breaking ones in more detail later.
