### ISSUE TITLE
Is there a particular reason not to expose AsioDriver, AsioDriverCapabilities etc to outside?

### ISSUE THREAD

**Issue by vsoldatkin** [naudio/NAudio#139]
Right now all of the underlying ASIO bindings and wrappers are internal. 
I'm trying some approaches to ASIO recording and could utilize some handy info about actual ASIO driver capabilities like preferred buffer size for example.

**Comment by markheath** [comment]
Only reason is that the more things that are public, the harder it is to refactor as changes are breaking, and also the more potential for users to be confused about which classes they are supposed to use. But I can see it would be handy to expose more low-level info about ASIO driver somehow.

**Comment by vsoldatkin** [comment]
Especially so since the current ASIO recording implementation encourages a low level approach and seemingly didn't evolve since your blog post on this matter from 2012.

Looks like there is a room for improvement here. What is the current abstraction layer for a recording audio source? Is it IWaveIn interface?

**Comment by markheath** [comment]
yes, but IWaveIn / IWaveOut are a bad fit for ASIO, which presents the playback and recording parts of the soundcard in a unified way rather than as two separate devices like mmio and WASAPI do. So the ASIO recording side of NAudio has always been a bit ugly.

**Comment by markheath** [comment]
have made AsioDriver and AsioDriverExt public now
