### ISSUE TITLE
Can this library be used to export MIDI files into mp3 or wave files?

### ISSUE THREAD

**Issue by nefcanto** [naudio/NAudio#140]
Hi

I read codeplex documentation, and I couldn't find anything to get my answer. Yet the more I look at this library, the more I realize how sophisticated it is. I just need to convert midi files into mp3 or wave files. And I need to do that programatically. Does this library do that? If so, where can I find a quick code snippet?

**Comment by markheath** [comment]
NAudio doesn't have anything built-in to do that. You could use WasapiLoopbackCapture to capture the audio if you can play the MIDI file through a software synthesizer. An alternative is to see if you can script [FluidSynth](http://www.fluidsynth.org/) to do it
