### ISSUE TITLE
Asio AudioAvailable event doesn't trigger after a while

### ISSUE THREAD

**Issue by AdrianSTANCULESCU** [naudio/NAudio#144]
Hi Mark,

After a while the AudioAvailable event handle isn't triggered anymore. Could be a driver issue or a hardware issue? I've tested with a MAYA44 USB board and a MOTU 16A board, 
private void AudioManager_AsioAudioAvailable(object sender, AsioAudioAvailableEventArgs e)
{
}
Cannot be constantly reproduced. On Windows 10 is working on 98% situations. On Windows 7 is failing more often.
What boards have you tested so far for asio development?
Thank you,
Adrian,

**Comment by markheath** [comment]
Have you subscribed to the `PlaybackStopped` event - should get fired if there is some kind of problem with the Exception set.
I've only been able to test on the limited set of ASIO devices I've actually owned which is only a handful.

**Comment by AdrianSTANCULESCU** [comment]
Didn't tried. I will be back with an answer. Thanks.

**Comment by AdrianSTANCULESCU** [comment]
HI Mark,
Seems to be a driver issue. Thanks for your answer.
You may close the issue.

**Comment by markheath** [comment]
great, glad you got to the bottom of this
