### ISSUE TITLE
File not release with WaveFileReader 

### ISSUE THREAD

**Issue by LePelicaN** [naudio/NAudio#145]
Hello everybody,

First, thanks a lot for you library. It's great.

Now, my issue: it seems that WaveFileReader doesn't release the file used if the construction fail early.

Here is how to reproduce:
```C#
[TestMethod]
public void NAudio_ReleaseFail()
{
    var path = Path.GetTempFileName();
    File.WriteAllBytes(path, new byte[] { });
    try
    {
        using (var reader = new WaveFileReader(path))
        { }
    }
    catch (Exception e)
    { }
    File.Delete(path); // Exception here
}
```

And this give a nice EndOfStreamException.

If I can give my opinion, I think the constructor of WaveFileReader is missing a `inputStream.Close()` before the `inputStream.Close()` (in case it's own).

Thanks,
Jonathan

**Comment by markheath** [comment]
hi, this bug is fixed in latest code already. Will be improved when next version of NAudio is released

**Comment by LePelicaN** [comment]
Thank you.
