### ISSUE TITLE
WaveFileReader.SampleCount member name and/or comment are misleading

### ISSUE THREAD

**Issue by vsoldatkin** [naudio/NAudio#148]
In the current implementation SampleCount is effectively a number of frames or a number of samples **per channel**.  A comment section suggests this is a total number of samples and one needs to divide it by channels count to get frames count / samples per channel, which is wrong. A note that SampleCount does not take channels into account just makes things less clear.

https://github.com/naudio/NAudio/blob/4bf547fa695edc2e53d08032180cb7592788e84b/NAudio/Wave/WaveStreams/WaveFileReader.cs#L154

**Comment by markheath** [comment]
oops, should say multiply - good spot

**Comment by vsoldatkin** [comment]
Wasn't it better to introduce new members such as SampleCountPerChannel (or FrameCount) and TotalSamplesCount? SampleCount may also be marked as obsolete if you wish not to break existing implementations right away.

**Comment by markheath** [comment]
Yes could be named better, but want to avoid breaking changes. I'd be happy to accept a PR for something better, but seems like hardly anyone actually uses this property because this issue has been present for a very long time.
