### ISSUE TITLE
NAudio solution not building

### ISSUE THREAD

**Issue by Slion** [naudio/NAudio#149]
I was trying to build NAudio.sln and I'm getting the following obscure errors: http://pastebin.com/shbMbhrN
What am I missing?

I then tried the Universal solution and although it compiles I could not run it. Well I never actually worked with Universal apps so I'm not sure what to look for. It complains that I needed to deploy it which I tried to do as instructed but still it would run. Is the time of being able to just build and run from VS gone?

**Comment by markheath** [comment]
Do you have VS2015 with all latest updates installed?
Not sure why you are seeing this issue

**Comment by Slion** [comment]
Indeed running latest VS2015.
I could locate that TXT log mentioned in the error and it contains the following.
http://pastebin.com/73dgfjcw

So it looks like the toolchain is getting confused with my Culture. I'm running an English Windows 10 with French keyboard input located in Germany, so maybe that confuses it. I'm working with quite a few other VS projects and none have had problems with that.

**Comment by Slion** [comment]
I fixed it by switching my Culture from English (Europe) **en-150** to English (United Kingdom) **en-GB**.
To do that you need to head to _Control Panel\All Control Panel Items\Language_ and click on "change date, time or number formats". Once you picked a more VS friendly Culture from the "Formats" tab you should really apply to all accounts through the "Administrative" tab to avoid further mischief.

**Comment by markheath** [comment]
glad you worked it out
