### ISSUE TITLE
Looped Pitch Changing WaveStream?

### ISSUE THREAD

**Issue by lucasheer** [naudio/NAudio#152]
Hello! I had this problem awhile back, but I was never actually able to fix it. I continued to use beeps instead of real instrument sounds for my instrument project. I have my program making a continuous brass sound by using a LoopStream class I found, that basically overrides the WaveStream class to loop it once it is finished. I have read that because of the microsoft .Net Stream, you have to have this signature?

`Public Overrides Function Read(buffer As Byte(), offset As Integer, count As Integer) As Integer`

Like I said, a continuous note works great, but I need to be able to change the Read function to bend the pitch. So I found the SmbPitchShiftingSampleProvider. However, it uses a read signature of :

`Public Function Read(buffer As Single(), offset As Integer, count As Integer) As Integer`

I realize that I could just change it, but I am having trouble converting byte() to single(). I'm not sure how the byte() buffer is structured anyways :( This was my 3rd try at converting the byte() into 16 bit mono float samples for me.

` Dim mono As Single() = New Single(sampRead / 2 - 1) {}
            Dim index = 0
            For sample = offset To sampRead + offset - 1 Step 2
                mono(index) = CType(BitConverter.ToInt16(New Byte() {buffer(sample), buffer(sample + 1)}, 0), Single)
                index += 1
            Next
            shifterLeft.PitchShift(pitch, mono.Length - 1, fftSize, osamp, WaveFormat.SampleRate, mono)
            index = 0
            For sample = offset To sampRead + offset - 1 Step 2
                Dim resSin As Int16 = Limiter(mono(index))
                Dim resSinBytes As Byte() = BitConverter.GetBytes(resSin)
                buffer(sample) = resSinBytes(0)
                buffer(sample + 1) = resSinBytes(1)
                index += 1
            Next`

My other question was, if there is any way that I can loop the SmbPitchShiftingSampleProvider, instead of having to make a whole LoopStream class implementing WaveStream? Thank you!

**Comment by lucasheer** [comment]
I managed to get it to work! I modified the LoopStream Class.

http://pastebin.com/fKcgFELc
^^ takes around 16 milliseconds to complete this code

However, it is very laggy. Im using a small wave sample that i can repeat 250 times, and its still under a second. It loops just fine, but when I change the pitch 100 times a second, it only sounds like its changing maybe 3 times. It also seems like there is a delay from when i change it in my GUI thread, to the actual audio playing thread. Does anyone know why this happens?

**Comment by markheath** [comment]
this is to do with latency - the way audio playback works is you fill a buffer of audio ahead of time. In NAudio the default is round 200ms, so that entire block will be same pitch.
And yes, DSP is usually CPU intensive. I tend to use SoundTouch for my pitch shifting needs as it is highly optimized.

**Comment by Freefall63** [comment]
As the creator of the SmbPitchShiftingSampleProvider I can tell you what causes the latency.

The internal buffer is filled and returns nothing, until there is enough for a first STFT run. Supposing a samplerate of 44100 and the default FFT Size of 4096 this leads to a delay of 4096 / 44100 = 0,093 s = 93 ms.

And your code seems to have some errors in the loops, I recommend to work with the official class or copy the code in from there.

-Freefall-
