### ISSUE TITLE
Support Xamarin

### ISSUE THREAD

**Issue by naweiss** [naudio/NAudio#153]
I tried to install this Package through nuget in Xamarin, but it failed.
The installer said that it's not supported.
Can you fix it.

I would also like to be able to install only NAudio.Wave without having to install all the package (it relatively big one).

**Comment by markheath** [comment]
A large part of NAudio is providing interop wrappers for Windows audio APIs, which unfortunately would not work in Xamarin, so there is no current plan to make a Xamarin version of NAudio
