### ISSUE TITLE
Simultaneous play music from multiple audio devices

### ISSUE THREAD

**Issue by Timsanxyz** [naudio/NAudio#156]
I am working on a small program for school.
For the moment there are two sound cards and each plays school bell at a specified time using WaveOut.
What I need to add: play music from playlist from both sound cards during a break or after all the lessons are over.
I could start the music, but I can not stop it. It plays until the end. 
What can a use to play music at both soundcards and stil control it (play/pause)?

**Comment by markheath** [comment]
You can use the `Pause` and `Stop` methods on `WaveOut`. Just make sure that you hold onto the instance of `WaveOut` that you started playing with.

**Comment by Timsanxyz** [comment]
@markheath how can I hold onto the instance?

For the moment, this is how I play schoolbell:
There is selection of soundcard and the ringtone

public void playSchoolBell(int audioDeviceNumber, string audioUrl)
        {
            IWavePlayer waveOutDevice;
            waveOutDevice = new WaveOut();
            AudioFileReader audioFileReader;
            audioFileReader = new AudioFileReader(audioUrl); //Подгружаем файл проигрывания
            var waveOut = new NAudio.Wave.WaveOut();
            waveOut.DeviceNumber = audioDeviceNumber; //вот тут выбираем звуковую карту - 0 = дэфолтная, 1 - дополнительная.
            waveOut.Init(audioFileReader);
            waveOut.Play();
        }

**Comment by markheath** [comment]
You hold on by making the IWavePlayer a member of your class.
Here's an example:

```
private WaveOut waveOut;
private AudioFileReader audioFileReader;
public void playSchoolBell(int audioDeviceNumber, string audioUrl)
{
    if (waveOut != null) return; // already playing something
    waveOut = new WaveOut();
    waveOut.PlaybackStopped += OnPlaybackStopped;
    audioFileReader = new AudioFileReader(audioUrl);
    waveOut.DeviceNumber = audioDeviceNumber;
    waveOut.Init(audioFileReader);
    waveOut.Play();
}

private void OnPlaybackStopped(object sender, PlaybackStoppedEventArgs args)
{
    if (audioFileReader != null) audioFileReader.Dispose();
    audioFileReader = null;
    if (waveOut != null) waveOut.Dispose();
    waveOut = null;
}

```

**Comment by Ucheha** [comment]
am writing a program for school bell also, i have service that using NAudio to play the sound,
the program is working well for some time, then it is not playing the mp3,
here is my code.

btw - on my computer it works well most the time,
for other computer the issue happens !!
can someone help?

 private void StartSchedule(string media, int durationTime)
        {
            _eventLog.WriteEntry("StartSchedule at : " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
            WaveOutEvent waveOut = null;
            Mp3FileReader mp3Reader = null;
            try
            {
                waveOut = new WaveOutEvent();
                mp3Reader = new Mp3FileReader(media);

                bool normal = true;
                waveOut.Init(mp3Reader);
                TimeSpan timeSpan =  mp3Reader.TotalTime;
                int remainTime = 0;
                if(timeSpan.TotalSeconds < durationTime)
                {
                    normal = false;
                    int numberOfLoops = durationTime / timeSpan.Seconds;
                    remainTime = durationTime % timeSpan.Seconds;
                    for (int i=0; i < numberOfLoops; i++)
                    {
                        waveOut.Play();
                        System.Threading.Thread.Sleep(timeSpan.Seconds * 1000);
                        waveOut.Stop();
                        mp3Reader.Position = 0;
                    }
                }
                mp3Reader.Position = 0;
                if (normal)
                {
                    waveOut.Play();
                    System.Threading.Thread.Sleep(durationTime * 1000);
                    waveOut.Stop();
                }
                else
                {
                    waveOut.Play();
                    System.Threading.Thread.Sleep(remainTime * 1000);
                    waveOut.Stop();
                }
                
                if (mp3Reader != null)
                    mp3Reader.Dispose();
                if (waveOut != null)
                    waveOut.Dispose();
            }
            catch(Exception e)
            {
                _eventLog.WriteEntry($"Error while playing mp3 file.\n{e.Message}", EventLogEntryType.Error);
            }
            finally
            {
                if(mp3Reader!= null)
                    mp3Reader.Dispose();
                if(waveOut != null)
                    waveOut.Dispose();
            }
        }

**Comment by markheath** [comment]
It is best not to re-start Playing until you've got the `PlaybackStopped` event. I wonder if you need the Play and Stop in your loop. Why not just reposition the mp3Reader back to the start after the desired time.
