### ISSUE TITLE
multiplexing fails on 1.8.0, work fine on 1.7.3 and previously

### ISSUE THREAD

**Issue by fabcal24** [naudio/NAudio#157]
Error is index out of range on all devices types in 1.8.0. In 1.7.3 work fine.

Asio on Hercules mk4 console in Asio mode fail on asio create buffer and also show ASE error

**Comment by markheath** [comment]
can you provide more information? what are you trying to achieve?

**Comment by fortunereject** [comment]
Got the same problem in initializing WasapiOut with MultiplexingWaveProvider. This is fixed in 1.9.0, possibly in #335
