### ISSUE TITLE
Mismatch between Pcm32BitToSampleProvider and BitConverter

### ISSUE THREAD

**Issue by mc0re** [naudio/NAudio#158]
Hi,

I noticed a strange difference between `NAudio.Pcm32BitToSampleProvider` and `Microsoft.BitConverter`.
When providing a value of 1.0, `BitConverter.GetBytes()` (which is by the way a very fast operation) converts it to four bytes `3F 80 00 00` (written to the stream from the end), which get converted by `Pcm32BitToSampleProvider.Read()` to 0.4960938... Is this correct? I thought, PCM floating point uses standard IEEE float...

**Comment by mc0re** [comment]
And if I provide byte sequence `80 00 00 00` (reversed as well), which is supposed to represent 1, to `Pcm32BitToSampleProvide`, it returns -1. What do I misunderstand?

**Comment by markheath** [comment]
No, 32 bit PCM is different from IEEE float. You don't come across it very often, usually it means the samples are 24 bit but stored in a 32 bit int as that's easier to work with in memory.

**Comment by mc0re** [comment]
Would it make sense to use BitConverter to convert to Long, then to Single by division?


Sent from my Windows 10 phone

**Comment by markheath** [comment]
Yes, use BitConverter.ToInt32

**Comment by mc0re** [comment]
I mean, do that in NAudio provider, instead of the many byte operations.


Sent from my Windows 10 phone

**Comment by markheath** [comment]
NAudio uses bit manipulation for performance reasons. The results are the same

**Comment by mc0re** [comment]
‘*(long*)value’ is faster than any bit operations.


Sent from my Windows 10 phone

**Comment by markheath** [comment]
longs are 64 bit in C#, but yes it could be made faster if we used unsafe code.

**Comment by mc0re** [comment]
Sorry, wrote in a hurry [😊]


It looks like `BitConverter.GetBytes` uses such code - take a look at Microsoft reference source.

________________________________
