### ISSUE TITLE
MasterPeakValue returning 0 when recording device tab within audio settings isn't opened. 

### ISSUE THREAD

**Issue by EldinZenderink** [naudio/NAudio#160]
When I am reading the peak value of a MMDevice it won't start getting values unless I open my audio devices window and click on the recording devices tab. After that, as long this window is open in the background it works just fine. Happens to me on both Windows 10 Pro and Windows 7 Home.

**Comment by markheath** [comment]
I'm afraid I don't know why this is. There might be something in the MMDevice documentation on MSDN that explains it.

**Comment by EldinZenderink** [comment]
Well, as I don't need a perfect value for peak volume, just a value that represent sound so I can detect if there is any, i've worked my way around this issue by just recording trough WaveIn and just parse the sample as soon there is available data (which is available quick enough). Anyway, thanks for the response.

**Comment by markheath** [comment]
OK glad you found a workaround
