### ISSUE TITLE
SfzFileReader

### ISSUE THREAD

**Issue by davidluzgouveia** [naudio/NAudio#162]
What's the deal with the SfzFileReader on:

https://github.com/naudio/NAudio/blob/master/NAudio/FileFormats/Sfz/SfzFileReader.cs

It's particularly creepy how the comment on line 100 just cuts o

**Comment by markheath** [comment]
lol, yeah that class has been in there right from the beginning 15 years ago! Probably should just take it out!

**Comment by markheath** [comment]
have deleted it

**Comment by davidluzgouveia** [comment]
No plans to incorporate an *actual* SFZ parser into NAudio? :)

**Comment by markheath** [comment]
Happy to accept one as a contribution, but have no need for one myself at the moment.

**Comment by davidluzgouveia** [comment]
Roger. Personally I've been using one I based off the code at https://csharpsynthproject.codeplex.com/ but I *kinda* remember having had to correct a bug with it, and now I don't remember what it was. But I think it was the annoying kind that was probably introduced by copy pasting similar code, like mistaking an y for an x somewhere.
