### ISSUE TITLE
WaveFileWriter - WAV file too large check

### ISSUE THREAD

**Issue by arndre** [naudio/NAudio#166]
when` WaveFileWriter.WriteByte(b)` is called in a loop, writing to multiple different files (in our case ~12), the check 
```
   if (outStream.Length + count > UInt32.MaxValue)
                throw new ArgumentException("WAV file too large", "count");
```
 consumes too much time.

**Comment by markheath** [comment]
I don't recommend you use `WriteByte` which comes from base class of `Stream`. Instead use `Write` and pass in a byte array for much better performance.

**Comment by arndre** [comment]
That's what I thought. We are planing to get rid of writing the file byte by byte beacuse it's a disaster when it comes to performance. Thanks for the quick response.
