### ISSUE TITLE
MediaFoundationReader is not releasing the files on close or dispose

### ISSUE THREAD

**Issue by djomen** [naudio/NAudio#167]
Hi,

MediaFoundationReader is not releasing the files on close or Dispose. I have tried having reader.Close() and reader.Dispose() outside of using too but the reader still seems to keep hold of the file it has been reading until the application terminates.

I don't have anything holding onto these file and if i comment out the below lines the files don't get locked.

I have also tried setting the reader to null but that doesnt help either.

Thanks
Damian

```
 var mediaType = MediaFoundationEncoder.SelectMediaType(
                    AudioSubtypes.MFAudioFormat_AAC,
                    new WaveFormat(44100, 1),
                    0);

                var enc = new MediaFoundationEncoder(mediaType);
                using (var reader = new MediaFoundationReader(tempFile))
                {
                    enc.Encode(outputFile, reader);
                    enc.Dispose();
                }
```

**Comment by djomen** [comment]
this looks to be down to a com object not being released.

I have added a System.GC.Collect(); after the above and it releases the objects.

**Comment by markheath** [comment]
glad you found a solution.
