### ISSUE TITLE
Remove check, that causes dozens times slow down!

### ISSUE THREAD

**Issue by TishSerg** [naudio/NAudio#170]
In NAudio/Wave/WaveOutputs/WaveFileWriter.cs
In method
```
        public override void Write(byte[] data, int offset, int count)
        {
            if (outStream.Length + count > UInt32.MaxValue)
                throw new ArgumentException("WAV file too large", "count");
            outStream.Write(data, offset, count);
            dataChunkSize += count;
        }
```
Remove
```
            if (outStream.Length + count > UInt32.MaxValue)
                throw new ArgumentException("WAV file too large", "count");
```
This just 2 lines causing to slow down performance by dozens of times!
You can ensure it by writing same count samples into wav-file using 2 ways:
+ WaveFileWriter.Write(byte[] data, int offset, int count)
+ WaveFileWriter.WriteSamples(short[] samples, int offset, int count). 

Dozens of times Carl!
It is  because `WaveFileWriter.WriteSamples()` not rely on `WaveFileWriter.Write()` (it relies on BinaryWriter), so that superinefficient check not performed. Why you added that check there, if in case of using `WaveFileWriter.WriteSamples()` wav oversize will not be detected anyway?

**Comment by markheath** [comment]
Yes, that probably could do with some optimization, but generally I recommend against using `WriteSamples`. You should normally just use the `Write` method, which is what will be called automatically if you are using `CreateWaveFile` and passing in an `ISampleProvider` or `IWaveProvider`.

**Comment by TishSerg** [comment]
When I using `WriteSamples` I can write data as it come. When using `CreateWaveFile` I must already have all data to write.
