### ISSUE TITLE
Managed Debugging Assistant 'FatalExecutionEngineError' has detected a problem in 'C:\Users\MyUsername\Documents\Visual Studio 2013\Projects\YAMP\YAMP\bin\Debug\YAMP.vshost.exe'.

### ISSUE THREAD

**Issue by rsdkz** [naudio/NAudio#171]
Everytime I switch music while other music is playing, my application crashes with the error message
`Managed Debugging Assistant 'FatalExecutionEngineError' `and this text (in German): `Die Laufzeit hat einen schwerwiegenden Fehler entdeckt. Fehleradresse: "0x748afeff" in Thread "0xe08". Fehlercode: 0xc0000005. Bei diesem Fehler könnte es sich um ein Problem in der CLR oder in den unsicheren oder nicht verifizierbaren Teilen des Benutzercodes handeln. Übliche Ursachen dieses Bugs sind Marshallerfehler für COM-Interop oder PInvoke, die den Stapel beschädigen können.`

**Comment by markheath** [comment]
what are you doing in NAudio when this happens? What classes are you using for playback?

**Comment by rsdkz** [comment]
I first check if WaveOut and Mp3FileReader are not null, if yes I'm disposing them and then I create a new instance of these classes using with the new file, and at that point it crashes everytime. When I stop the music before I load a new music file then it doesn't crash.

I am only using Mp3FileReader and WaveOut.

**Comment by markheath** [comment]
I've not seen that issue before myself. Sounds like there could be a driver problem - check you have the latest soundcard drivers. Also, try not starting again until you've received the PlaybackStopped event from the first WaveOut
