### ISSUE TITLE
Could not find DLL entry point - MFCreateMFByteStreamOnStreamEx

### ISSUE THREAD

**Issue by rinkako** [naudio/NAudio#176]
In Windows 7, using StreamMediaFoundationReader to play a memory stream would probably cause this exception. I found that in **NAudio.MediaFoundation.MediaFoundationInterop**, line 69-82, and also in the **MediaFoundationHelper**, there is a IF when `NETFX_CORE` then use `MFCreateMFByteStreamOnStreamEx`, which cause the application will try to use the API: `MFCreateMFByteStreamOnStreamEx` in mfplat.dll in  windows 7 and cause exception "Could not find DLL entry point - MFCreateMFByteStreamOnStreamEx".

I found this API on MSDN, it says that the **minimum** supported client of this API is Windows **8**, that may be the reason the application work improperly. 

And after I replaced `MFCreateMFByteStreamOnStreamEx` by `MFCreateMFByteStreamOnStream`, the application work properly on Windows 7. Is this a little bug? :)

**Comment by markheath** [comment]
NETFX_CORE is for WinRT applications, so it shouldn't be present if you are building Windows 7 apps. What framework are you targeting?

**Comment by rinkako** [comment]
The application was built on .NET Framework 4.0 with WPF. Before I solve this problem, I took the EXE file run on Windows 7 PC (both x86 and x64, Simplified Chinese Language, and I'm sure that they are not WinRT) and this exception was thrown. After I removed the code of NETFX_CORE and only use `MFCreateMFByteStreamOnStream` , the application works properly on the above Win7 PC. Amazing.

**Comment by kellyelton** [comment]
I have a desktop WPF application targeting .net 4.6 and this is happening on Windows 7 for me also.

Latest nuget of NAudio.

**Comment by kellyelton** [comment]
![image](https://cloud.githubusercontent.com/assets/1356163/26415840/dc019528-4081-11e7-9d76-79d753640acb.png)

**Comment by kellyelton** [comment]
It's understood that
`#if NETFX_CORE`
Only happen on build right? So that conditional doesn't even get run by anyone consuming this library.

It seems like the dll that's being distributed is built with the NETFX_CORE symbol or something.

**Comment by kellyelton** [comment]
![image](https://cloud.githubusercontent.com/assets/1356163/26416308/72df9444-4083-11e7-8f1a-c169e7b731d3.png)
This is from packages\NAudio.1.8.0\lib\net35\NAudio.dll

**Comment by markheath** [comment]
Yes, that method is in [Win 8](https://msdn.microsoft.com/en-us/library/windows/desktop/hh162754(v=vs.85).aspx) and above only. Not sure why that NETFX_CORE symbol is being set on the regular NAudio build though

**Comment by kellyelton** [comment]
Looks like the fix just hasn't been released yet.
