### ISSUE TITLE
ADSR/EnvelopeGenerator won't allow attack/decay less than 1 second.

### ISSUE THREAD

**Issue by WamWooWam** [naudio/NAudio#177]
I'm currently writing a synthesizer using NAudio in C#, for a while now, there's been one thing I've not been able to do, that being ADSR

I've discovered that currently, I can't create attack windows less than one second either using the ADSR sample provider or directly with the EnvelopeGenerator, even 1ms less and it all falls to pieces.

This is quite annoying, as the music I'm trying to create relies heavily on ADSR Envelopes.

**Comment by markheath** [comment]
there shouldn't be a problem with attacks of less than 1 second - I've used much shorter attacks without issues.

**Comment by WamWooWam** [comment]
So, it turns out, it was my fault for dividing my millisecond value by `1000` not `1000f`. Producing a double not a float. For whatever reason neither intellisense nor the compiler picked that up and all casts were declared redundant. It works just fine now. Sorry!
