### ISSUE TITLE
The Windows Universal build seems to be non functional...

### ISSUE THREAD

**Issue by Danthekilla** [naudio/NAudio#179]
The UWP version compiles fine but fails to function. But there is a working win8 version...

Whats the deal with that, and when will the UWP version be working, I would love to integrate this into a game engine for windows and xbox but we use 100% UWP.

**Comment by markheath** [comment]
what's not working for you? have you tried running the NAudio UWP demo app - you should be able to play and record with WASAPI. The UWP version is still experimental - unfortunately I have not had capacity to develop it recently, although I have been accepting bug fixes and enhancements via pull requests.

**Comment by vbisbest** [comment]
I have the same issue.  NAudio.Wave is missing a lot of classes like WaveFileReader and WaveRecorder.  And WasapiCapture does not exist.  This is NAudio 1.8 pulled from Nuget.

**Comment by markheath** [comment]
Yes, unfortunately UWP apps are very restricted in the APIs you can call, and so WaveFileReader and others can't compile in their current forms. There's a whole new way to interact with the file system, so ideally it needs a rewrite. There is WasapiOutRT and WasapiCaptureRT which you can try. Really the UWP support in NAudio is still in a beta state. I sadly have not had the time needed to create a really good audio API for UWP. There is also the AudioGraph API that is worth looking at if you are doing audio in a UWP app, and ideally a future version of NAudio would be compatible with that as well.
