### ISSUE TITLE
COMException: Class not registered

### ISSUE THREAD

**Issue by generalui-glados** [naudio/NAudio#181]
Hi there,

  I've installed NAudio via Nuget in Visual Studio 2017
  I'm developing a UWP app and I'm getting COM Exceptions when trying to use anything in the framework.

  For example, simply calling
`            var deviceEnum = new MMDeviceEnumerator();
`

Is throwing a COMException: Class not registered in Safetypes.g.cs

Any ideas on how to remedy?  
I'm very new to developing on Windows, so a LOT of references to Windows specific things sound like complete gibberish to me.

I have a experience developing audio applications on other platforms, so I'm not completely ignorant, I just can't get Visual Studio to let me write code.  

Thanks!

**Comment by markheath** [comment]
what operating system are you trying to run on? what sort of application are you building?

**Comment by generalui-glados** [comment]
Developing on Windows 10 - Putting together an app that can run on the Desktop and the Hololens.

The bulk of the app is written in C# and uses AudioGraph for audio processing.  I need something with lower latency and was looking at wrappers for WASAPI and ASIO (I can't seem to control buffer size with AudioGraph)

**Comment by markheath** [comment]
OK, you won;t be able to use ASIO at all on hololens. And UWP apps are quite restricted in what COM objects are available. There is a very rudimentary UWP sample that comes with the NAudio source code - it might be worth you trying to see if you can get that working on the Hololens.

Also, with AudioGraph, did you try setting the QuantumSize to LowestLatency?

**Comment by generalui-glados** [comment]
I'll give the sample project a shot.

Yea, I tried setting QuantumSize to LowestLatency
Also tried setting it to ClosestToDesired and various desired sample per quantum sizes with no luck.  No matter what I do I always get 10ms of audio per quantum...even with the HD drivers.  The docs seem to be pretty clear about what to do, so either I'm missing something glaringly obvious or it doesn't work?  Right now latency is on average about 1000-1500ms per 10ms of Audio.  The thinking is if I can lower the size of the quantums that the latency would go down proportionally with it.  Can't prove that though because I can't change the size of them :)
