### ISSUE TITLE
Can't find NAudio.Midi

### ISSUE THREAD

**Issue by TheGoodBear** [naudio/NAudio#183]
Hello,

Must be a noob question but..
I am trying to play music notes in Windows Universal Application.

I found this code that should do it :
```
public static async Task PlayNoteAsync(
    MidiOut midiOut,
    int note,
    TimeSpan duration,
    int volume = 127,
    int channel = 0)
{
    midiOut.Send(MidiMessage.StartNote(note, volume, channel).RawData);
    await Task.Delay(duration).ConfigureAwait(false);
    midiOut.Send(MidiMessage.StopNote(note, volume, channel).RawData);
}
```

It requires using NAudio.Midi (I suppose MidiOut is part of it) but VS says :

> The type or namespace Midi does not exist in namespace NAudio

I have installed last NAudio package (1.8.0) from Nuget.

If you have any hint...

**Comment by markheath** [comment]
These old Win32 MIDI APIs are unfortunately not available in Windows Universal Applications. There is however, a MIDI API for Universal apps - check out [this sample here](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/MIDI)

**Comment by TheGoodBear** [comment]
Mark, thanks for that quick answer, I will look at that.
