### ISSUE TITLE
Conversion from G711 to wav produce loud ratcheting sound over good audio

### ISSUE THREAD

**Issue by Pigweed** [naudio/NAudio#185]
DarylJones posted this same issue on CodePlex and did not get a good answer.

I am having the exact same issue. It does not matter if I convert my file using nAudio, Sox, Switch, Audacity, whatever, it comes out with the exact same sound as described by Daryl a loud ratcheting sound on top of my audio. The only way the audio comes out clean is when I play it or convert it in Wireshark or the PCAP2Wav Xplico demo online. 

I really want to make nAudio work as it is a simple clean solution I can put into my app. 

Wireshark shows this: 
Payload type: ITU-T G.711 PCMU (0) 
Sample Rate (Hz): 8000 

I am using the following nAudio code from my app:
        Stream tmpMemStream = new FileStream(inFileName, FileMode.Open, FileAccess.Read);
        var waveFormat = WaveFormat.CreateMuLawFormat(8000, 1);
        var reader = new RawSourceWaveStream(tmpMemStream, waveFormat);
        using (WaveStream convertedStream = WaveFormatConversionStream.CreatePcmStream(reader))
        {
            WaveFileWriter.CreateWaveFile(outFileName, convertedStream);
        }
        tmpMemStream.Close();
Still I get that ratcheting noise over my phone call audio which is barely audible in the background. 

To assist I have posted the wav file here so you can give it a listen: 
https://services.streamwrite.com/images/output.wav 

Any help would be greatly appreciated! 
-Marco.

**Comment by markheath** [comment]
Probably the audio is wrapped in some kind of packet - you need to strip off any headers before decoding the audio - ulaw treats every single byte as a sample

**Comment by Pigweed** [comment]
MarkHeath that was my problem. Here are the details:

I take the network packet and pull the upd payload only and write that, without including the first 12 bytes (this was my issue), to a filestream file using WriteByte.  I save it as a .BIN file. Then run the nAudio conversion against that file. Those first 12 bytes were causing my ratcheting sound and Wireshark must have known to extract them. 

Here is how I create the .bin file:
        static public void WriteToFile(FileStream file, IpV4Datagram ip, UdpDatagram udp)
        {
            if(ip.Source.ToString() == voipSwitch)
            {
                for (int i = 12; i < udp.Payload.Length; i++ )
                {
                    file.WriteByte(udp.Payload[i]);
                }
            }
        } // WriteToFile

The nAudio code from my original post above works fine on that now.
