### ISSUE TITLE
Crash with corrupted audio

### ISSUE THREAD

**Issue by ssnseawolf** [naudio/NAudio#188]
When handling certain cases of corrupted audio, `WaveFormatConversionProvider`'s `conversionStream` is null, possibly due to strange things happening with Windows Multimedia. It seems `conversionStream`  isn't checked for null and throws an exception in Dispose(). This crash occurs in my own testing and in NAudioWpfDemo, 5-10 seconds after attempting to load the file.

I am not well-versed in .NET, but this condition is a problem because I'm unable to trap the exception in try-catch from external code.

File link (too big for GitHub) [here]( https://1drv.ms/u/s!AnP3QPE8xSweheMgHCJnk5a-xcfSdQ).

**Comment by markheath** [comment]
thanks for reporting, have checked in a fix
