### ISSUE TITLE
GetPosition blocks forever if you hit a breakpoint (and then continue)

### ISSUE THREAD

**Issue by sciencectn** [naudio/NAudio#19]
Hello,

So in my app, I call `WaveOut.GetPosition` repeatedly to find out how the song has progressed. But if I hit a breakpoint (or if some other error occurs), and I try to continue, it seems to block forever.

**Comment by markheath** [comment]
if you look at the stack trace, where is it blocked? Is it in the call to the underlying API, or is something hanging on to the lock?

**Comment by sciencectn** [comment]
Looks like it gets stuck at this line:
MmException.Try(WaveInterop.waveOutGetPosition(hWaveOut, out mmTime, Marshal.SizeOf(mmTime)), "waveOutGetPosition");

This also happens randomly from time to time without breaking but I haven't been able to reproduce that. 

Here's a screenshot of exactly where it is in WaveOut.cs:
![stuck](https://cloud.githubusercontent.com/assets/1373858/9394910/fdaf6fe8-473f-11e5-8cb7-e0b71e3de66e.PNG)

**Comment by markheath** [comment]
have a look at all the other threads. Are any of them inside a call to a waveOut function, or waiting on the waveOutLock? Also, what callback model are you using? Have you tried with WaveOutEvent?
