### ISSUE TITLE
System.ArgumentException: WAV file too large

### ISSUE THREAD

**Issue by fasiqueira9** [naudio/NAudio#191]
I'm trying to convert a file with almost 4gb and I received the erro below:

System.ArgumentException: WAV file too large
Parameter name: count
   at NAudio.Wave.WaveFileWriter.Write(Byte[] data, Int32 offset, Int32 count)
   at NAudio.Wave.WaveFileWriter.CreateWaveFile(String filename, IWaveProvider sourceProvider)

This problem occurs because the limit of int32 object?

This is my code:

void WaveToPCM(string pcmFileName, string waveFileName)
        {
            using (var reader = new WaveFileReader(waveFileName))
            using (var PCMStream = WaveFormatConversionStream.CreatePcmStream(reader))
                WaveFileWriter.CreateWaveFile(pcmFileName, PCMStream);
        }

**Comment by markheath** [comment]
Yes, a WAV file cannot be larger than 4GB. That has to include space for the RIFF headers and format chunk as well as the data, so you can't quite get there. You can make a BWF (RF64) file - check out my article here http://www.markheath.net/post/naudio-rf64-bwf
