### ISSUE TITLE
The Current Time exceeded the Total Time

### ISSUE THREAD

**Issue by womandroid** [naudio/NAudio#192]
HI, thanks for your great work.
I tried using NAudio Demo to play a mp3 file, and I found the Current Time is bigger than the Total Time
As you can see in the picture, the total time is 43 seconds and I am sure this is definitely right. But the current time is 1'03'', it has exceeded the total time and it's still going on.
![screenshot](https://cloud.githubusercontent.com/assets/11504254/26337162/6ca832b4-3fa9-11e7-9c43-5478a278731c.png)

I want to know how to fix this problem? Thanks.

**Comment by markheath** [comment]
NAudio's `Mp3FileReader` attempts to work out the duration of an MP3 file based on the MP3 frames within in, but it can sometimes get it wrong. You could try using `MediaFoundationReader` instead and see if that is better at deducing the file length.

**Comment by womandroid** [comment]
Yes, I used MediaFoundationReader instead of Mp3FileReader, and now it works fine.
Thank you very much.
