### ISSUE TITLE
Fast Forwarding and Rewind

### ISSUE THREAD

**Issue by Sivaram6466** [naudio/NAudio#193]
Hi All, 

Please help me how to do fastforwarding and rewind using naudio.

**Comment by markheath** [comment]
if you mean jumping to different positions in a file, then you can do that by simple setting the position. The NAudio demo application shows how this is done.

**Comment by Sivaram6466** [comment]
No markheath I need like playback with speed while fast forwarding not jumping.

**Comment by markheath** [comment]
OK, then look at the varispeed sample provider demo app here: https://github.com/naudio/varispeed-sample/

It is possible to play backwards in conjunction with this approach, but there isn't a built-in NAudio component to do that.

**Comment by Sivaram6466** [comment]
Hi markheath, 
how to run this project, is it mono? 
I m trying with vs2013 it shows lots of error

**Comment by markheath** [comment]
its a VS2015 project
