### ISSUE TITLE
Converting AMR to MP3

### ISSUE THREAD

**Issue by nefcanto** [naudio/NAudio#194]
Hi

I'm trying to convert AMR files being records in Android app to MP3 in the HTTP service behind the app.
I can't find a sample online and I can't figure it out myself.

Does NAudio support this feature. I can't find anything related to AMR in this repository.

Thank you so much

**Comment by markheath** [comment]
No, sorry there is no AMR codec included in NAudio. It can access other codecs installed on your machine, but Windows does not come with an AMR codec out of the box.
