### ISSUE TITLE
Problem generating sine wave - seems floa samples of +1 get written as -1

### ISSUE THREAD

**Issue by dirdiver** [naudio/NAudio#195]
When generating a 124-bit 192000hz sine wave at 440, there are audible clicks in the waveform. 
Looking at the values using Sonic Visualizer (http://www.sonicvisualiser.org/) you will see that the wave file has -1 where it should have +1. I got around it by encoding the data myself.

Here is an example console application that shows the problem. 

        using System.IO;

        using NAudio;

        static void Main(string[] args)
        {
            string name = "SineWave.wav";
            ushort bitsPerSample = 24;
            uint samplesPerSecond = 192000;
            ushort channelCount = 2;
            float startFreq = 440.0f; // concert-a
            uint numSamples = samplesPerSecond * 10;

            // https://blogs.msdn.microsoft.com/dawate/2009/06/24/intro-to-audio-programming-part-3-synthesizing-simple-wave-audio-using-c/
            float[] floatValues = new float[numSamples * channelCount];
            double t = (Math.PI * 2 * 440.0f) / samplesPerSecond; 

            for (uint i = 0; i < numSamples; i++)
            {
                // Fill with a simple sine wave at max amplitude
                for (uint channel = 0; channel < channelCount; channel++)
                {
                    double doubleValue = Math.Sin(t*i);
                    floatValues[i * channelCount + channel] = (float)doubleValue;
                }
            }
            NAudio.Wave.WaveFormat m_nAudioWaveFormat = new NAudio.Wave.WaveFormat((int)samplesPerSecond, bitsPerSample, channelCount);
            FileStream fileStream = new FileStream(name, FileMode.Create);
            NAudio.Wave.WaveFileWriter writer = new NAudio.Wave.WaveFileWriter(fileStream, m_nAudioWaveFormat);
            writer.WriteSamples(floatValues, 0, floatValues.GetLength(0));
            writer.Close();
            fileStream.Close();
        }

**Comment by dirdiver** [comment]
I added the following after fileStream.Close
            fileStream = new FileStream(name, FileMode.Open, FileAccess.Read);
            NAudio.Wave.WaveFileReader reader = new NAudio.Wave.WaveFileReader(fileStream);
            float[] samples = new float[reader.SampleCount * reader.WaveFormat.Channels];
            for (int ii = 0; ii < reader.SampleCount; ii++)
            {
                float[] sampleFrame = reader.ReadNextSampleFrame();
                for (int channel = 0; channel < reader.WaveFormat.Channels; channel++)
                {
                    samples[ii * reader.WaveFormat.Channels + channel] = sampleFrame[channel];
                }
            }
            fileStream.Close();

looking at 7200 in the values written vs read back in:
		floatValues[7200]	1.0	
		floatValues[7201]	1.0	
		samples[7200]	-1.0	
		samples[7201]	-1.0

**Comment by markheath** [comment]
I'd recommend you look at the `SignalGenerator` class in NAudio for an easier way to generate sine waves

**Comment by Skupje** [comment]
A sine wave is not supposed to reach + or -1, It's maximum value is fsin(1-(1/2n-1))
