### ISSUE TITLE
How could I achieve hot-plugging using NAudio during playing or recording?

### ISSUE THREAD

**Issue by heku** [naudio/NAudio#197]
Hi,

I know this question might out of the scope of NAudio, but I still have no idea about this after some research on the internet.

Is there already some APIs in NAudio that support this scenario? or any of you have any experience/idea on this?

Any help will be appreciated, thank you in advance.

**Comment by markheath** [comment]
With WaveOut I believe you can specify -1 (mapper) as the device number and get this behaviour. Haven't tried it out myself
