### ISSUE TITLE
MediaFoundationHeader (Windows 10 UWP) zero bytes at beginning of Read buffer

### ISSUE THREAD

**Issue by prajwal83** [naudio/NAudio#198]
Hello

I am trying to use NAudio.Wave.MediaFoundationReader (version 1.8) in a windows UWP application

To read a MP3 audio file (created using UWP AudioGraph, with bitrate = 256000, sampleRate = 16000 and channel = 1) to get PCM data.
Everytime (including the very first time) I seek() to some position on this MediaFoundationReader instance and try read some bytes (which should return PCM data), the beginning of the buffer contains an arbitrary number of bytes with value "0" (sometimes it's the first 625 bytes or first ~1500 bytes of the buffer read)

Can you please help explain why bytes with value "0" appear at the beginning of the buffer read using MediaFoundationReader.Read() ?

Thanks
Prajwal

**Comment by markheath** [comment]
hi, not sure exactly why this is happening  - MediaFoundationReader is a wrapper around lower-level Windows Media Foundation APIs, so we have relatively little control over what happens. However, if you're using UWP, why not just use [AudioFileInputNode](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Audio.AudioFileInputNode) instead?

**Comment by prajwal83** [comment]
Hi Mark, thanks for responding. Appreciate that there is little control as it's lower-level windows api. 
What I am trying to do is show/render a wav form graph (like a simple moving bar graph of sample values) while playing an MP3 audio file. So, I thought I will use MediaFoundationReader to seek to playback position and read some (fixed number of) bytes of PCM data to display a graph of sample values continuously through-out the playback duration. Is there any other alternative to achieve the same in NAudio ?

AudioGraph is not usable (I suppose) because I can't seek to random positions in audio file to extract sample values as the audio plays on mediaplayer.. (as user can fwd/rewind playback position manually as well)
