### ISSUE TITLE
convert wav byte array to mp3 byte array

### ISSUE THREAD

**Issue by Fivezero05** [naudio/NAudio#201]
I am trying to capture sound on my computer and stream it to an arduino. WAV is too big for the memory, so it would be great if I could send MP3 over UDP.

However, I don't find a way to convert an array of bytes coded in WAV to MP3 WITHOUT saving it on the disk.

alternatively : Could it be possible to set up a radio station server with naudio? The connection stuff I can handle, but the conversion of the captured data from WaveInEventArgs is another problem.

**Comment by markheath** [comment]
I'm afraid I have no easy way to encode MP3 on the fly with NAudio at the moment. There is a project wrapping LAME that might help - https://github.com/Corey-M/NAudio.Lame

**Comment by TommasoRuggeri** [comment]
it is possible now?
