### ISSUE TITLE
Recording in random position from an existing wav file

### ISSUE THREAD

**Issue by christophdebaene** [naudio/NAudio#204]
I am currently building a voice recorder application. 
Often they want to go back in the recording and record from that position again.

I am not sure if this is supported through the `WaveFileWriter`?
How can this be accomplished?

Thank you

**Comment by markheath** [comment]
This is not a feature of NAudio, but I have done something similar with my own custom version of WaveFileWriter. So long as you are careful about block align, its not too hard to write over the top of the data chunk of an existing file
