### ISSUE TITLE
Can I use NAudio to play music written in a music score?

### ISSUE THREAD

**Issue by ygc369** [naudio/NAudio#206]
If I only have a music score and do not have any music files, can I write a program to play it using NAudio?
I can translate the music score to strings manually, according to specific rules.
QBasic has this feature, using "play" command.
Relative issue: https://github.com/dotnet/csharplang/issues/346

**Comment by markheath** [comment]
no, sorry NAudio does not include a software synthesizer/sampler or sequencer, both of which you'd need to implement this

**Comment by jnm2** [comment]
Hmm... I've done it, a long time ago, with both MIDI and waveform generation using NAudio. It wasn't right out of the box, as in play a QB music string, but its totally doable if you have a mind to implement it.
