### ISSUE TITLE
New release and .Net Standard

### ISSUE THREAD

**Issue by philkild** [naudio/NAudio#207]
Is it possible to get a new NuGet package released with the recent bug fixes and also add support for .Net Standard?

**Comment by devomage** [comment]
also would be great to remove references to system.windows.forms

**Comment by markheath** [comment]
Adding support for .NET standard is a fairly major undertaking, and provides limited value since the majority of NAudio only works on Windows. It is something I agree should be done in the future, but it's not actively in development at the moment.

**Comment by JunielKatarn** [comment]
Adding this support could help with eventual UNIX ports.
Meaning, they are more likely to happen if the code base is already .NET Standard.

I'd be happy to contribute some time for such refactoring effort, but may need some pointers regarding building.

**Comment by markheath** [comment]
OK, thanks. Have done a couple of experimental ports to .NET standard, and was holding off trying again until .NET standard 2.0 has wider support, which might make life easier

**Comment by philkild** [comment]
If it could be deployed with .Net 4.6.1 or higher included then it could be consumed by .Net Standard apps on Windows which would be a good start.

**Comment by markheath** [comment]
Yes although NAudio is used in a lot of enterprise software that is stuck on very old versions of .NET and I don't want to break support for them. It's still on .NET 3.5 at the moment.

**Comment by philkild** [comment]
Can the NuGet package not target multiple versions though?

**Comment by markheath** [comment]
Sure, it already has several builds. Just adds a lot of extra testing overhead to release a new version, especially if the code for the different versions starts to diverge.
