### ISSUE TITLE
"Out of Index" error with USB devices when try get volume peak.

### ISSUE THREAD

**Issue by andernunes** [naudio/NAudio#208]
I'm tryin get the peaks of volume from USB devices with WASAPI but i het a overflow error:
"Exception thrown: 'System.IndexOutOfRangeException' in NAudio.dll"

With others devices no problem. Only with USB like UB222 and Wireless Headphones.

![err](https://user-images.githubusercontent.com/24887313/27935463-3dfa5440-6279-11e7-9d32-a36989a44176.png)

I need the values to test a custom VU Meter with customized handles.

(Sorry my bad english)

**Comment by markheath** [comment]
is index >= Count? This method should probably throw an ArgumentOutOfRangeException before getting the peak values

**Comment by andernunes** [comment]
Hi markheath!
No, its stereo.
I try increase and decrease the index value, write a count test to jump the error but i don't had sucess.
The error happen only when i use a USB device, like UC202 (Behringer) or a Headphone Wireless with dongle USB.
If i use a pci or pci-x soundcard, works fine.

**Comment by markheath** [comment]
hmm, may just be a quirk of the drivers for those devices.

**Comment by andernunes** [comment]
Hi markeath!
Sorry for this (don't report anymore about the issue). 
Thank you. (Here, in Brazil, we say: Antes tarde do que nunca. LOL)

**Comment by andernunes** [comment]
**SOLVED**
The error happens because the index of listed devices for Peaks is different from listed devices on WaveDevices.
I have created a function that associate the index of soundcard in WASAPI

```
Private Function getwasapi_dev(ByVal n As Integer, tipo As DataFlow) As Integer
        Try
            Dim caps As String = Nothing
            Dim entradas_d(32) As String
            If tipo = DataFlow.Capture Then
                caps = WaveIn.GetCapabilities(n).ProductName
            ElseIf tipo = DataFlow.Render Then
                caps = WaveOut.GetCapabilities(n).ProductName
            End If
            Dim c As Integer = 0
            Dim enumerator As MMDeviceEnumerator = New MMDeviceEnumerator()
            For Each device As MMDevice In enumerator.EnumerateAudioEndPoints(tipo, DeviceState.Active)
                If caps = Microsoft.VisualBasic.Left(device.FriendlyName, 31) Then
                    Debug.Print(n & ": " & caps & " - " & c & ": " & Microsoft.VisualBasic.Left(device.FriendlyName, 31))
                    Return c
                End If
                c += 1
            Next
        Catch ex As Exception
        End Try
        Return -1
End Function
```

Again: Thank you so much for your knowledgment.
