### ISSUE TITLE
Remove references to System.Windows.Forms

### ISSUE THREAD

**Issue by devomage** [naudio/NAudio#209]
Remove references to System.Windows.Forms

For applications that are not using System.Windows.Forms - this is a problem.

**Comment by markheath** [comment]
why is it a problem? NAudio was created back in 2002 and is primarily focused on desktop Windows applications - whether you're doing WinForms or WPF, the windows messaging callbacks of WaveIn/WaveOut use that assembly. But if you're not doing desktop apps, just don't use those versions of WaveIn/WaveOut.

**Comment by devomage** [comment]
It will not compile within Unity3D because of these references.

**Comment by WamWooWam** [comment]
It's also the only thing code wise preventing basic .Net Standard support.

**Comment by jwosty** [comment]
I believe this is can be closed now, as only NAudio.WinForms references Windows Forms, and NAudio.Core is already .Net Standard.
