### ISSUE TITLE
Codec 2 support

### ISSUE THREAD

**Issue by KvanTTT** [naudio/NAudio#21]
I have an .NET wrapper for ultra low bitrate (1200-3200 bit/sec) voice codec Codec2 https://github.com/freedv/codec2

It it should be included in NAudio library?

**Comment by markheath** [comment]
hi, LGPL code cannot be included in NAudio. Probably the best thing would be to make an NAudio wrapper project for it, like we have done for various other codecs. It could be called NAudio.Codec2
