### ISSUE TITLE
WaveFormat cannot be set for WASAPI Loopback Capture

### ISSUE THREAD

**Issue by achrafchikoun** [naudio/NAudio#213]
i am trying to stream sound card ouput from server to client, so i need to encode the array bytes in the server and decode in client.

> waveIn = new WasapiLoopbackCapture();
waveIn.WaveFormat = selectedCodec.RecordFormat;
waveIn.DataAvailable += soundStream_DataAvailable;
waveIn.StartRecording();

but 

> waveIn.WaveFormat = selectedCodec.RecordFormat; 

throw exception

> WaveFormat cannot be set for WASAPI Loopback Capture

i did the same thing to stream the microphone between two users using client/server architecture and it work perfectly.

**Comment by markheath** [comment]
yes, this is how wasapi loopback capture works. You have to capture at the wave format that the system audio is running - usually IEEE float, stereo at 44.1 or 48kHz.
If you want a different format you must convert it manually as a separate step

**Comment by achrafchikoun** [comment]
Thank you for the replay, can you give me please a link on how convert it manually as a separate step

**Comment by achrafchikoun** [comment]
I have tried this code to convert bytes from 32 to 16 bits and to resample, but all I get every time is just blank audio.

**I convert the array bytes from 36 bits to 16 bits like this :**

> byte[] newArray16Bit = new byte[e.BytesRecorded / 2];
>             short two;
>             float value;
>             for (int i = 0, j = 0; i < e.BytesRecorded; i += 4, j += 2)
>             {
>                 value = (BitConverter.ToSingle(e.Buffer, i));
>                 two = (short)(value * short.MaxValue);
>                 newArray16Bit[j] = (byte)(two & 0xFF);
>                 newArray16Bit[j + 1] = (byte)((two >> 8) & 0xFF);
>             }

**and then i resample like this :** 

> Buffer.BlockCopy(newArray16Bit, 0, resampleStream.SourceBuffer, 0, newArray16Bit.Length);
>             int sourceBytesConverted = 0;
>             var convertedBytes = resampleStream.Convert(newArray16Bit.Length, out sourceBytesConverted);
>             if (sourceBytesConverted != (e.BytesRecorded / 2))
>             {
>                 Console.WriteLine("We didn't convert everything {0} bytes in, {1} bytes converted", sourceBytesConverted, e.BytesRecorded / 2);
>             }
>             var converted = new byte[convertedBytes];
>             Buffer.BlockCopy(resampleStream.DestBuffer, 0, converted, 0, convertedBytes);

**and finally to save :**

> waveWriter.Write(converted, 0, convertedBytes);
>             waveWriter.Flush();

**Comment by markheath** [comment]
the best way to troubleshoot issues like this is to save your audio to WAV file at intermediate problems. Try saving after the conversion to 16 bits and checking that is OK. If it's OK then you can focus more on the resampling which is more likely to be where the issue is.
