### ISSUE TITLE
MMDevice can only be used on the thread they were created on.

### ISSUE THREAD

**Issue by skinnyMan** [naudio/NAudio#214]
There seems to be an issue with using MMDevice in a multithreaded scenario.

main thread:
```cs
var device = (MMDevice) comboWasapiDevices.SelectedItem;
```
background processing thread:
```cs
IWaveIn newWaveIn;

Task task = new Task(() => {
    newWaveIn = new WasapiCapture(device) // <----------------- THROWS EXCEPTION
});
task.start();
```

Exception Thrown Message:
An exception of type 'System.InvalidCastException' occurred in NAudio.dll but was not handled in user code

{"Unable to cast COM object of type 'System.__ComObject' to interface type 'NAudio.CoreAudioApi.Interfaces.IMMDevice'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{D666063F-1587-4E43-81F1-B948E807363F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE))."}

**Comment by markheath** [comment]
`WasapiCapture` already creates a background thread to doing the capturing on when you call `StartRecording`. So no reason to do this. I expect the exception you're seeing is due to the COM apartment threading model of the thread you're running on.

**Comment by skinnyMan** [comment]
The exmample code I placed above just helps recreate the exception.

I need to record multiple sessions in a row without blocking the main UI thread, so I have a background thread that needs to keep running record sessions non stop until the user stops. The background thread can't create another waveIn instance since MMDevice can't be touched by other threads.

IWaveIn instances don't seem to like to be reused, which is why the background thread is trying to reinstantiate the instance.

```cs
private IWaveIn CreateWaveInDevice()
{
    IWaveIn newWaveIn;
    var tempDevice = (MMDevice)device;
    if (!WasapiLoopBack)
    {
        newWaveIn = new WasapiCapture(this.device);
    }
    else
    {
        newWaveIn = new WasapiLoopbackCapture();
    }

    newWaveIn.DataAvailable += OnDataAvailable;
    newWaveIn.RecordingStopped += OnRecordingStopped;
    return newWaveIn;
}
```

What am I missing?

**Comment by krugg** [comment]
IMO every object created by a thread is owned by it. So if you really want to use these devices within a thread (here Task) you have to create it within.

The following code do select the device by index given to the task:

`                WasapiCapture device = null;
                Task task = Task.Factory.StartNew((object devIndex) =>
                {
                    var index = (int)devIndex;

                    var deviceEnum = new MMDeviceEnumerator();
                    var threadDeviceList = deviceEnum.EnumerateAudioEndPoints(DataFlow.Capture, DeviceState.Active).ToList();
                    var threadDevice = threadDeviceList[index];

                    device = new WasapiCapture(threadDevice); // <----------------- SHOULD NOT THROW EXCEPTION
                }, this.DevColIn.IndexOf(this.SelectedInputDevice));
                //task.Start();
`

Hope this helps.

**Comment by JohnsonGao** [comment]
I found the same appearances that seems like NAudio lib codes works only under Main UI Thread ?? 
for example, MMDeviceEnumerator cannot work rightly under non-ui thread and throw out the error System.InvalidCastException.

**Comment by markheath** [comment]
CSCore does IL rewriting to use the calli instruction. That's something I've never had time to implement on NAudio but would be a great improvement. It's now possible with compiler intrinsics to emit that IL instruction directly so that's an alternative approach.

**Comment by JohnsonGao** [comment]
Thank you Mark, I have to look forward to your next great improvements or compiler intrinsics . :+1: 
By the way , another question is I did not find the normal 10band Equalizer codes in NAudio right ? Or if there exists please show me the place. Thank you very much.

**Comment by markheath** [comment]
I think the code for that is in the WPF demo app. It's not made it into the main NAudio library, but you can easily copy the code and adapt it to the number of bands you want, and frequencies you would like
