### ISSUE TITLE
Asio capture seems not to work anymore

### ISSUE THREAD

**Issue by krugg** [naudio/NAudio#215]
I've using NAudio 1.7.3 for several years without any problems on Asio capturing.

After updating to 1.8.1 via Nuget no sound (only some minimal noise) gets captured. Then I've gone back to 1.8.0 and capturing works again.

After testing Asio capturing demo from 1.8.1 the same problem occurs there. I haven't found any difference in source code that could explain me the cause of this behaviour.

For Asio capture and playback I am using ASIO4ALL v2.

**Comment by markheath** [comment]
That's very strange. I can run ASIO capture on my PC with no issues. How are you testing? Have you cloned the NAudio repo and tried running the demo directly from latest code?

**Comment by krugg** [comment]
After having some time again I have updated my projects from .net 4.5.2 
to 4.6.1* and updated again to NAudio 1.8.1 (nuget). I think the problem 
with ASIO capturing is associated with .net versions < 4.6 in some way 
as it is gone away now (even using an old Terratec EWX24/96). But making 
it some worse again I can't start any of my applications in Visual 
Studio Debugger at the first time after updating as I get an Heap 
Corruption Exception (0xc0000374) when creating AsioOut by name:

using (AsioOut asio = new AsioOut(name))  <= Exception 0xc0000374 here
                 {  ....   }

If I start the application directly the exception is not thrown anymore, 
even in debugger. Very strange but OK for now as the exception is gone 
while debugging and in Release mode no exceptions thrown at all at this 
critical points.

*: Wanted to use 4.6.1 for trying the new GC feature 
"|GCSettings.LatencyMode"|

Thanks for your time and help. IMO you can close this case.



Am 26.07.2017 um 20:48 schrieb Mark Heath:
