### ISSUE TITLE
MP3 Timespan updated wrongly

### ISSUE THREAD

**Issue by Davaxyr** [naudio/NAudio#217]
On the newest version, 1.8.1, the MP3 current time timespan is updated wrongly. That means, the timespan goes 2x faster than the actual time, and it updates in 2-second ticks. This happens only to the current time MP3 timespan.

**Comment by tjscience** [comment]
I have the same issue. It works fine if I use MediaFoundationReader, but I need an ISampleProvider.

**Comment by markheath** [comment]
sorry, I've just pushed 1.8.2 which should include a fix for this issue. Please let me know if you have any further problems
