### ISSUE TITLE
'System.OutOfMemoryException' in mscorlib.dll

### ISSUE THREAD

**Issue by psideas** [naudio/NAudio#218]
I am using NAudio in my VB.NET Windows Forms application to record long-form programs (30 minutes to 4 hours) and I am seeing an error after about 40 minutes. The error reads:

> Exception thrown: 'System.OutOfMemoryException' in mscorlib.dll
> An unhandled exception of type 'System.OutOfMemoryException' occurred in mscorlib.dll

The code I am using is:
`Public Sub StartRecording()
        newWave = New NAudio.Wave.WaveIn
        memstream = New MemoryStream

        If My.Settings.recordMode = 0 Then
            My.Settings.recordMode = 1
        End If

        Select Case My.Settings.SampleRate
            Case 0
                newWave.WaveFormat = New WaveFormat(44100, My.Settings.recordMode)
            Case 1
                newWave.WaveFormat = New WaveFormat(48000, My.Settings.recordMode)
            Case Else
                newWave.WaveFormat = New WaveFormat(44100, My.Settings.recordMode)
        End Select
        newWave.DeviceNumber = My.Settings.audio_device_index

        waveFile = New WaveFileWriter(memstream, newWave.WaveFormat)

        AddHandler newWave.DataAvailable, AddressOf RecordedDataAvailable
        AddHandler newWave.RecordingStopped, AddressOf RecordingStopped

        newWave.StartRecording()
    End Sub

    Private Sub RecordedDataAvailable(sender As Object, e As NAudio.Wave.WaveInEventArgs)
        If waveFile IsNot Nothing Then
            waveFile.Write(e.Buffer, 0, e.BytesRecorded)
            waveFile.Flush()
        End If
        'error here: Exception thrown: 'System.OutOfMemoryException' in mscorlib.dll
        'An unhandled exception of type 'System.OutOfMemoryException' occurred in mscorlib.dll
    End Sub`

Any help would be greatly appreciated.

**Comment by markheath** [comment]
You're just writing audio into a memory stream which will grow and grow until you run out of memory. To avoid this, write to a file on disk instead.

**Comment by psideas** [comment]
Thank you, Mark. It is working well now.
