### ISSUE TITLE
MediaFoundationReader reports wrong Length and Timespans

### ISSUE THREAD

**Issue by TakisGenn** [naudio/NAudio#219]
MediaFoundationReader.Length = AudioFileReader.Length *2

Also, there are cases (different tracks) where:
MediaFoundationReader.TotalTime = AudioFileReader.TotalTime *2
(same applies to .CurrentTime)

I do not know how to handle this in my application as the only reader i use is MFR for playing tracks and relaying URLs and those timespans are used for driving a fader class for starting and terminating tracks (mixing) comparing them with stored values in a db. Not using a WaveOutDevice.PlaybackStopped event at all.

My first idea was to initialize an AudioFileReader, get the correct length and timespans and start dividing but there are more than one cases and i will loose control.
Any more ideas?

Regards
Takis

**Comment by markheath** [comment]
sorry, have just pushed v1.8.2 which includes a fix for this issue.

**Comment by TakisGenn** [comment]
Wow!! Thanks!! :100:
