### ISSUE TITLE
Playbackstate when using mixersampleprovider

### ISSUE THREAD

**Issue by FonyRockfeel** [naudio/NAudio#22]
I use NAudio framework in my project. I have a MixerSampleProvider to play several Cashed sounds. I noticed when using mixersampleprovider in outputdevice, OutputDevice.PlaybackState always has Playing state. How can I trace the end of soundfile?

**Comment by markheath** [comment]
I would like to improve the mixer at some point to make it easier to detect when individual sounds have finished, as well as when everything has finished. However, if you set ReadFully to false, which should be the default then playback should stop when you have finished playing the final input.

**Comment by markheath** [comment]
there are now events when individual inputs have ended
