### ISSUE TITLE
Can't use any codepage except Unicode to read TextEvent from MidiFile

### ISSUE THREAD

**Issue by alexlarex** [naudio/NAudio#221]
`MidiFile `reads events using binary reader, all text events are decoded with `NAudio.Utils.ByteEncoding.Instance` encoding which uses `(char)byte` to decode bytes into char, but casting to char treats byte as a Unicode character which it may not be. As an example, byte 0xC3 in cp1251 is 'Г' but in Unicode it is '&Atilde;'

**Comment by alexlarex** [comment]
I made a quick patch addressing this issue #222

**Comment by markheath** [comment]
thanks, merged in
