### ISSUE TITLE
MediaFoundationReader: a couple HE-AAC & HE-AACv2 cases

### ISSUE THREAD

**Issue by tfwio** [naudio/NAudio#223]
Greetz!

HE-AAC/HE-AACv2 cause an exception.  
the (quick) fix below also causes an exception if we have an aac_lc mono file ;( in which case i suppose a try/catch can revert on `SetCurrentMediaType` if one were inclined.

[edit: wow i sure edited the h out of this -- no more edits;]

see:
- http://forum.doom9.org/archive/index.php/t-74510.html
- https://en.wikipedia.org/wiki/High-Efficiency_Advanced_Audio_Coding

after calling `var currentMediaType = GetCurrentMediaType(reader);`  
if `subType == AAC` && `numchannels == 1`, doubling numchannels and sample-rate appears to get the format(s) working.

I'd tested various HE-AAC/AACv2 files at different channel and samplerate settings am aware of and it seems to do the trick.

```cs
    /// <summary>
    /// Creates the reader (overridable by )
    /// </summary>
    protected virtual IMFSourceReader CreateReader(MediaFoundationReaderSettings settings)
    {
      IMFSourceReader reader;
      MediaFoundationInterop.MFCreateSourceReaderFromURL(file, null, out reader);
      reader.SetStreamSelection(MediaFoundationInterop.MF_SOURCE_READER_ALL_STREAMS, false);
      reader.SetStreamSelection(MediaFoundationInterop.MF_SOURCE_READER_FIRST_AUDIO_STREAM, true);

      // Create a partial media type indicating that we want uncompressed PCM audio

      var partialMediaType = new MediaType();
      partialMediaType.MajorType = MediaTypes.MFMediaType_Audio;
      partialMediaType.SubType = settings.RequestFloatOutput ? AudioSubtypes.MFAudioFormat_Float : AudioSubtypes.MFAudioFormat_PCM;

      var currentMediaType = GetCurrentMediaType(reader);

      // HE-AAC (and v2) seems to halve the samplerate
      if (currentMediaType.SubType==AudioSubtypes.MFAudioFormat_AAC && currentMediaType.ChannelCount==1)
      {
        currentMediaType.SampleRate *= 2;
        currentMediaType.ChannelCount *= 2;
      }
      // mono, low sample rate files can go wrong on Windows 10 unless we specify here
      partialMediaType.ChannelCount = currentMediaType.ChannelCount;
      partialMediaType.SampleRate = currentMediaType.SampleRate;
      

      // set the media type
      // can return MF_E_INVALIDMEDIATYPE if not supported
      reader.SetCurrentMediaType(MediaFoundationInterop.MF_SOURCE_READER_FIRST_AUDIO_STREAM, IntPtr.Zero, partialMediaType.MediaFoundationObject);

      Marshal.ReleaseComObject(currentMediaType.MediaFoundationObject);
      return reader;
    }
```

Many thanks :)

**Comment by markheath** [comment]
thanks for reporting. feel free to issue a PR with these changes.

**Comment by Ahmed-Abdelhameed** [comment]
I encountered a similar issue #231. Just tested your fix, and it worked with MP4 files with AAC audio format, _but didn't work with MP2 though_. Anyway, this is good enough for me at least for now. Kindly issue a PR so we can have this committed ASAP. Thank you!
