### ISSUE TITLE
Converting to mono creates an empty sound

### ISSUE THREAD

**Issue by uluhonolulu** [naudio/NAudio#225]
Hi,

I'm trying to convert a stereo sound to mono using the following code:

```
			using (var waveFileReader = new WaveFileReader(sourceFileName))
			{
				var toMono = new StereoToMonoProvider16(waveFileReader);
				WaveFileWriter.CreateWaveFile(destFileName, toMono);
			}
```

The file is created without problems, but when I play it, it doesn't produce any sound.

How do I convert a wav file to mono? I'm avoiding any converter that uses built-in codecs since I'll be using it on an Azure Website.

The file is attached...
[How to Perfect the Elevator Pitch_cut_part1.naudio.zip](https://github.com/naudio/NAudio/files/1220493/How.to.Perfect.the.Elevator.Pitch_cut_part1.naudio.zip)

**Comment by markheath** [comment]
I've answered on StackOverflow, but the short answer is that on your `StereoToMonoProvider16` you need to provide values for `LeftVolume` and `RightVolume` to indicate how much of each input channel you want mixed into the output.
