### ISSUE TITLE
How to read MP3 properties with NAudio

### ISSUE THREAD

**Issue by SamuelCox** [naudio/NAudio#226]
Hi, sorry for the question as an issue, but the docs aren't helpful and neither was google.
http://naudio.codeplex.com/wikipage?title=Create%20an%20ID3v2%20Tag shows how to create an ID3v2 tag, which is all fine, but given an Mp3 file, how do I get the artist or title or etc. Do I really have to do ID3v2.Read and decode the raw bytes myself?

I'm new to NAudio so I might be missing something simple, essentially what I want to do is 
   ``` 
   Mp3FileReader reader = new Mp3FileReader();
    reader.Title;
    reader.Artist
```
or

    Id3v2Tag.ReadTag(stream).Title;

**Comment by markheath** [comment]
NAudio's support for ID3 tags is very basic. There are other NuGet packages (e.g. [TagLibSharp](https://www.nuget.org/packages/taglib/) that can do a better job

**Comment by SamuelCox** [comment]
Yeah, I ended up going with TagLibSharp, I was hoping to avoid more third party dependencies though. Thanks for the response.
