### ISSUE TITLE
Add a second parameter to AudioFileReader to ignore "advertised" length of WAV file

### ISSUE THREAD

**Issue by axtens** [naudio/NAudio#227]
As per my [StackOverflow posting](https://stackoverflow.com/questions/45769835/naudio-wave-to-mp3-conversion-issue) , I have a situation where the WAV has a corrupted header and so does not convert to MP3. However, VLC will play the WAV, and sox, if told to --ignore-length, will give me a WAV file that converts flawlessly to MP3.

Therefore, is it possible to add to AudioFileReader an option to do its equivalent of sox's --ignore-length.

**Comment by markheath** [comment]
`AudioFileReader` just uses `WaveFileReader` internally to read the WAV file. For your specific case where you're trying to deal with a very specific corruption in the header, I'd just copy the code and make a custom `WaveFileReader` for your specific use case. We can then decide if its worth bringing into the core library.

**Comment by axtens** [comment]
I did fork the repository in the hopes that I'd be able to grok the workings. I was a little overconfident in that regard. In the meantime the production code is shelling to dos to run sox which is ugly but functional.
