### ISSUE TITLE
NSpeex Decoding issue

### ISSUE THREAD

**Issue by achrafchikoun** [naudio/NAudio#228]
I'm capturing the micro and sound card audio from a server and I send the data to the client. When I test in local everything is good but when i try to test through a network it doesn't work.
the bug come from the client side when i try to decode.
it crushed here (Decode function in SpeexChatCodec.cs. third line in the function) :
`public byte[] Decode(byte[] data, int offset, int length)
        {
            var outputBufferTemp = new byte[length * 320];
            var wb = new WaveBuffer(outputBufferTemp);
            int samplesDecoded = decoder.Decode(data, offset, length, wb.ShortBuffer, 0, false);
            int bytesDecoded = samplesDecoded * 2;
            var decoded = new byte[bytesDecoded];
            Array.Copy(outputBufferTemp, 0, decoded, 0, bytesDecoded);
            Debug.WriteLine(String.Format("NSpeex: In {0} bytes, decoded {1} bytes [dec frame size = {2}]", length, bytesDecoded, decoder.FrameSize));
            return decoded;
        }`

**Comment by markheath** [comment]
It may be that the speex codec isn't installed on the target machine. It's quite an old legacy codec that was included in Win 7, but may not be present on newer versions of Windows. Without seeing the actual exception details I can't offer more details than that I'm afraid
