### ISSUE TITLE
WaveMixerStream32 in Universal (UWP)?

### ISSUE THREAD

**Issue by JunielKatarn** [naudio/NAudio#232]
WaveMixerStream32 is not present in the NAudio Universal assembly.
Is there a way to emulate its functionality with the available types for UWP?

**Comment by markheath** [comment]
I think it was just that I didn't want to turn on the "allow unsafe code" flag for the Universal project and `WaveMixerStream32` requires that.  You could just copy the code verbatim into your own project - no need for it to be part of NAudio. `WaveMixerStream32` is really a legacy class now that I don't intend to support going forward - I'd recommend using `MixingSampleProvider` where possible instead.

**Comment by RomualdDub** [comment]
No

**Comment by JunielKatarn** [comment]
Noted. Thanks.
