### ISSUE TITLE
NullReferenceException  on  public AsioOut(int driverIndex)

### ISSUE THREAD

**Issue by lashajala** [naudio/NAudio#234]
After updating from 1.8.0 to version 1.8.2 there is issue when creating AsioOut instance with driverIndex , occures NullReferenceException at calling InitFromName(string driverName) at line 134:  AsioDriver basicDriver = AsioDriver.GetAsioDriverByName(driverName);  driveName is empty string because it not initialized before

**Comment by markheath** [comment]
good spot, thanks for reporting. have checked in a fix
