### ISSUE TITLE
[UWP] Real time audio processing in UWP?

### ISSUE THREAD

**Issue by niels9001** [naudio/NAudio#237]
Hi guys,

I'm trying to do the following: I'd like to create a UWP app that would use the device microphone to record audio and do real time processing. I want to make a visualizer that would use colors to light up etc. Is this possible with this API and can you give me any pointers on how to do this?

Niels

**Comment by markheath** [comment]
NAudio does have some basic UWP support, but you may find the new AudioGraph API is easier to work with - it allows you to capture sample level audio which you can use to drive your visualizations. I do have a [pluralsight course on AudioGraph](https://www.pluralsight.com/courses/uwp-audio-fundamentals?utm_medium=affiliate&utm_source=1036405) if you're interested in diving deeper
