### ISSUE TITLE
How to convert 32bit PCM to 16bit PCM

### ISSUE THREAD

**Issue by LGinC** [naudio/NAudio#238]
Can I use NAduio to convert ?

**Comment by markheath** [comment]
There are several helper classes in NAudio for this: `SampleToWaveProvider16`, `WaveFloatToWaveProvider16`, `Wave32To16Stream`

**Comment by LGinC** [comment]
And support Noise Suppression？

**Comment by markheath** [comment]
I'm afraid there isn't a built-in noise suppression algorithm in NAudio

**Comment by LGinC** [comment]
what's the lib for noise suppression in C#  you recommend?

**Comment by markheath** [comment]
I'm not aware of one I'm afraid.
