### ISSUE TITLE
Custom Propery Keys Unknown Property

### ISSUE THREAD

**Issue by Coobers** [naudio/NAudio#241]
When I took Properties out of Realtek's MMDevice, i have number of PropertyStoreProperty that's PropertyKey is not in  NAudio/NAudio/CoreAudioApi/PropertyKeys.cs

For example PropertyKey.propertyId = 17 with formatId = 3ba0cd54-830f-4551-a6eb-f3eab68e3700.
It looks it's Realtek driver property for detecting headphones in joined device (State of device is always active regardless if laptop speaker is used or headphones are used).

Can you confirm this property is custom (non standard) or is there any list of properties that can be used here?

**Comment by markheath** [comment]
Unfortunately, there is no official list of these properties. When I come across one I've not seen before I just google it and see if I can find a name for it. So it's just trial and error and PropertyKeys is just the list of ones I've discovered so far.

**Comment by mirh** [comment]
If it can help, on my laptop `{3BA0CD54-830F-4551-A6EB-F3EAB68E3700},6` seems to be whether the jack socket is "empty" or not.
