### ISSUE TITLE
Is there a NAudio Discussions replacement planned?

### ISSUE THREAD

**Issue by SmokinLeather** [naudio/NAudio#242]
The CodePlex Discussions (user forum) appears to be frozen now (unless I'm missing something)
The Discussions threads are a great resource for the NAudio user community. And I don't see a similar resource over at here at GitHub. Any plans for a new forum now that CodePlex is sunsetting?

**Comment by markheath** [comment]
The main places to discuss NAudio are 

 - here on GitHub in the issues
 - [chat on Gitter](https://gitter.im/naudio/NAudio) (not particularly active)
 - ask questions on [StackOverflow tagged with NAudio](https://stackoverflow.com/questions/tagged/naudio)

**Comment by SmokinLeather** [comment]
Thanks Mark.
I guess StackOverflow is a reasonable replacement. 
The StackOverflow moderators get a bit anal. Even commenting "thank you" to someone who gives a great answer is forbidden. 
What I liked about the Codeplex Discussions forum was that you could carry on a friendly conversation with someone.
But oh well, adapt or perish. :-)

PS. Might be worth adding a note on the README.md about StackOverflow being the place for developer questions. 

Thanks for NAudio. Truly a Masterpiece.

**Comment by Emyr42** [comment]
Commenting thank you is fine, so long as you don't post it as an answer.
