### ISSUE TITLE
Need an NAudio.dll version for using in Silverlight Application 

### ISSUE THREAD

**Issue by frajos100** [naudio/NAudio#243]
Need an NAudio.dll version for using in Silverlight Application to record Audio coming from laptop speaker using WasapiLoopbackCapture.
Currently Silverlight Project is not allowing to add NAudio.dll since it is not built against the Silverlight runtime. Do you have a separate version of NAudio for Silverlight?

**Comment by markheath** [comment]
no sorry, there is no NAudio version available for silverlight, and you would not be able to call WasapiLoopbackCapture from silverlight anyway as it is a sandboxed environment without direct access to Windows APIs
