### ISSUE TITLE
UWP Audio Capture and InvalidCastException

### ISSUE THREAD

**Issue by ciarandavies7191** [naudio/NAudio#244]
When building UWP application under VS2010, builds generates a RTE of InvalidCast in NAudio.WinRT.dll 
 when attempting to capture audio if compiled with "Compile with .NET Native toolchain".

**Comment by markheath** [comment]
I assume you don't mean VS2010, but in any case there are some known issues supporting the .NET Native toolchain which I have sadly not had time to troubleshoot.

**Comment by ciarandavies7191** [comment]
VS2010 does not produce the RTE, no, rather any application that uses the built artifact (from my tests).
I have made some changes to the project that allowed the library to work with UWP which I would be happy to share.

**Comment by markheath** [comment]
sure, feel free to issue a PR
