### ISSUE TITLE
StopRecording on WaveIn class does not exit some times.

### ISSUE THREAD

**Issue by SreejithShenoi** [naudio/NAudio#245]
Facing one issues where as in some times StopRecording method never exits, which causing the program to hang. NAudio library is used to buffer and analyze the audio which comes across microphone input on the machine.  

Following is the code
 IWaveIn wi = new WaveIn(WaveCallbackInfo.FunctionCallback());
 wi.DataAvailable += new EventHandler<WaveInEventArgs>(_wiDataAvailable);
 wi.RecordingStopped += new EventHandler<StoppedEventArgs>(_wiRecordingStopped);
 wi.WaveFormat = new WaveFormat(8000, 16, 1);
                
 wfw = new WaveFileWriter(fileStore, wi.WaveFormat);  This is a class variable of type WaveFileWriter

 wi.StartRecording();

 //Wait for a minute
Thread.Sleep(60 * 1000);

 wi.StopRecording();

//recording stopped event handler
private static void _wiRecordingStopped(object sender, StoppedEventArgs e)
        {
            if (wfw != null)
            {
                wfw.Close();
                wfw = null;
            }

After execution of multiple trials, sometimes wi.StopRecording() never exits and this is confirmed by looking at the active threads in the Debug->Threads window in VS.

Is there something wrong in the code? Any work around for this?
        }

**Comment by markheath** [comment]
I recommend against using function callbacks. Use window callbacks, or the WaveInEvent class as an alternative to WaveIn which uses a better callback model

**Comment by SreejithShenoi** [comment]
@markheath 
Thanks for the suggestion. We changed our implementation to use WaveInEvent class, post that we did not face this issue.
