### ISSUE TITLE
Can I Include this DLL in my MIT licensed project?

### ISSUE THREAD

**Issue by NathanWarden** [naudio/NAudio#246]
I'm not too familiar with the Ms-PL. Looking at this statement in it:

"If you distribute any portion of the software in compiled or object code form, you may only do so under a license that complies with this license."

Does this mean I can include the DLL and retain my MIT license?

If yes, do I need to include a copy of the Ms-PL license for the DLL or not?

Thanks :)

**Comment by markheath** [comment]
yes, my understanding you are free to use NAudio in an MIT project and not required to supply any additional files

**Comment by NathanWarden** [comment]
Thanks Mark, I appreciate the response and also the work you've done on this library.

**Comment by Mgamerz** [comment]
We are reviewing our licenses for a GPL project we have an have been using NAudio - I have noticed this library uses MS-PL which GPL lists as incompatible. https://directory.fsf.org/wiki/License:MS-PL

GNU doesn't specifically list why. It seems to stem from the inability to sublicense it. It seems to have to do with the compiled form requiring the license too?

**Comment by markheath** [comment]
MS-PL was chosen as a permissive license. I've no idea why it's marked as incompatible with GPLv3. I don't have any problems with you using NAudio in your project.
