### ISSUE TITLE
Naudio WPF Demo 8 band Equalizer Frequency ranges

### ISSUE THREAD

**Issue by SmokinLeather** [naudio/NAudio#247]
Hi Mark, et al,

I'm working with the Naudio WPF Demo 8 band Equalizer. It works nicely. But I can't figure out the audible frequency bands (0-22KHz range) for each of the band sliders. 

The demo code looks like this...

```
 bands = new EqualizerBand[]
                   {
                        new EqualizerBand {Bandwidth = 0.8f, Frequency = 100, Gain = 0},
                        new EqualizerBand {Bandwidth = 0.8f, Frequency = 200, Gain = 0},
                        new EqualizerBand {Bandwidth = 0.8f, Frequency = 400, Gain = 0},
                        new EqualizerBand {Bandwidth = 0.8f, Frequency = 800, Gain = 0},
                        new EqualizerBand {Bandwidth = 0.8f, Frequency = 1200, Gain = 0},
                        new EqualizerBand {Bandwidth = 0.8f, Frequency = 2400, Gain = 0},
                        new EqualizerBand {Bandwidth = 0.8f, Frequency = 4800, Gain = 0},
                        new EqualizerBand {Bandwidth = 0.8f, Frequency = 9600, Gain = 0},
                   };
```

So assuming standard audio spans from 0Hz to 22050 Hz, how does the Frequency parm in the EqualizerBand constructor map to the 0-22KHz range?

**Comment by markheath** [comment]
The frequency parameter is in Hz, and you can give it any value (obviously staying below Nyquist frequency - half the sample rate). I kept the maximum band fairly low in this example to avoid issues with lower sample rates, but no reason why you can't go higher.

**Comment by SmokinLeather** [comment]
Mark,
Thanks for the quick reply.

Ok, so for audio with a 44.1K sample rate I could set Frequency as high as 22050?
Example
`new EqualizerBand {Bandwidth = 0.8f, Frequency = 22050, Gain = 0},`

What I might do is get the sample rate in the ISampleProvider constructor and calc the Frequency for each band accordingly.

**Comment by SmokinLeather** [comment]
I found this link that has a good explanation of how to choose the Equalizer bands frequencies.   
https://www.presonus.com/learn/technical-articles/equalizer-terms-and-tips

With this info, I'm closing this issue. If anyone has anything to add, please do comment below.
