### ISSUE TITLE
 Invalid controllerValue 226 for controller Pan, Pos 0xAE3

### ISSUE THREAD

**Issue by taovo** [naudio/NAudio#250]
Hi,
I got the message  **Invalid controllerValue 226 for controller Pan, Pos 0xAE3** when I try to load midi file (https://www.dropbox.com/s/0r9kxs0igvw2s23/7019.midi?dl=0). Anyone can help me? I try to play it with VLC or window media sucessfully.
Thanks,

**Comment by markheath** [comment]
either the file has a genuine invalid CC value (values should be in range 0-127) or an earlier event has been misinterpreted. Maybe could add a mode to silently ignore errors like this.
