### ISSUE TITLE
WPF demo - Media Foundation playback was a crash

### ISSUE THREAD

**Issue by ZhaiSoul** [naudio/NAudio#251]
Hi,I need some help
WPF Demo use Media Foundation playback play URL was a crash
MediaFoundationReader.cs
MediaFoundationInterop.MFCreateSourceReaderFromURL(file, null, out reader);
System.Runtime.InteropServices.COMException:“Exception from HRESULT: 0xC00D2EFE”

System:Windows 10

thanks

**Comment by markheath** [comment]
This error seems to be:

0xC00D2EFENS_E_BAD_SYNTAX_IN_SERVER_RESPONSE | The response from the media server could not be understood. This might be caused by an incompatible proxy server or media server.

It just means that MediaFoundation can't interpret the format of data coming from that server.
