### ISSUE TITLE
can't found Mp3FileReader

### ISSUE THREAD

**Issue by XanderChenChina** [naudio/NAudio#253]
- System : Windows 10
- Platform : Universal Windows Platform
- Language : CSharp
- NAudio Version : 1.8.3 ( use nuget download )

I just copy some code on this web page : https://stackoverflow.com/questions/7932951/trimming-mp3-files-using-naudio , because i want trim some music to make ringtone . 

and in my programm , i can not use Mp3FileReader .

IDE told me is doesn't exist on NAudio.Wave .

**Comment by markheath** [comment]
I'm afraid Mp3FileReader cannot be used in a UWP app as it uses ACM codecs that are not permitted to be used in UWP

**Comment by XanderChenChina** [comment]
thank you

i will try it

wish me lucky
