### ISSUE TITLE
Throw UnspecifiedError when change Percent of UnsignedMixerControl instance

### ISSUE THREAD

**Issue by akiJoin** [naudio/NAudio#256]
Please help me, thanks!!
In some case, It throws an exception below:
NAudio.MmException   UnspecifiedError calling mixerSetControlDetails

 public double MicrophoneLevel
        {
            get
            {
                return _desiredVolume;
            }
            set
            {
                _desiredVolume = value;
                if (_mixerControl != null)
                {
                    _mixerControl.Percent = value;
                }
            }
        }

it invoke on "  _mixerControl.Percent = value;"

**Comment by markheath** [comment]
What value are you setting it to?
