### ISSUE TITLE
How to get MIDI CC message from nAudio?

### ISSUE THREAD

**Issue by yorkzhang** [naudio/NAudio#258]
I am having problem to read the MIDI CC message from nAudio library, especially CC64. Any ideas about how to read it? Thanks a lot in advance.

**Comment by markheath** [comment]
what do you mean? Are you trying to get this from a MIDI device or from a MIDI file?

**Comment by yorkzhang** [comment]
Thanks for the reply.I am try to get this data from a MIDI file.

**Comment by yorkzhang** [comment]
May I have your anwer? Thanks. @markheath

**Comment by markheath** [comment]
You can use the `MidiFile` class to read all the MIDI events in a file.
Use the `Events` property to get at the events, and index into it with the track number to get a list of `MidiEvent`. Look for instances of `ControlChangeEvent` in that list. The `Controller` and `ControllerValue` properties give you the controller type and number information.

**Comment by yorkzhang** [comment]
Thank you very much, Mark!

**Comment by yorkzhang** [comment]
Thank you very much, Mark!
