### ISSUE TITLE
Exception when accessing FriendlyName in devices - Failed unit tests

### ISSUE THREAD

**Issue by MichalisN** [naudio/NAudio#26]
I run the tests and 2 of them fail. Those are in Wasapi project at MMDeviceEnumeratorTests. The tests are CanEnumerateDevicesInVista and CanEnumerateCaptureDevices.

I did some investigation, they both fail for the same reason, the MMDeviceEnumerator returns the devices but the ones with state DeviceState.NotPresent throw exception when FriendlyName is accessed. In the demo applications only Active devices are used so no exceptions there.

I did a fix to write (with Debug.WriteLine as it was) the name only on the ones with state different than NotPresent and the ID for the ones with state NotPresent. Let me know if the tests are valid with this change to submit a pull request.

**Comment by markheath** [comment]
yes, that would be great, thanks
