### ISSUE TITLE
Length of Mp3 badly reported in windows

### ISSUE THREAD

**Issue by matiaschamu** [naudio/NAudio#262]
When I generate an mp3 in C # the length is misinformed in windows (the quality is 128kb ABR)

**Comment by matiaschamu** [comment]
example: 

https://drive.google.com/open?id=1DJyOIseXx52pdfgLnSx3VSSA-1Px48Ts

This audio actually lasts 2:00 min, however in windows it appears as 1:14 min.
The coding is ABR 128kbit, 44000khz mono.

Generated with naudio v1.8.3 and naudio.lame v1.0.6

Excuse my English, I'm from Argentina and my English is bad

**Comment by markheath** [comment]
This is not something NAudio has control over - LAME is producing the audio file.
