### ISSUE TITLE
ReleaseNotes outdated

### ISSUE THREAD

**Issue by FroggieFrog** [naudio/NAudio#263]
What are the changes between 1.8.0 (availbale via GitHub releases) and 1.8.3 (available via NuGet)?
Whay are there no tags in the repository?

**Comment by markheath** [comment]
I only tend to write changes for the major releases. For point releases you can just check the GitHub history.

The NAudio project was originally a Mercurial repository (and before that Subversion) so the tags were lost on conversion. I think there are some for later releases though and will probably add tags for previous releases in the future.
