### ISSUE TITLE
Record using RF64 or BWF file to exceed 4GB limit

### ISSUE THREAD

**Issue by psideas** [naudio/NAudio#264]
Hi,

It is my understanding that RF64 and BWF files are not limited by the 4GB limit on WAV files.

I seek some help on how to record to this type of file. My application has settings for sample rate, channels, and audio device (if anything is different there as well).

Thanks

**Comment by markheath** [comment]
I've actually very recently checked in a BWF writer to NAudio:
https://github.com/naudio/NAudio/blob/master/NAudio/Wave/WaveOutputs/BwfWriter.cs
Here's a tutorial on using it:
http://www.markheath.net/post/naudio-rf64-bwf
It's not in a released version of NAudio yet, so just copy the code from the blog post into your own app for now.

**Comment by psideas** [comment]
Thanks, Mark. If I understand correctly, I can make BwfWriter.cs into an independent DLL and import as a reference to my VB.NET application.

At that point, I believe I could use the following line to call it:
BwfFile = New BwfFileWriter(filespec, newBwf.WaveFormat)

Is this correct? Are there any other parameters (in addition to the above) I would need to include in the BwfWriter() call? I would imagine this would still write directly to the file as opposed to write to memory.

Thanks for the help.

**Comment by markheath** [comment]
BwfFileWriter is now part of NAudio 1.8.4, so you can just use it directly. You also need to provide a BextChunkInfo to the constructor containing file metadata

**Comment by psideas** [comment]
That is great. How would I construct a blank BextChunkInfo if I am using a database for all data pertaining to the file?
