### ISSUE TITLE
CrossFade is possible or not with NAudio?

### ISSUE THREAD

**Issue by SR-TheCodingGenius** [naudio/NAudio#270]
HI, 
I wanted to know whether we can crossfade two different audio sources using naudio or not,
the scenario is audio_file1 and audio_file2 both are playing parallely with volumes 1 and 0 , when I hit Crossfade button the volumes should be swapped , that means one audio file should fade-out and other should fade-in.
 I tried several ways to implement this using NAudio and finally I came to know only one file can be fade-in and fade-out at a time, I did  this using FadeInOutSampleProvider class , but no luck , only one file can be faded in or out, that was my outcome after doing lot of research and analysis , 
IS there any any way using Naudio to switch between two files using crossfade?

Note - all the audio files are passed through mixer, the code is some thing like this.
var mixer = new MixingWaveProvider32(inputs.Select(c => c._channels));
_waveOutDevice.Init(mixer);

mixer contains 3 inputs (audio streams) where only one will be playing with volume 1 and others are playing with volume 0, when I hit on Button2 the second stream should fade in and first stream should fade out, simliarly the pattern follows...

**Comment by markheath** [comment]
hi, I recently wrote [an article](https://github.com/naudio/NAudio/blob/master/Docs/FadeInOutSampleProvider.md) on `FadeInFadeOutSampleProvider` which you may find helpful

Out of the box, NAudio does not have a crossfade feature though, so you have to implement it yourself.
In your case it sounds like you might be able to wrap each mixer input (using `MixingSampleProvider` will be easier) in a `FadeInOutSampleProvider` and so when the button is hit, fade out the one that is playing and fade in the other one.

**Comment by SR-TheCodingGenius** [comment]
Ok, I created a high resolution timer in my code and trying to set the volumes in high resolution of time
for eg - 400 micro seconds, does the audio will settle at that pace, if pass on volume samples at that rate?
I tried to set the volumes at 400 microseconds interval to WaveOutEvent object, it seems the audio player object is not get settled at that particular volume, Is there any suggestion you can make, by tweaking settings it will settle at that volume at high resolution.

**Comment by SR-TheCodingGenius** [comment]
I tried using FadeInOutSampleProvider before, as we need to pass it through Init method of the wave player object  it will fade out the currently playing stream, but it doesnot fade in the other stream which needs to be fade in, which is the actual problem

**Comment by markheath** [comment]
Yes, `FadeInOutSampleProvider` does not implement crossfade. But you can adapt its code to make your own cross-fading sample provider

**Comment by fosterz** [comment]
can somebody put some light like how I can adapt it.

**Comment by ddorsey84** [comment]
> can somebody put some light like how I can adapt it.

Has there been any updates on this @fosterz ?
