### ISSUE TITLE
Invalid MP3 file - no MP3 Frames Detected

### ISSUE THREAD

**Issue by Deathrage** [naudio/NAudio#272]
Hi I have a memory stream which was created by combining 3 mp3 files. When I download it as a server response it works fine, but when I try read the stream using Mp3FileReader it throws: Invalid MP3 file - no MP3 Frames Detected.

using (var mp3stream = new MemoryStream())
        {
            Combine(filenameArray, mp3stream);
            using (var reader = new Mp3FileReader(mp3stream))
            {
                var waveformat = new WaveFormat(8000, 16, 1);
                var wavestream = new RawSourceWaveStream(reader, waveformat);
                WaveFileWriter.WriteWavFileToStream(wavestream, reader);
                var wavePlayer = new DirectSoundOut();
                wavePlayer.Init(wavestream);
                wavePlayer.Play();
            }
        }

And here is the funtion Combine, it loads files from string array and merges them in one output memory stream:

public static void Combine(string[] inputFiles, Stream output)
    {
        foreach (string file in inputFiles)
        {
            
            Mp3FileReader reader = new Mp3FileReader(file);

            if ((output.Position == 0) && (reader.Id3v2Tag != null))
            {
                output.Write(reader.Id3v2Tag.RawData, 0, reader.Id3v2Tag.RawData.Length);
            }
            Mp3Frame frame;
            while ((frame = reader.ReadNextFrame()) != null)
            {
                output.Write(frame.RawData, 0, frame.RawData.Length);
            }

        }
    }

**Comment by markheath** [comment]
after calling combine, reset the memorystream position to 0. And then after that you don't need most of the code you have. Just call `wavePlayer.Init(reader)`
