### ISSUE TITLE
build errors in Visual Studio 2015?

### ISSUE THREAD

**Issue by relaxok** [naudio/NAudio#276]
Hi - sorry, I'm not a C# expert so not sure what's up here.  I downloaded the latest as of today.  I'm loading NAudio.sln in Visual Studio 2015 Update 3 and there are ~15 build errors in the code due to lines like:

get => midiFileType; 
set => throw new InvalidOperationException("Repositioning a WaveFileWriter is not supported");

etc.

Seems like some language feature that's not supported but this is a fairly recent IDE so are you really using things that only work in 2017 or something? What am I missing?

**Comment by markheath** [comment]
Yes, you need 2017 to develop NAudio (the free community edition should be fine). It's only if you want to work on the project - you can reference the NuGet package and use it from any version of Visual Studio

**Comment by relaxok** [comment]
Thanks
