### ISSUE TITLE
seeking long waveform

### ISSUE THREAD

**Issue by premingiet** [naudio/NAudio#277]
I have a long waveform created using nAudio library but i am unable to seek or scroll through the entire waveform on horizontal scroll bar scrolling. I am using windows forms

**Comment by markheath** [comment]
hi, I'm afraid NAudio isn't really focused on providing GUI components. You'd need to write your own WaveForm visualizer if you need this sort of behaviour.

**Comment by premingiet** [comment]
I figured out the solution. Now i am able to scroll through the entire waveform of about 3 hours long waveform without any issues. thanks by the way.

**Comment by markheath** [comment]
great, glad you got it working
