### ISSUE TITLE
UnspecifiedError calling mixerSetControlDetails

### ISSUE THREAD

**Issue by timjekri** [naudio/NAudio#278]
Hello,
When setting the MicrophoneLevel, it sometimes throw an exception:
NAudio.MmException: UnspecifiedError calling mixerSetControlDetails

public double MicrophoneLevel
{
	get
	{
		return desiredVolume;
	}
	set
	{
		desiredVolume = value;
		if (volumeControl != null)
		{
			volumeControl.Percent = value;
		}
	}
}

I have been doing some testing and debugging to try and figure out the reason for this.

Setting the UnsignedMixerControl.Percent to different values have no impact. (Tried multiple numbers between 0 and 100)
It seems to only happen when using a specific recording device (of the few tested).
When using the "Plantronics Blackwire C310-M" the issue happens, while using the integrated microphone or other external microphones, there are no problems.

From what I can see, this is also the only recording device that does NOT have a volume slider in Windows (Under: Sound -> Recording -> Select recording device -> Properties -> Levels)

Can it be that this recording device is readonly, and it will throw an exception when trying to write to this device?

The only issue with this theory is; it throws an exception when using Windows 10. However, when testing on Windows 7 it does not throw an exception.

I have looked at the code for the UnsignedMixerControl, but I am not entirely sure exactly what it does in the Value setter.
Any idea to what the issue might be?

Thanks.

**Comment by markheath** [comment]
possibly, I've found the mixer APIs to be horribly inconsistent between different soundcards and versions of Windows. I'd only touch them if you absolutely need to. It's better to use WASAPI and MMDevice since Windows Vista.
