### ISSUE TITLE
NAudio (1.8.3.0) ASIO Out doesn't work with Steinberg UR22 mk II

### ISSUE THREAD

**Issue by Dries9605** [naudio/NAudio#280]
I am trying to use the Steinberg UR22 mk II type with the ASIO Out Class in NAudio. To check if the device is connected, I call the function ASIODriver.GetLatencies(Input, Output) as Result. This always returns ASIO_NotPresent, even if the device is connected.

If I use the DirectsoundOut Class, I can play music through it, but sometimes my music players stops playing music and I have to call the DirectsoundOut.Init() function again to play music again.

I am having these problems only with this device. I have already worked with 2 other devices without any problem.

**Comment by markheath** [comment]
what other ASIODriver methods have you tried? Possibly you need to open the device before calling GetLaencies with that soundcard

**Comment by Dries9605** [comment]
I am using the GetChannels() method to list the channels and the GetChannelInfo() to get the name of the channel. Never got an error with these methods.

I use this code to create the ASIOOut class: 

  Try
                   ASIOCore = New AsioOut(_DriverName)                 <--- this line throws an exception
                   ASIOCore.ChannelOffset = _StartChannel
                   ASIOCore.Init(VolumeControl.ToWaveProvider)

                  ASIOCore.Play()
                  AudioCore = ASIOCore

                  _VU.SetAvailableColor()
                  _State = AudioDeviceState.Opened

Catch ex As Exception
                  frmErrorLog.AddError(ex.ToString)
                  MsgBox(ex.Message)
                  _DevNotReady = True
                  ASIOCore = Nothing
                  _VU.SetUnavailalbeColor()
End Try

When I use this code, without the function to check if the device is connected, I get the following error:
(I checked the '_DriverName' value, which was correct)

System.InvalidOperationException: Device could not be opened.
   bij NAudio.Wave.Asio.AsioDriverExt..ctor(AsioDriver driver)
   bij NAudio.Wave.AsioOut.InitFromName(String driverName)
   bij NAudio.Wave.AsioOut..ctor(String driverName)
   bij DB_Theatre_Cue.AudioDevice.OpenDevice()

**Comment by markheath** [comment]
ok I see. Very hard to diagnose this sort of problem without having that exact soundcard. Can other programs open the ASIO driver?

**Comment by Dries9605** [comment]
I use Steinberg Cubase Artist (same manufacturer) and Adobe Audition with this audio interface. They don't have any problems with it.

I've seen Steinberg also got an SDK for Asio:
https://www.steinberg.net/en/company/developers.html

**Comment by Dries9605** [comment]
I've been testing with this audio interface, and I found something that can cause the problem. I used this code below in my test project to play a random music file:

```
    'If NAudio.Wave.Asio.AsioDriver.GetAsioDriverByName(ListBox1.SelectedItem.ToString).GetLatencies(inp, out) = NAudio.Wave.Asio.AsioError.ASE_OK Then
            '    NAudio.Wave.Asio.AsioDriver.GetAsioDriverByName(ListBox1.SelectedItem.ToString).ReleaseComAsioDriver()

            reader = New AudioFileReader(TextBox1.Text)

            volume = New VolumeWaveProvider16(reader.ToWaveProvider16)

            asio = New AsioOut(ListBox1.SelectedItem.ToString)

            asio.Init(volume)



            asio.Play()

            Timer1.Start()
            'End If
```
When I use the NAudio.Wave.Asio.AsioDriver.GetAsioDriverByName() method, the code returns at 'asio = new AsioOut'. When I don't use this method, and immediately create the AsioOut class, the code doesn't return an error and the music file is playing smoothly.

**Comment by markheath** [comment]
ok, great, glad you found a solution
