### ISSUE TITLE
AsioSampleConvertor

### ISSUE THREAD

**Issue by mouthbow** [naudio/NAudio#281]
Hi!

I need a converter for this case in class NAudio.Wave.Asio.AsioSampleConvertor:

                case AsioSampleType.Float32LSB:
                    switch (waveFormat.BitsPerSample)
                    {
                        case 16:
                            throw new ArgumentException("Not a supported conversion");

I have been trying to implement but I'm not getting any success, I don't really understand what the converter has to do. I hope someone has implemented it or maybe you can give me any direction to do it.

Many thanks in advance.

**Comment by markheath** [comment]
Hi, its hard to code these without a soundcard that can replicate them. But I've had a go creating a new converter method. Would you be willing to try this out for me:

        /// <summary>
        /// Generic convertor for float
        /// </summary>
        public static void ConverterShortToFloatGeneric(IntPtr inputInterleavedBuffer, IntPtr[] asioOutputBuffers, int nbChannels, int nbSamples)
        {
            unsafe
            {
                short* inputSamples = (short*)inputInterleavedBuffer;
                float*[] samples = new float*[nbChannels];
                for (int i = 0; i < nbChannels; i++)
                {
                    samples[i] = (float*)asioOutputBuffers[i];
                }

                for (int i = 0; i < nbSamples; i++)
                {
                    for (int j = 0; j < nbChannels; j++)
                    {
                        *(samples[j]++) = (*inputSamples) / 32768f;
                        inputSamples++;
                    }
                }
            }
        }

**Comment by markheath** [comment]
Did you have a chance to try this out?

**Comment by mouthbow** [comment]
Hi!
First of all many many thanks for your help!!!
I was a little bit ashamed because I had this problem when I wrote the issue on december 20th. 
But I'm not sure in which conditions the problem was happening. I thing It was with a brand new soundcard I bought and finally I gave back to provider.
So I'm not able to try this and I'm sorry about that.
I have incorporated to the code with a breakpoint just in case.
I hope your work can help other people in this forum.

**Comment by markheath** [comment]
no problem, it is a little bit of an unusual sample conversion, but if anyone runs into to it again, they can try the code above

**Comment by henon** [comment]
You'll get the `"Not a supported conversion"` ArgumentException when trying to play a 16 bit PCM wave provider to an `AsioOut`. I solved the problem by using the `Wave16ToFloatProvider` to convert from 16 to 32 bit which plays fine with the built-in sample sample conversion functions in `AsioOut`.
