### ISSUE TITLE
WAV file not in sync with source MP3 file

### ISSUE THREAD

**Issue by ftppro** [naudio/NAudio#282]
I am using the methods described here to convert a 2-hour MP3 file into a WAV file:
https://github.com/naudio/NAudio/blob/master/Docs/ConvertMp3ToWav.md

The resulting WAV file is not in sync with the source MP3 file:
MP3 second #996 = WAV second #1000
MP3 second #1991 = WAV second #2000

The Google Speech API requires a WAV file to create a time-coded transcript, but the time codes are then not accurate for the MP3 file (which is a podcast).

I have to use MP3 as the source format, since that is what all the podcasts use.

How can I create a WAV file that is in sync with the source MP3 file?

**Comment by markheath** [comment]
which technique did you use? I would expect `MediaFoundationReader` to give the most accurate results.

**Comment by ftppro** [comment]
Thank you for your reply.

I tried all the available methods to transfer an MP3 to a WAV file
(including  MediaFoundationReader), and every resulting file was
out-of-synch.

You can replicate this problem by transferring an MP3 file downloaded here:
http://adamcarolla.com/ally-hilfiger-steve-hash-and-jeff-cesario/

Towards the end of the podcast, make a note of the exact minute-and-second
that the MP3 plays a particular section, and you will find that the WAV
file is 20 seconds later.

This makes it impossible to use the Google Speech API, because they will
only accept WAV files (not MP3 files), and therefore the resulting
time-coded transcript does not align with the MP3 podcast.

**Comment by markheath** [comment]
does this happen with all podcasts or just this one? I suspect there must be something unusual about this particular mp3 file if the same issue is seen with all the decoding techniques.

**Comment by ftppro** [comment]
According to Adobe Soundbooth, the Sample Rate of the problematic MP3 is
44.1 kHz, and the converted WAV file is also 44.1 kHz.

However, when I tried a different podcast, the problem did not happen:
https://www.stuffyoushouldknow.com/podcasts/how-seven-wonders-ancient-world-works-part-i.htm
The MP3 from that website was in sync with the converted WAV file (the
problem did not occur). The sample rate of that MP3 was 22.05 kHz, and the
converted WAV file was 32 kHz.

What is it about the following podcast that causes this problem?
http://adamcarolla.com/ally-hilfiger-steve-hash-and-jeff-cesario/

**Comment by ftppro** [comment]
I tried using your MediaFoundationReader class to convert another podcast
MP3 to a WAV file, and it also failed to create a file that is in synch
with the original MP3:
https://www.podbean.com/site/EpisodeDownload/PB79C0F4D5XWI

Do you know of any solution? Otherwise, I cannot create transcripts with
accurate timecodes for podcast files.

**Comment by markheath** [comment]
if MediaFoundationReader can't produce matching WAV files I suspect there is something odd about the MP3 itself, and not something we can fix in NAudio
