### ISSUE TITLE
Wave refusing to play outside the monitor

### ISSUE THREAD

**Issue by Gizego** [naudio/NAudio#283]
I am playing a WaveOut directly and even doing this:
wave.DeviceNumber = -1;
it does not work. How do i convert this:
var enumerator = new MMDeviceEnumerator();
var device = enumerator.GetDefaultAudioEndpoint(DataFlow.Render, Role.Console);
to an int that i can use?
My code:

[Sample.txt](https://github.com/naudio/NAudio/files/1588921/Sample.txt)

**Comment by markheath** [comment]
`MMDeviceEnumerator` enumerates WASAPI devices. You;d use `WasapiOut` to open the devices you find that way.

`WaveOut` uses the legacy `waveOut` Windows APIs, so you need to call `GetCapabilities` to get details of the available devices. 

[This article](https://github.com/naudio/NAudio/blob/master/Docs/EnumerateOutputDevices.md) should help.
