### ISSUE TITLE
WasapiOut fails to resample automatically.

### ISSUE THREAD

**Issue by logicbait** [naudio/NAudio#284]
I'm writing the following code to play audio from a URL, but it throws an exception:
```c#
var source  = new MediaFoundationReader(_url);
var wasapi  = new WasapiOut(sharing,
    _latency);
wasapi.Init(source); // throws exception
wasapi.Play();
// ....
```
I thought `WasapiOut` was meant to automatically resample the `IWaveProvider` to fit the default sound device.  Interestingly, the following code works without a problem:
```c#
var source  = new MediaFoundationReader(_url);
var wasapi  = new WasapiOut(sharing,
    _latency);
var resample    = new ResamplerDmoStream(source,
    wasapi.OutputWaveFormat);
wasapi.Init(resample); // happy now
wasapi.Play();
// ....
```
It works for now, but feels unnecessary.
## Exception Details ##
ArgumentException {"Unsupported Output Stream format\r\nParameter name: outputFormat"}
   * at NAudio.Wave.ResamplerDmoStream..ctor(IWaveProvider inputProvider, WaveFormat outputFormat)
   * at NAudio.Wave.WasapiOut.Init(IWaveProvider waveProvider)

**Comment by markheath** [comment]
interesting. WasapiOut attempts to find the closest supported format which may be different from OutputWaveFormat. It would be interesting to see what those two formats are in your case.

**Comment by logicbait** [comment]
According to the debugger, source.WaveFormat is {16 bit PCM: 44kHz 2 channels} and wasapi.WaveFormat is {IeeeFloat}.

**Comment by Paulsrud** [comment]
Hi
I get the same exception in WasapiOut.Init() when playing a wav-file. 
Input format is 12025 Hz and output format is 16000 Hz in my case.
Note. This worked without problem in Windows7 but not in Windows10.

**Comment by pdxmholmes** [comment]
I found this happening on my particular output device as well. It seems to be that some devices, mine included, return a very strange format for the "closestSampleFormat" when checking if the IWaveProvider.WaveOutput format is valid. This format is rejected by the DMO resampler.

I have some code to work around it that basically forces a fallback to MixFormat if it get's an exception trying to initialize the DMO resampler with the "closest" sample format.
