### ISSUE TITLE
NAudio and .NET Core?

### ISSUE THREAD

**Issue by juanluelguerre** [naudio/NAudio#285]
Hi,
Any plan/roadmap to move it to .NET Core 2.x and upper?
Regards
Juanlu

**Comment by markheath** [comment]
hi, I have experimented a bit with a .NET Standard build. The nature of NAudio is that there is a lot of stuff that is very Windows platform specific, so it would be a fairly cut-down subset of NAudio's capabilities.

**Comment by juanluelguerre** [comment]
Ooh, yes it's true! The problem here is we will have to consider specific code for each different platform! :-S
Thanks so much and once again, good job!!!
Regads
Juanlu
