### ISSUE TITLE
some audio wav files not plotting waveform properly in waveviewer in win form

### ISSUE THREAD

**Issue by urizo** [naudio/NAudio#287]
Here is a link to sample wav file
https://www.amazon.com/clouddrive/share/DFmVrQJvfSdVmBcHrU7Y2eV4mu9m7tK0NqvsMskVrnB

when i try to plot it on waveviewer it only shows a series of vertical lines but when i extract image of it, it shows proper waveform. I am not sure whats the issue. Only this audio file has issues. Rest all files are fine.

Also how to get total number of samples per second for the plotted waveform ? i want to draw timeline, and when i use "pixels per second", i have to manually set it and it doesn't gets synced with all audio files.
I need a way to draw timeline in x-axis that is sync with the waveform. In the source code, there is "samples per pixel" but nothing about "pixels per second". How do i get "pixels per second" ? please help

**Comment by markheath** [comment]
if you know samples per second (the sample rate) and samples per pixel, then you get pixels per second by dividing the sample rate by samples per pixel.
