### ISSUE TITLE
WasapiOut Crashing Web Video and Audio Players

### ISSUE THREAD

**Issue by Gizego** [naudio/NAudio#288]
I moved my sample class in my game engine to WASAPIOUT but, when i create a new wasapi out:
 WasapiOut o = new WasapiOut(new MMDeviceEnumerator().GetDefaultAudioEndpoint(DataFlow.Render, Role.Multimedia), AudioClientShareMode.Exclusive, false, 0);
every chrome / edge / mozilla video player crashes. I dont need to start playing it. 
I'm using windows 10 x64

**Comment by lorddev** [comment]
Do you think it could be related to "AudioClientShareMode.Exclusive" ?

**Comment by Gizego** [comment]
if its shared it does not go to the default device

**Comment by markheath** [comment]
The share mode should not affect what device you are playing from.

**Comment by Gizego** [comment]
its not getting on my headphones with shared mode

**Comment by markheath** [comment]
Are they USB headphones? Check the name of the device returned by `GetDefaultAudioEndpoint` to see if its what you expected. But there's not a lot different NAudio can do to change what device the sound plays out of - we're just passing the device through to the WASAPI APIs
