### ISSUE TITLE
How to get WaveInEvent from MMDevice.

### ISSUE THREAD

**Issue by kimhc999** [naudio/NAudio#289]
I want to get WaveInEvent object from MMDevice object.
The reason I want to do that is, When I change the mic volume, I want to use MMDevice object, when I record, I want to use WaveInEvent.
Is there any way to get WaveInEvent object?
I checked all attributes in WaveInEvent and MMDevice. But I could not find the way.

**Comment by markheath** [comment]
`WaveIn` and `MmDevice` represent two different audio APIs - I don't know of a reliable way to use the two together. In general if you need `MMDevice` functionality, you should be using the `WasapiCapture` class instead of `WaveIn`
