### ISSUE TITLE
IOException file in use by another user

### ISSUE THREAD

**Issue by adig14** [naudio/NAudio#290]
I am converting an app which plays alaw wav files. This has been made easier by using NAudio as can be done by the following code:

private NAudio.Wave.WaveFileReader wave = null;
private NAudio.Wave.DirectSoundOut output = null;
wave = new NAudio.Wave.WaveFileReader(CurrentFile);
NAudio.Wave.WaveStream stream = NAudio.Wave.WaveFormatConversionStream.CreatePcmStream(wave);
output = new NAudio.Wave.DirectSoundOut();
output.Init(new NAudio.Wave.WaveChannel32(stream));
output.Play();

All this works fine when I have multiple versions of the app on different PCs playing the same wav. The problem comes when I try and play a wav file I am creating from another app as I get an IOException, file in use by another user.

The previous player read a temporary file to get all the wav header information as the wav creation app creates a dummy wav header and updates it when the recording is completed. This then used a BinaryReader and BaseStream.Seek to get data and used marshal to write it to the sound device. This would open the file with FileAccess.Read and FileShare.ReadWrite.

I can used the old code for the playing of files being recorded but as this is a less frequent requirement but would prefer to use NAudio for both types of files as it appear to be a lot tidier and makes better use of resources. Any pointers on how to resolve this? Thanks

**Comment by markheath** [comment]
You can open `WaveFileReader` passing in a `Stream`, so you could try opening the file with the necessary share permissions.
