### ISSUE TITLE
change human audio voice to robot style

### ISSUE THREAD

**Issue by vovanb** [naudio/NAudio#293]
Hi Is it possible to change audio to mechanized voice using NAudio? Can you provide examples?

**Comment by markheath** [comment]
NAudio does not include speech synthesis or robot voice effects. There are speech synthesis libraries for Windows if that's what you're after. If you want an effect to make an existing voice sound robotic I recommend implementing ring modulation

**Comment by vovanb** [comment]
And ring modulation I can do using naudio?
