### ISSUE TITLE
Generate signal not by playing media file

### ISSUE THREAD

**Issue by qianthinkover** [naudio/NAudio#294]
Hi guys,
     I have a question about this code library, Is it possible to generate the signal list result without playing the media file? all your demo is to generate  signal when play the file.

**Comment by markheath** [comment]
I'm not sure exactly what you're asking. NAudio does not require you to play from audio files - you can generate your own sounds. And you don't need to play audio through the sound card. You can use it to generate audio files. Check [the tutorials in the main readme](https://github.com/naudio/NAudio) for an idea of the scope of what is achievable with NAudio.
