### ISSUE TITLE
MIDI KeySignatureEvent.SharpsFlats Bug

### ISSUE THREAD

**Issue by davidluzgouveia** [naudio/NAudio#295]
I found a bug on the `SharpsFlats` property of the `KeySignatureEvent` class, but it's trivial to fix.

The property is supposed to return values between -7 and 7, but because you're casting directly from byte into int, the sign bit doesn't get evaluated and negative values wrap around to the the 250~ range instead of coming up negative. 

To fix, simply cast to sbyte before returning the value, like so:

```
public int SharpsFlats
{
    get
    {
        return (sbyte)this.sharpsFlats;
    }
}
```

Here's a permalink to the line that needs the fix:

https://github.com/naudio/NAudio/blob/1a99d54276d32f26cf1cc5e4ace43fe89d773460/NAudio/Midi/KeySignatureEvent.cs#L51

**Comment by markheath** [comment]
thanks for reporting
