### ISSUE TITLE
ReadFullyStream: Unable to read data from the transport connection: The connection was closed

### ISSUE THREAD

**Issue by Japollack** [naudio/NAudio#296]
Sometimes an application crash occures. Not sure what is the root cause and how or where to handle it. Any insight?

This line crashes while trying to connect to an internet radio station:
**readAheadLength = sourceStream.Read(readAheadBuffer, 0, readAheadBuffer.Length);**
at _NAudio/NAudioDemo/Mp3StreamingDemo/ReadFullyStream.cs_

```
System.IO.IOException
  HResult=0x80131620
  Message=Unable to read data from the transport connection: The connection was closed.
  Source=System
  StackTrace:
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at x.Services.ReadFullyStream.Read(Byte[] buffer, Int32 offset, Int32 count) in x:\Services\ReadFullyStream.cs:line 56
```

**Comment by markheath** [comment]
sounds like you're trying to read from a socket that has been closed. This could be a malformed MP3 file. If its just internet radio, I'd simply catch the exception and carry on.
