### ISSUE TITLE
Issue with 4 channel interface

### ISSUE THREAD

**Issue by protocat-112** [naudio/NAudio#299]

**Comment by protocat-112** [comment]
Thanks again for the code! Just wondering, is it possible to record from audio interfaces with more than 4 channels? Code works fine for audio inputs with 1 and 2 inputs, but can't handle 4. I have forked and downloaded the NAudio source code to debug further, and when I try and record from my 4-channel interface, audioClientInterface.Initialize() in AudioClient returns a value of '-2147024809' for some reason.
![image](https://user-images.githubusercontent.com/16902799/35883462-35d6fe30-0b7f-11e8-9c49-77dc6683146f.png)
This is the waveform it is trying to record from. Everything is the same a working stereo audio source, except the AverageBytesPerSecond, BlockAlign and Channels are twice as big (as expected). Your help would be greatly appreciated!

**Comment by protocat-112** [comment]
Oh, and I am using WasapiCapture. This is the call stack:
![image](https://user-images.githubusercontent.com/16902799/35883677-fd238b84-0b7f-11e8-8568-b1d12d495ec4.png)

**Comment by markheath** [comment]
Yes, unfortunately many multi-channel soundcards don't seem to easily let you record or play multi-channel audio. Most often if you want to use all the channels on a soundcard, you should make use of the ASIO drivers.

**Comment by protocat-112** [comment]
It seems that it's only 'partially supported'. Do you have any pointers for using the ASIO drivers in C#?

**Comment by protocat-112** [comment]
Your ASIO method  has fixed the problem, many thanks!
It seems a bit in effect at the moment as the AsioAudioAvailableEventArgs.GetAsInterleavedSamples() gives me floats, which I manally convert to bytes to make use of your buffered wave provider, which are then converted to shorts but hey, it works!
