### ISSUE TITLE
OGG Encoder

### ISSUE THREAD

**Issue by SirusDoma** [naudio/NAudio#300]
Hello, where can I find OGG Encoder?
And also, does this encoder works via windows API? or purely under c# language?
I need only OGG Encoder since I already have audio playback that work under mono/linux environment.

Thank you in advance

**Comment by SirusDoma** [comment]
Too bad! I'll close the issue then

**Comment by roxxel** [comment]
> Too bad! I'll close the issue then

https://github.com/roxxelr/Opus.NET maybe this will help you
