### ISSUE TITLE
How to fetch samples from output at any moment?

### ISSUE THREAD

**Issue by daintycode** [naudio/NAudio#301]
NAudio is a bit overwhelming when starting off, so how to chain something like

    Sound Output from Windows (general, all sounds played back)
         ---> My Program, fetching some sample off it, working with it

together?

No write back to the output or something. Essentially recording without saving but all the examples involving recording just pipe some WaveProviders creating sound artificially into some Recorder which saves stuff automatically.

I plan to use it in VB but I know C#, too.

I know it may be kind of vaguely asked, but where else to ask?

**Comment by markheath** [comment]
Look at `WasapiLoopbackCapture` which captures sound being played on a specific device.
