### ISSUE TITLE
Fade Out audio before it ends

### ISSUE THREAD

**Issue by SR-TheCodingGenius** [naudio/NAudio#304]
HI,

I wanted a functionality while playing the audio in a selected region it should fade out before it reaches its end, so that it doesn't produces any clicks at the end, I used DelayedFadeInOutSampleProvider class for this, I want to fadeout at 200 msecs before it reaches the selected end point or the file

if (((_waveDisplay.ChannelPosition * 1000.0) + 200.0) >= (SelectEnd * 1000.0)) 
{
if (_fadeinFlag == true)
{
_audioObject.FadeOut(_doAudioOperations[_current], fadeOutTime);
_fadeinFlag = false;
}
}

is there any better way so that It should be produce clicks ?

**Comment by markheath** [comment]
are you saying this isn't working?

**Comment by SR-TheCodingGenius** [comment]
yes

**Comment by markheath** [comment]
what's DelayedFadeInOutSampleProvider? that's not part of NAudio. There is a FadeInFadeOutSampleProvider you can use instead

**Comment by SR-TheCodingGenius** [comment]
I'm mentioning about the link which you have shared
https://gist.github.com/markheath/8fb396a5fe4bf117f361

**Comment by markheath** [comment]
ok, I can't remember what I created that for, but you can see that FadeState.FadingOut does get set here:
https://gist.github.com/markheath/8fb396a5fe4bf117f361#file-delayfadeoutsampleprovider-cs-L84

If you fade back in (with a short duration), then you can apply another fade out later
