### ISSUE TITLE
Getting error InvalidParameter calling waveInOpen

### ISSUE THREAD

**Issue by skaa** [naudio/NAudio#305]
Getting this error every time calling `WaveInEvent.StartRecording`. Method` MMDeviceEnumerator.EnumerateAudioEndPoints(DataFlow.Capture, DeviceState.Active)` returns info about my microphone. Method `WaveInEvent.GetCapabilities(0)` returns 2 channels with many `SupportedWaveFormat`.
This issue is not direct related to NAudio, tried my code with DllImport - same result. Can anybody help me?
Windows 7 SP1 x64

**Comment by markheath** [comment]
so what parameters are you calling it with?

**Comment by skaa** [comment]
```
var sourceFormat = new WaveFormat(44100, 1);
_waveIn = new WaveInEvent();
_waveIn.WaveFormat = sourceFormat;
_waveIn.DataAvailable += OnSoundDataAvailable;
_waveIn.RecordingStopped += OnRecordingStopped;
_waveIn.StartRecording(); // InvalidParameter 
```

**Comment by markheath** [comment]
OK, try with 2 channels and also with 48kHz. Maybe the drivers for your sound device are fussy

**Comment by skaa** [comment]
Same error.
WaveFormat: 16 bit PCM: 48kHz 2 channels
WaveInEvent.GetCapabilities(0): WAVE_FORMAT_48S16 and WAVE_FORMAT_48S08 are supported
Windows microphone default settings: 2 channels, 16 bit, 48000 Hz. Windows SoundRecorder.exe records wma without errors.

**Comment by markheath** [comment]
Then I have no idea why it won't open for you. Have you tried with other audio devices on your system?

**Comment by markheath** [comment]
are you in a virtual machine / rdp session by any chance?

**Comment by skaa** [comment]
This is operator PC with audio registration, not a VM nor RPD. I connecting via TeamViewer, but issue not belongs on user connection type. Will try MCI windows api.

**Comment by AliParLouS** [comment]
Why this issue is closed? It's solved? What was the solution?

**Comment by omid-94** [comment]
> Why this issue is closed? It's solved? What was the solution?

I was looking for an answer too 😄 😆

**Comment by skaa** [comment]
Nо solution found. In my case the reason was - Kaspersky antivirus on operator PC, so i have added additional message to error handler. Sample code:
```
catch (Exception ex)
{
    string msg = "Error when starting recording";
    var mmex = ex as NAudio.MmException;
    if (mmex != null && mmex.Result == NAudio.MmResult.InvalidParameter && mmex.Message.IndexOf("waveInOpen") > -1)
        msg += "warning about AV software";
    _logger.Error(ex, msg);
}
```
Sorry for issue closing without comment.

**Comment by Rac0n** [comment]
I am having the same issue

> are you in a virtual machine / rdp session by any chance?

And I am in a virtual machine. Does that have to do with the problem?

**Comment by netstacker1970** [comment]
> Nenhuma solução encontrada. No meu caso, o motivo foi o antivírus Kaspersky no PC do operador, então adicionei uma mensagem adicional ao manipulador de erros. Código de exemplo:
> 
> ```
> catch (Exception ex)
> {
>     string msg = "Error when starting recording";
>     var mmex = ex as NAudio.MmException;
>     if (mmex != null && mmex.Result == NAudio.MmResult.InvalidParameter && mmex.Message.IndexOf("waveInOpen") > -1)
>         msg += "warning about AV software";
>     _logger.Error(ex, msg);
> }
> ```
> 
> Desculpe por fechar o problema sem comentar.

Perdi horas para descobri que realmente se tratava do AV Kasperksy na minha estação de trabalho.
Muito obrigado @skaa , sua informação poupou alguns cabelos brancos. kkkk  !!!
