### ISSUE TITLE
Stutter effectt in audio for Low Latency

### ISSUE THREAD

**Issue by SR-TheCodingGenius** [naudio/NAudio#307]
Hi,

I was trying to play audio using Waveout, ASIO and WASAPI modes at low latencies below 100 msecs, I observed stutters in the audio, when I played in higher latencies it played well.
Can you please suggest what would be the best approach for playing the audio at low latencies using NAudio.

**Comment by markheath** [comment]
The lower latencies you go to, the more chances of dropouts which cause stutters. For lowest latency I recommend using ASIO drivers which offer best performance, and highly optimising the code you write inside the callbacks. if you can do things that avoid making work for the garbage collector that will help.
