### ISSUE TITLE
Trying to encode to FLAC with MediaFoundationEncoder but no success *updated #2*

### ISSUE THREAD

**Issue by datoml** [naudio/NAudio#309]
Hello,
I am trying to encode an Audio-PCM Format to FLAC using the MediaFoundationEncoder.

Calling the `MediaFoundationApi.EnumerateTransforms(MediaFoundationTransformCategories.AudioEncoder);` tells me that the FLAC encoder should be available on my system and is defined like this.

```
Name: Microsoft FLAC Audio Encoder MFT
Input Types: 1 items:
    Audio-PCM
Class identifier: 128509e9-c44e-45dc-95e9-c255b8f466a6
Output Types: 1 items:
    Audio-0000f1ac-0000-0010-8000-00aa00389b71
Transform Flags: 1
Transform Category: Audio Encoder
```

If I understand this correctly it means that this encoder accepts an Audio-PCM input and supports the `MFAudioFormat_FLAC` output type represendet with the GUID `0000-0010-8000-00aa00389b71` . 

Regarding to the documentation about [Encode to MP3, WMA and AAC with MediaFoundationEncoder](https://github.com/naudio/NAudio/blob/master/Docs/MediaFoundationEncoder.md) and [Resampling Audio](https://github.com/naudio/NAudio/blob/master/Docs/Resampling.md) I created a short example to test this.

I read the `_input.flac` file with the `MediaFoundationReader` and resample it using the `MediaFoundationResampler` and write it back to my test folder using `WaveFileWriter`. This is working great.

However when I try to read the test file that I created like described in the  [Encode to MP3, WMA and AAC with MediaFoundationEncoder](https://github.com/naudio/NAudio/blob/master/Docs/MediaFoundationEncoder.md) I always get an error.

To make sure I did nothing wrong I read the `WaveFormat` of the existing FLAC file first and use it to create my `MediaType` for the `MediaFoundationEncoder `.

But when I call the `enc.Encode(outputFlac, reader);` methode I get this error:
`The data specified for the media type is invalid, inconsistent, or not supported by this object.`

How do I know what is wrong? The input media type should be ok because I am able to create an MP3 file without any issues.

Is there a specific format I have to use for the FLAC encoder? There is unfortunately no documentation about the FLAC encoder MFT.

**Update**

After digging more through the code in this repo I managed to find the part how I am able to list all supported values for a specific GUID.

Could it be possible that I used the decoder GUID for encoding?

After creating the GUID with `new Guid("0000f1ac-0000-0010-8000-00aa00389b71")` I am able to create FLAC files. The funny part here is that the encoding only works with 32Bit Audio-PCM formats.
Regarding to the [FLAC documentation](https://xiph.org/flac/documentation_tools_flac.html) the input must be between 4 and 24 bits per sample.  No idea why it is working...

```
var availableMediaTypes = GetOutputMediaTypes(new Guid("0000f1ac-0000-0010-8000-00aa00389b71"))
                        .Where(mt => mt.SampleRate == 48000 && mt.ChannelCount == 1)
                        .Select(mt => new { MediaType = mt }) //, Delta = Math.Abs(desiredBitRate - mt.AverageBytesPerSecond * 8) })                                                              ////.OrderBy(mt => mt.Delta)
                        .OrderByDescending(mt => mt.MediaType.BitsPerSample)
                        .Select(mt => mt.MediaType);
```

**Update 2**

I managed now to make it work. Seems like I used the wrong codec so it was pure luck that it was working with 32bit Audio-PCM. 20 seconds where about 10 seconds in the output flac file. 

Here's the working code sample that is working:
```
using (var reader = new MediaFoundationReader(testFilePath))
            {
                var availableMediaTypes = GetOutputMediaTypes(new Guid("0000f1ac-0000-0010-8000-00aa00389b71"))
                        .Where(mt => mt.SampleRate == reader.WaveFormat.SampleRate && mt.ChannelCount == reader.WaveFormat.Channels && mt.MediaType.BitsPerSample == reader.WaveFormat.BitsPerSample)
                        .Select(mt => new { MediaType = mt })
                        .OrderByDescending(mt => mt.MediaType.BitsPerSample)
                        .Select(mt => mt.MediaType);

                var mediaType = availableMediaTypes.FirstOrDefault();
                if (mediaType == null) throw new InvalidOperationException("No suitable FLAC encoders available");

                var outputFlac = Path.Combine(outputFolder, "baz.flac");

                using (var encoder = new MediaFoundationEncoder(mediaType))
                {
                    encoder.Encode(outputFlac, reader);
                }
            }
```

Maybe this could help someone in the near future who is facing the same problem.

Here's the code example I created:

```
var flacInputPath = Path.Combine(outputFolder, "_input.flac");

using (var reader = new MediaFoundationReader(flacInputPath))
{
	var outFormat = new WaveFormat(44100, reader.WaveFormat.Channels);

	using (var resampler = new MediaFoundationResampler(reader, outFormat))
	{
		WaveFileWriter.CreateWaveFile(outputWaveFilePath, resampler);
	}
}            

using (var flacReader = new MediaFoundationReader(flacInputPath))
{
	using (var reader = new MediaFoundationReader(testFilePath))
	{
		var outputFlac = Path.Combine(outputFolder, "baz.flac");
		var mediaType = new MediaType(flacReader.WaveFormat);
		MediaFoundationEncoder enc = new MediaFoundationEncoder(mediaType);
		enc.Encode(outputFlac, reader);
	}
}
```

Thank you in advance!

**Comment by jasonxz** [comment]
@datoml Would you mind sharing the code you used to read the Transform properties?

**Comment by datoml** [comment]
> @datoml Would you mind sharing the code you used to read the Transform properties?

I searched again the implementation and it seems that I had made the export in CPP and then call it using a "wrapper" in C#.
But I don't know exactly why I did it that way.
