### ISSUE TITLE
How to  change  record stream volume?

### ISSUE THREAD

**Issue by laoyebisheng** [naudio/NAudio#310]
hi,
I am learning NAudio.When I follow your tutorials   [http://markheath.net/post/how-to-record-and-play-audio-at-same](url)  ，I find can't control the record stream volume. If I want to  set an stream object volume =0,then it will  make other as the same sound card  stream object  volume can't hear.
`private void RecorderOnDataAvailable1(object sender, WaveInEventArgs waveInEventArgs)`
`{`
	`bufferedWaveProvider1.AddSamples(waveInEventArgs.Buffer, 0, waveInEventArgs.BytesRecorded);`
`}`

` private void RecorderOnDataAvailable2(object sender, WaveInEventArgs waveInEventArgs)`
`{`
	`bufferedWaveProvider2.AddSamples(waveInEventArgs.Buffer, 0, waveInEventArgs.BytesRecorded);`
`}`

`private void Record_Click(object sender, EventArgs e)`
{
	/*1*/
	`recorder1 = new WaveIn();`
	`recorder1.DeviceNumber = 0;`
	`recorder1.DataAvailable +=  RecorderOnDataAvailable1;`
	`bufferedWaveProvider1 = new BufferedWaveProvider(recorder1.WaveFormat);`
	`player1 = new WaveOut();`
	`player1.DeviceNumber = 0;`
	`player1.Init(bufferedWaveProvider1);`
	`player1.Play();`
	`recorder1.StartRecording();`
	/*2*/
	`recorder2 = new WaveIn();`
	`recorder2.DeviceNumber = 1;`
	`recorder2.DataAvailable +=  RecorderOnDataAvailable2;`
	`bufferedWaveProvider2= new BufferedWaveProvider(recorder2.WaveFormat);`
	`player2 = new WaveOut();`
	`player2.DeviceNumber = 0;`
	`player2.Init(bufferedWaveProvider2);`
	`player2.Play();`
	`recorder2.StartRecording();`
`}`
When I set  `player1.Volume=0`  , I  can't hear player2 stream.
please tell me how to change my code can hear player2 stream. 
thank you!

**Comment by markheath** [comment]
You need to set up a signal chain that lets you adjust volume. An easy way is to do `bufferedWaveProvider1.ToSampleProvider()` and then pass that into a `VolumeSampleProvider` that you can use to adjust the volume of just that stream of audio. Pass the `VolumeSampleProvider` into `player1.Init`
