### ISSUE TITLE
WaveFileWriter Produces Very Large (~3GB or More) Output

### ISSUE THREAD

**Issue by R030t1** [naudio/NAudio#311]
After recording, the console window will not exit. It seems like WaveFileWriter continues to write data until the console is manually closed.

The sound is reproduced accurately, but after the initial samples there is no output for many hours.

```C#
using System;
using System.Linq;
using NAudio.Wave;

namespace MicrophoneTest
{
    class Program
    {
        static WaveInEvent source = new WaveInEvent();
        static BufferedWaveProvider bwp = new BufferedWaveProvider(source.WaveFormat);

        static void Main(string[] args)
        {
            source.DataAvailable += OnDataAvailable;
            source.StartRecording();

            Console.ReadLine();
            source.StopRecording();
            WaveFileWriter.CreateWaveFile("out.wav", bwp);
        }

        static void OnDataAvailable(object sender, WaveInEventArgs wiea)
        {
            bwp.AddSamples(wiea.Buffer.ToArray(), 0, wiea.BytesRecorded);
            Console.WriteLine(".");
        }
    }
}

```

**Comment by R030t1** [comment]
Unfortunately the recommended examples may not work for the processing I want to do. It would be best if I can keep the waveform in memory indefinitely. Are there any types in NAudio that might help? `BufferedWaveProvider` seemed the most obvious (I sincerely think either the name or operation of the class should be changed), and I assumed it was backed by a growing memory structure. Since there is a fixed size of 5 seconds, I do not see the point in calling the buffer endless.

Setting `BufferedWaveProvider.ReadFully = false` prevents overreading. I am not sure a default of true for this value makes sense. If blank audio is meant to be processed, it will be put into the buffer intentionally.

**Comment by markheath** [comment]
In that case just write to a `MemoryStream` instead of a `WaveFileWriter` (although remember you will use a *lot* of memory if you record for more than a minute or so). `BufferedWaveProvider` is not a good fit for this scenario. Later, you can pass the `MemoryStream` to a `RawSourceWaveStream` in order to get something you can play with NAudio or write to a WAV file
