### ISSUE TITLE
Live G.722.1 audio stream

### ISSUE THREAD

**Issue by mixandmatch025** [naudio/NAudio#314]
I'm trying to use NAudio to playback a live audio stream.
This stream needs to be decoded (G.722.1) and resampled (perhaps, I'm not sure if NAudio automatically resamples to fit the speaker's needed sample rate).

Do you have any pointers to help me set this up?

**Comment by markheath** [comment]
the best place to look is in the network chat demo of NAudio.
what you do is receive a packet of compressed audio over the network, decode it (NAudio actually has a managed G.722 codec) and then put the decoded bytes into a `BufferedWaveProvider`. 
If you use `WaveOutEvent` then you won't need to do any manual resampling - the soundcard drivers take care of that for you so playing 16kHz mono will be fine.

**Comment by mixandmatch025** [comment]
From what I understand G.722.1 works at a different bit rate than G.722, though I have yet to find a .NET library which implements it.
Does `BufferedWaveProvider` works as a jitter buffer?

> the soundcard drivers take care of that for you so playing 16kHz mono will be fine.

Does this require any particular soundcard driver/manual configuration?

**Comment by markheath** [comment]
I'm not familiar with the details of the difference between G.722.1 and G.722 I'm afraid.
`BufferedWaveProvider` lets you queue up audio to be played as you receive it, and plays silence if nothing is queued.
`WaveOutEvent` uses the events callback mechanism and seems to be generally more reliable. But the same is true of `WaveOut` - it should just play 16kHz mono without any issues - no special setup required.

**Comment by mixandmatch025** [comment]
Does this automatic resampling work for every given sample rate?

**Comment by markheath** [comment]
You wouldnt use it as an arbitrary rate resampler, but yes you can play all the common sample rates 8kHz, 16kHz, 22kHz etc with it. I'm pretty sure G.722.1 can only be 16kHz (or maybe 32kHz). 

It's easy enough to try anyway. Just create some audio with `SignalGenerator` at any sample rate you like and try to play it.

**Comment by mixandmatch025** [comment]
Okay, got everything up and running.
Thank you very much for your help.
