### ISSUE TITLE
Crossfade at the end of the loop of audio file

### ISSUE THREAD

**Issue by SR-TheCodingGenius** [naudio/NAudio#316]
Hi,
In WASAPI Exclusive mode, I wanted to crossfade the audio file while it is looping in a selected region, where the audio has to fadeout before it reaches the end the region and fades in when it gets looped back, 
so that no click gets generated, 
My question is when an music file is looped in a region how this can be achieved  using a single audio object, because WASAPI (Exclusive mode) doesn't allows another audio object to be created

**Comment by markheath** [comment]
WASAPI exclusive mode means only one application can open the device - that's not a limitation of NAudio.

The way to get what you want is to implement your own custom `ISampleProvider` that fades in and out the audio as it loops and use that to feed the output device. I'm afraid there isn't a ready-made class in NAudio that does that, but you could use the `FadeInOutSampleProvider` code as inspiration for how to write your own version of this.
