### ISSUE TITLE
WaveFileWriter - higher bit depth

### ISSUE THREAD

**Issue by TheMates** [naudio/NAudio#317]
Hi,
I don't know, if I'm right, but I think, that in the WaveFileWriter.cs, methods WireteSample, WriteSamples, event if there is an option to output 16, 24 and 32bit WAVE files, the samples itself are passed as short or float, both having only 16bit precision. I mean, can you actually reach the 24 or 32bit resolution in the output file?

I don't think, I can offer a solution, because I'm not experienced enough, but I think maybe an overload for the WriteSample(s) functions, that accepts a double variable would do.

**Comment by markheath** [comment]
`WaveFileWriter.Write` accepts a byte array with audio formatted however you want - supporting 16,24 and 32 bit as well as compressed formats. The `WriteSamples` method attempts to convert the passed in samples to whatever bit depth your WAV file is using. That also supports 16,24 and 32 bit.

Also, float doesn't have 16 bit precision. Float is 32 bit.

**Comment by TheMates** [comment]
True, don't know why I thought float was 16bit. My bad, sorry.
