### ISSUE TITLE
future cooperation

### ISSUE THREAD

**Issue by Leoon111** [naudio/NAudio#318]
Hello! I'm now starting to write a program to select your favorite music. Now I'm studying your achievements. They will help me a lot in understanding the work with audio files. The idea of ​​how I implement this already exists, and it is good. I have a desire to contact you when the draft version of the program is ready, so that specifically you look at whether I understand the work of your program accurately.
P.S. At the moment, not one service for selecting music according to preferences does not know how to select music normally for those records that are nryatsya. He does not know how to analyze music. I know how to do this. How to make an analysis of audio recordings for further selection of other musical compositions from this analysis.

**Comment by markheath** [comment]
I'm not sure I fully understand your question. NAudio will allow you to access the raw sample data for many common audio files. From that you can perform any analysis you want, but you would need to write the signal processing code to do that yourself.

**Comment by Leoon111** [comment]
Yes everything is correct. The signal handler is developed by me, I know how it will work. It remains for me to understand your code. Understand the work of the program. This proposal on cooperation, how it will work, I will write to you here.
