### ISSUE TITLE
Naudio Popping, clicking, skipping, jumping, spluttering

### ISSUE THREAD

**Issue by ricci07** [naudio/NAudio#32]
I am using Naudio primarily to play sounds simultaneously. Problem is that Naudio make the .wav play with pops and clicks. (Random, sometimes it doesn't "sometimes" being rare)

Is there anyway to fix this?

Public Class NAudioPlayer

    Private wfr As WaveFileReader
    Private wc As WaveChannel32
    Private dso As DirectSoundOut

    Public Sub New(ByVal soundFile As String)
        wfr = New WaveFileReader(soundFile)
        wc = New WaveChannel32(wfr)
        dso = New DirectSoundOut
        dso.Init(wc)
    End Sub

    Public Property Volume() As Double

        Get
            Return wc.Volume
        End Get
        Set(value As Double)
            wc.Volume = value
        End Set

    End Property
  
    Public Sub play(ByVal fromBeggining As Boolean)

        If fromBeggining Then
            wc.Seek(0, SeekOrigin.Begin)
        End If

        dso.Play()
    End Sub

    Public Sub StopSound()
        dso.Stop()
    End Sub

    Public Sub Pause()
        dso.Pause()
    End Sub
End Class

**Comment by markheath** [comment]
See if another wave player like `WaveOutEvent` gives better results. Another option is to keep just one player open and mix all the audio in using a "fire and forget strategy". Pops can be due to suddenly starting or stopping, or dropouts due to performance issues.
