### ISSUE TITLE
Discrepency in BlockAlign and BitsPerSample?

### ISSUE THREAD

**Issue by TechnologyDude** [naudio/NAudio#321]
I have a WAV file which is 16-bit, 48000Hz, 2 channels.  If I examine the WAV header with a HEX editor, it shows that the Block Align is 4.  Using NAudio as follows, the reader.WaveFormat.BlockAlign is reporting 8 instead of 4, and the reader.WaveFormat.BitsPerSample is reporting 32.

```
using (var reader = new AudioFileReader(filename))
{
      var y= reader.WaveFormat.Channels * (reader.WaveFormat.BitsPerSample / 8);
      var x = reader.WaveFormat.BlockAlign;
```

I'm not quite sure I understand why NAudio is reporting these values.

**Comment by markheath** [comment]
It's because `AudioFileReader` converts to IEEE float, so `BlockAlign` is now `2 x sizeof(float)`

Use `WaveFileReader` if you don't want the conversion.
