### ISSUE TITLE
Can't use StreamMediaFoundationReader

### ISSUE THREAD

**Issue by Jin-K** [naudio/NAudio#325]
Hello, I'm trying without success to play the following web stream url: 
http://65.60.45.74:8072/;stream.mp3 (codec: MPEG AAC Audio / mp4a).

I tried it with StreamMediaFoundationReader but it looks like it's supposed to work with filestreams (or I really don't understeand how it should be used).

My code that worked best so far is the following:

    using (var webStream = WebRequest.Create( url ).GetResponse().GetResponseStream()) {
        var ms = new MemoryStream();

        new Task( () => {
          byte[] buffer = new byte[4096];
          for (int read;  (read = webStream.Read(buffer, 0, buffer.Length)) > 0;)
            ms.Write( buffer, 0, read );
        } ).Start();

        using (var streamMFReader = new StreamMediaFoundationReader( ms ))
        using(WaveOut waveOut = new WaveOut( WaveCallbackInfo.FunctionCallback() )) {
          waveOut.Init( streamMFReader );
          waveOut.Play();
          while (waveOut.PlaybackState == PlaybackState.Playing)
            Thread.Sleep( 100 );
        }
      }

But it works about ~60 seconds before crashing (problem in WaveOutBuffer.OnDone() I think ==> 0 bytes read).

I know my code is destined to crash: 
- "ms" is used in different threads, 
- streamMFReader's properties don't update correctly (CurrentTime becomes higher than TotalLength)
- and a lot of other reasons

But how should I use this class ? Should I try to create a class (inheriting StreamMediaFoundationReader) that allows read/write/seek in a stream implement "IStream" ?

I also tried to use a similar mechanism as the "MP3StreamingDemo" demo project (using a BufferedWaveProvider, one thread adding samples and another playing), but I can't "AddSamples" with my "StreamMediaFoundationReader" object.

**Comment by markheath** [comment]
Often you can play from a URL directly with `MediaFoundationReader` although in this case it doesn't seem to work. And so I don't think `StreamMediaFoundationReader` would help you even if you could use it (you'd just use the webStream directly, without introducing a MemoryStream).

If you use the MP3 streaming demo approach, you should not be using `StreamMediaFoundationReader`. In that example, the MP3 frames are being converted using ACM and then passed as PCM into the `BufferedWaveProvider`

**Comment by Jin-K** [comment]
Ok I see.

Do you think I shouldn't use MediaFoundation ?
I ask it because I just started reading this book:
https://blogs.msdn.microsoft.com/microsoft_press/2011/12/20/new-book-developing-microsoft-media-foundation-applications/ 😆 

Or, I don't know if it is possible, should I look for a way to decompress mpeg aac stream (instead of mp3) and pass it to a BufferedWaveProvider ?

**Comment by markheath** [comment]
MediaFoundation has the capabilities to do the decoding you need, but I think it requires a lower-level access to the Media Foundation Transforms themselves which is quite a bit of code to write, and NAudio doesn't yet have support for doing that (we only do it in the case of resampling)
