### ISSUE TITLE
Mix multiple pcm data

### ISSUE THREAD

**Issue by kfbzhenggy** [naudio/NAudio#326]
I have  five  realtime  pcm stream with a same fixed format  received from the network , you may think this is five people  talk to each other at the same time .

eg : 
Five People : A ,B ,C,D,E

When i received audio stream from ABCDE, then i need to send BCDE to A , and ABCD to E, so BCDE or ABCD need to be mixed , i need a mix algorithm , how to do this?

I would use c++ to implement it ,because of  the stream is received very fast (Frame/4ms).

**Comment by markheath** [comment]
NAudio is a C# library, so if you want to use C++ you should use something else.
But in NAudio, you'd create a `BufferedWaveProvider`, one for each person, convert each to an `ISampleProvider` with the `ToSampleProvider` extension method, and then mix them with the `MixingSampleProvider`
