### ISSUE TITLE
Bug in Demo: Audio File Playback

### ISSUE THREAD

**Issue by Mnaukal** [naudio/NAudio#328]
I found a bug in Audio File Playback demo. When allowing user to select output device, you first fill the combo boxes with available devices from index -1. But then when selecting the device, you return SelectedIndex property of the combo box. This means that the numbers are shifted by 1. For exaple if I select the first item in the combo box, the SelectedIndex will be 0, but deviceId of this device should be -1.

I think this happens in all the files NAudioDemo/AudioPlaybackDemo/*SettingsPanel.cs

**Comment by markheath** [comment]
thanks for reporting, I'll get this fixed

**Comment by markheath** [comment]
this is now fixed in the latest code and will be part of the next release
