### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by Mnaukal** [naudio/NAudio#329]
The documentation says:

> Once you've selected the device you want, you can open it by passing the device number into the `WaveOut `or `WaveOutEvent `constructor:
>` var outputDevice = new WaveOutEvent(deviceNumber);`

but WaveOutEvent does not contain a constructor, that would take one parameter. 

The workaround I found is:

``` recorder = new WaveInEvent() { DeviceNumber = 1 };```

**Comment by markheath** [comment]
thanks, have fixed this
