### ISSUE TITLE
Playing memory stream with text "Third Activation" over DirectSoundOut plays a weird sound at the end of playback

### ISSUE THREAD

**Issue by dhilipswaminathan** [naudio/NAudio#331]
I am trying to play memory stream of data through DirectSoundOut. Everything works fine. but i am hearing unwanted "beep" sound at the end of playback. If I try to play "First Activation", "Second Activation" and "Third Activation" . The issue happens only with "Third Activation". Something to do with this text. Any help would be appreciated. 

Here is the code

 /// <summary>
        /// Plays the audio stream.
        /// </summary>
        /// <param name="player">The player.</param>
        public bool TransmitAudio(MemoryStream audioStream)
        {            
            IWavePlayer waveOut = CreateWaveOut(_audioDeviceGuid);

            waveOut.PlaybackStopped += _playBackStopped;

            ISampleProvider sampleProvider = CreateInputStream(audioStream);

            //Initialize the WavePlayer
            waveOut.Init(sampleProvider);

            //Play audio
            waveOut.Play();

            _interfaceResetEvent.WaitOne();

            //Reset the manual reset event
            _interfaceResetEvent.Reset();

            //Return true
            return true;
        }

**Comment by markheath** [comment]
I'm afraid I don't understand how the text "third activation" relates to the code you have shown.
