### ISSUE TITLE
Error: NoDriver calling acmFormatSuggest when do wave re-sampling using NAudio.

### ISSUE THREAD

**Issue by hepower** [naudio/NAudio#336]
Hi NAudio expert, 

Thanks for providing such a good tool for us. :)
I use NAudio to covert a wav file to PCM16 and do re-sampling with below code:

`if (filename.EndsWith("wav"))

                {
                    using (var reader = new WaveFileReader(new MemoryStream(audio)))
                    using (var converter = WaveFormatConversionStream.CreatePcmStream(reader))
                    {
                        if (outSampleRate == -1)
                        {
                            if (reader.WaveFormat.SampleRate >= 16000)
                            {
                                outSampleRate = 16000;
                            }
                            else
                            {
                                outSampleRate = 8000;
                            }
                        }
                        outMilliSeconds = reader.TotalTime.TotalMilliseconds;
                        using (var sampler = new WaveFormatConversionStream(new WaveFormat(outSampleRate, 1), converter))
                        {
                            string tempPath = Path.GetTempPath();
                            string tmpFile = Guid.NewGuid().ToString("n").Substring(0, 8) + filename.Substring(Math.Max(filename.Length - 10, 0));
                            string tmpFileFullPath = Path.Combine(tempPath, tmpFile);
                            WaveFileWriter.CreateWaveFile(tmpFileFullPath, sampler);
                            var bytes = File.ReadAllBytes(tmpFileFullPath);
                            File.Delete(tmpFileFullPath);
                            return bytes;
                        }
                    }
                }
                else
                {
                    throw new Exception("Unknown audio format. Support wav file only!");
                }`

But it reported a error:
NoDriver calling acmFormatSuggest

It works in 1 windows PC, but with this error in other windows PC.

Src format is pcm_alaw 8000 s16
Target format is PCM 16000 S16LE

Do you have any suggestions?

Thank you very much!

**Comment by markheath** [comment]
You can't typically make that jump in one go with ACM codecs. Go from alaw 8kHz to PCM 8kHz. And then from 8kHz to 16kHz.
