### ISSUE TITLE
WaveOut and WaveOutEvent don't read the actual volume

### ISSUE THREAD

**Issue by neilt6** [naudio/NAudio#342]
`WaveOut.Volume` and `WaveOutEvent.Volume` both return a cached volume level instead of retrieving it from the system. As a result, volume changes made using the Settings app on Windows 10 v1803 can't be detected and respected.

I propose adding the following method to `WaveOut` and using it in `WaveOut.Volume` and `WaveOutEvent.Volume` to read the actual app volume instead of returning a cached value:

```
internal static float GetWaveOutVolume(IntPtr hWaveOut, object lockObject)
{
	int stereoVolume;
	MmResult result;
	lock (lockObject)
	{
		result = WaveInterop.waveOutGetVolume(hWaveOut, out stereoVolume);
	}
	MmException.Try(result, "waveOutGetVolume");
	return (stereoVolume & 0xFFFF) / (float)0xFFFF;
}
```

**Comment by neilt6** [comment]
@markheath Would you mind commenting on this proposal? If you're in favour of these changes I can prepare a pull-request.

**Comment by markheath** [comment]
yes, makes sense. I'd obsoleted volume, but changed my mind, and so the Volume property comment should say something like Device Volume
