### ISSUE TITLE
WaveIn, WaveInEvent, and startup lag

### ISSUE THREAD

**Issue by ulatekh** [naudio/NAudio#344]
I'm trying to write a simple C# app that reads audio from the microphone and streams it as UDP packets.
I'm basing my code on the RecordingPanel demo.

I noticed that there's quite a bit of lag between clicking the "Start recording" button and the actual start of recording. It appears most of the time is spent in the waveInOpen() call. Rearranging the code so that waveInOpen() is only called once (i.e. when the WaveIn or WaveInEvent object is created) takes care of the lag.

My modification to get rid of start-recording lag is simple.

In WaveInEvent.cs (and presumably, WaveIn.cs):
1) Rewrite the WaveFormat property to use a private _waveFormat field. get returns that field, and set sets the field from the incoming value and calls OpenWaveInDevice().
2) Remove the call to OpenWaveInDevice() from StartRecording().

And in RecordingPanel.cs:
1) Only recreate waveIn when the settings change.
2) Change the call to Cleanup() in RecordingPanel.OnRecordingStopped() to just dispose of writer, i.e. not waveIn.

So far, it "seems to work", but I know that means little.
Is there some reason that WaveIn and WaveInEvent are written to call waveInOpen() every time recording starts? It seems like it'd only need to be called after the WaveFormat property changes.

**Comment by markheath** [comment]
You can always just call StartRecording once, but then only send the audio over UDP if you actually want to stream. This is the way a lot of recording apps work - they are constantly monitoring the soundcard, so when you actually press the record button, it just sets a flag that causes the received audio to get written to disk.

**Comment by ulatekh** [comment]
Well, that'd certainly be a workaround, but I'd rather not have the recording active unless I need it, e.g. to help preserve battery life.

I can continue to use my modified version (in the vs2010 branch of my fork) and report if I find any problems with it. I was just wondering if there was any reason why my method wouldn't work in general for audio devices.
