### ISSUE TITLE
Different results AudioFileReader vs WaveFileReader?

### ISSUE THREAD

**Issue by Meekohi** [naudio/NAudio#346]
Simple test program.
```
            byte[] samples;
            using (WaveFileReader reader = new WaveFileReader(files[selection - 1]))
            {
                samples = new byte[reader.Length];
                while (reader.Position + 4096 < reader.Length)
                {
                    reader.Read(samples, 0, 4096);
                    Console.Write("{0}\n", samples[0]);
                }
            }
```
This works correctly on a simple `test.wav` file. If I switch the `WaveFileReader` to `AudioFileReader`, it prints all zeros instead. Maybe I am misunderstanding how it is meant to be used, but this seems like unexpected behavior -- shouldn't `AudioFileReader` just be an abstraction so I can also read mp3s and etc?

**Comment by markheath** [comment]
`AudioFileReader` converts to IEEE floating point samples, so no, you wouldn't expect to see the same results.

**Comment by Meekohi** [comment]
Ah so the standard flow would be to call `rawBytes = AudioFileReader.Read(...)` and then some `floatSamples = ConvertByetsToFloat(rawBytes)` (?) right after?

**Comment by markheath** [comment]
you can read directly into a float[] with AudioFileReader as it implements ISampleProvider

**Comment by Meekohi** [comment]
Got it. Thanks!
