### ISSUE TITLE
WAV Local Driver and threads

### ISSUE THREAD

**Issue by pmiddleton** [naudio/NAudio#348]
@markheath  - I have run into an issue and am hoping you have some clarification for me.

I am using a 3rd party acm driver to convert wav files from the Dsp True Speech codec to PCM in a server environment.

I have found that I need to register the driver, via AcmDriver.AddLocalDriver, on each thread that is performing a conversion.  I can't just register it once globally.  

I can't find any backing documentation from Microsoft on the Audio Compression Manager to know if this is both the correct way to to use this driver and also thread safe.  

I have written a small test app and everything appears to be working, but I don't know if anything is going to come back to bite me.  Have you ever run into this issue and have any guidance?

Thanks

**Comment by markheath** [comment]
yes, it's annoying, but that's how AddLocalDriver works. It was years ago that I last used this, but I remember having to track which threads I'd added the driver on.

**Comment by pmiddleton** [comment]
Have you ever run into any upper limits on the number of threads that can be used simultaneously?  

I am planning on deploying this into an Azure webjob fired off by a QueueTrigger.   I will be therefore be  running on a threadpool thread I don't have control over and could be constantly running on a new thread.

**Comment by markheath** [comment]
hmm, I have a feeling I might have just removed the driver every time I finished a transcode to avoid ending up with hundreds of loaded copies. I'd have to dig out some very old code to remember exactly what I did/

**Comment by pmiddleton** [comment]
I will give that approach a try along with doing a LoadLibrary on the dll at startup to prevent the dll from popping in and out of memory during low load times.

Thanks for the help!
