### ISSUE TITLE
NullreferenceException in WaveIn.cs RaiseDataAvailible

### ISSUE THREAD

**Issue by Mrnikbobjeff** [naudio/NAudio#35]
Sometimes Naudio stops working when I record something, raising a NullreferenceException in WaveIn's RaiseDataAvailible function becuase it does not check wether the passed Argument is null. To fix this one only needs to add a null check, as I did in the pull request.

**Comment by markheath** [comment]
not sure exactly what you mean here. buffer has already been checked for null before `RaiseDataAvailable` is called. Also, which pull request are you referring to?
