### ISSUE TITLE
Get a video stream of MediaFoundationApi instance if available in addition to the audio?

### ISSUE THREAD

**Issue by SimonSimCity** [naudio/NAudio#36]
Even so this has very little to do with NAudio ... just leaving that question here:

By using the `MediaFoundationApi`, I am able to get the audio out of an MP4 file. Do you know if it's easy to also get the video, once I already have that handler to the file?

The use-case is, that I currently am working on a audio-cutting project, where I have multiple translations (available as WAVE files) that the user want to cut. I also have a video file, that just has to be synchronized with all these wave-files within my application. As this would've been the easiest way, and you already are in the system, I thought it's worth asking if there is an easy possibility to get the video :wink:

Another option for me would be to start up VLC and play it using the embeded player, but I guess it would be hard to keep them in sync.

**Comment by markheath** [comment]
I'm afraid that's not a part of the Media foundation API I am personally familiar with, but I believe its possible. Have a look at some to the Windows SDK sample projects for examples.

**Comment by SimonSimCity** [comment]
This was just a thought of mine during estimating a project. I now solved it by using VLC (Vlc.DotNet). That's enough for my customer for now. If someone wants to do the same, these samples may help him: https://github.com/ZeBobo5/Vlc.DotNet/tree/master/src/Samples

@markheath feel free to close this or close it by letting the programmers replace the instantiation of the `MediaFoundationReader` instance in the `AudioFileReader`. They may extend the `MediaFoundationReader` to their needs - or just fork the project and change the file directly. They anyways then will have to adjust if that file changes. :wink:
