### ISSUE TITLE
Will the Vorbis Codec be Ported Over?

### ISSUE THREAD

**Issue by Mosely** [naudio/NAudio#37]
Hi there!  I see that there's Vorbis decoding capabilities, so I'm a bit curious as to whether Vorbis encoding will eventually be provided or even an entire port of the Vorbis codec.  I think libvorbis is BSD licensed, so it should be okay, right?

Great library, by the way.

**Comment by markheath** [comment]
Take a look at [NAudio.Vorbis](https://github.com/naudio/Vorbis) which integrates NAudio with the [NVorbis project](https://github.com/ioctlLR/NVorbis).

**Comment by Mosely** [comment]
Cool, thanks for the info.  I see that NVorbis doesn't support encoding, either, but since that library exists, I'll ask its owner to see if this functionality will be implemented.
