### ISSUE TITLE
ISampleProvider from WaveFileReader

### ISSUE THREAD

**Issue by mleenhardt** [naudio/NAudio#38]
Hey,

I was wondering if there was a way to get a `ISampleProvider` from a `WaveFileReader` whose `WaveFormat` is `WaveFormatEncoding.Extensible`? The wav file itself is 16bits, 44 kHZ 4 channels and it seems that `SampleProviderConverters` is only able to provde `ISampleProvider` for Pcm and IeeeFloat encodings.

I've also attempted to use `WaveFormatConversionStream` to convert the file and get a Pcm encoding but I'm getting an 'AcmNotPossible calling acmStreamOpen' exception. I understand this is related to the fact that the codec that can perform this conversion doesn't exist on my machine but I'm haven't been able to find one that can convert from 4 channels wav file in those which are listed by the NAudio demo app.

**Comment by markheath** [comment]
you could use a `RawSourceWaveStream` and set the `WaveFormat` to what it really is. No conversion stream should be necessary.
