### ISSUE TITLE
DeviceID somehow changed during c# script is running

### ISSUE THREAD

**Issue by Filgaja** [naudio/NAudio#391]
I have an issue i do not understand.

I wrote a bot for twitch and it plays sounds in stream by waveout to my audio device "Vac - Soundbar"
When i start the bot it is always the device id 2 like in following script:

```
WaveStream waveStream = new Mp3FileReader($"{Environment.CurrentDirectory}/Sounds/{s}.mp3");
//var waveOut = new WaveOut { DeviceNumber = MainWindow.ComboBox.SelectedIndex - 1 };
var waveOut = new WaveOut { DeviceNumber = 2 };
waveOut.Init(waveStream);
waveOut.Play();
```

it works like a charm for a while. but somehow after a while the bot starts to waveout on a different sounddevice and not on "Vac - Soundbar" anymore untill i restart the bot.

Is there a way to use audio device name in naudio instead of using id?

Somthing like:

```
WaveStream waveStream = new Mp3FileReader($"{Environment.CurrentDirectory}/Sounds/{s}.mp3");
var waveOut = new WaveOut { DeviceNamer = "Vac - Soundbar" };
waveOut.Init(waveStream);
waveOut.Play();
```

Would be nice if someone can share theyr knowledge.
Anyone has simular problems while your tool is running longer? Any idea what cause this issue?

Regards

**Comment by Filgaja** [comment]
Seems i managed it with directout instead of waveout

```
                    foreach (var dev in DirectSoundOut.Devices)
                    {
                        if (dev.Description == "3 - VAC - Soundbar (Virtual Audio Cable)")
                        {
                            WaveStream waveStream = new Mp3FileReader($"{Environment.CurrentDirectory}/Sounds/{s}.mp3");
                            waveOutDevice = new DirectSoundOut(dev.Guid, 100);
                            waveOutDevice.Init(waveStream);
                            waveOutDevice.Play();
                        }
                    }
```
Works like a charm and it only output on the correct device

**Comment by markheath** [comment]
great, glad you found a solution
