### ISSUE TITLE
Problem Converting WAV file with more than 2 channels to MP3

### ISSUE THREAD

**Issue by MartinHarran** [naudio/NAudio#392]
Hi

I am developing an application that records streaming audio to a wav using NAudio and then creates an mp3 version but my sound system is 5.1 and I am running into a problem doing the mp3 conversion due to the number of channels in the wav file.

When I use LameMP3FileWriter I get an “Unsupported number of channels 6” error ; when I use MediaFoundationEncoder.EncodeToMp3, I  get a “No suitable MP3 encoders available” but the issue is again the number of channels as both conversions work fine when I set my sound system to stereo.

This is a bit of a pain; firstly, it means I cannot use my 5.1 system when recording the music but more of an issue, for some reason that I cannot figure out, if I set my speakers to stereo, they revert to quadraphonic when the PC is rebooted!

Have you any suggestions as to how I can get around this? I’m guessing that I will have to do something like resampling the wav file to 2 channels before the conversion but I’m hoping there is something simpler than that.

**Comment by markheath** [comment]
Sorry, I'm not aware of any way to work around this other than to convert the WAV to stereo before converting it.

**Comment by MartinHarran** [comment]
Thanks, Mark, I more or less expected that but hope springs eternal :)
