### ISSUE TITLE
Cannot Create Mp3Frame With Zero Bytes

### ISSUE THREAD

**Issue by Mehranh** [naudio/NAudio#394]
I want to create some silence bits and create a mp3 file.

it's very stupid that  removes the zero bytes.

```
var silenceBytes = new byte[1118880];
                for (int i = 0; i < silenceBytes.Length; i++)
                {
                    silenceBytes[i] = 0;
                }
       var mp3Stream = new MemoryStream(silenceBytes);
     var readFullyStream = new ReadFullyStream(mp3Stream);
 var frame = Mp3Frame.LoadFromStream(readFullyStream);
```
in this code frame is null !!

How can i fix it.
thanks

**Comment by markheath** [comment]
MP3 is not like PCM - you can't generate silence simply by creating an array of zeroes. For `LoadFromStream` to work, you need a properly formatted MP3 frame. It's possible that there's a well-known pattern for generating a silence MP3 frame, but I don't know what it is. One way to discover this would be encode a silent WAV to MP3 and examine one of the frames.
