### ISSUE TITLE
Cross-fade the Audio file with itself

### ISSUE THREAD

**Issue by SR-TheCodingGenius** [naudio/NAudio#397]
I Have a scenario where I have play few audio sources simultaneously through a mixer, which I'm doing currently, only one audio file can be heard while others have their volumes set to zero, so when I select a portion of the audio file with full volume , and loop it, I need to crossfade the audio file with itself , that is the end-part of the selected portion crossfade with begining part of it. Is this can be possible? when the audio player is configured in WASAPI Exclusive mode or ASIO mode.

If possible please suggest some options

**Comment by markheath** [comment]
it's possible, but not easily built out of the built-in components. I'd probably make a custom `ISampleProvider` called `CrossFadingLoopSampleProvider` which saved the first and last x milliseconds of audio in memory so that it could mix it together itself during the crossfade portion.

**Comment by markheath** [comment]
Well it depends a little bit on exactly what your requirements are, but essentially, let's say that the crossover is 500ms, you'd have two float[] into which you'd read the two portions of audio to be cross-faded. Then you can mix them by summing them together with a multiplier.

Here's a very simplistic approach to crossfading two buffers into a third

```
for(int n = 0; n < sampleCount; n++)
{
    var amount = ((float)n)/sampleCount;
    crossfade[n] = fadeInBuffer[n] * amount + fadeOutBuffer[n] * (1.0f - amount);
}
```

The `Read` method would then need to either return parts of the crossfade (keeping track of how far through it was), or return audio from the file.

And for better optimization, you would only perform the amount of the crossfade you needed on demand.

Sorry I don't have time at the moment to do a full implementation, but hopefully that points you in the right direction

**Comment by SR-TheCodingGenius** [comment]
Hi, 
That worked for me, but there one more issue, when the region is under loop I'm moving the audio player to the beginning of the region when it reaches end, by doing so, it produces a  click for audio files with multiple frequencies, can you give some suggestion to do this without clicks.

Note- can't create two play positions as it needs to work for Waveout, WASAPI exclisve and ASIO modes.
