### ISSUE TITLE
LoopStream does not loop

### ISSUE THREAD

**Issue by tramanz** [naudio/NAudio#408]
Hi! I'm trying to reproduce an audio file as an infinite loop using the class LoopStream present in the demo folder, but this does not seem to work at all.  In fact, the file is reproduced only the first time and then only silence can be heard. In my code, I simply read the audio file (format .m4a, but I tried also with .wav with the same results) with the AudioFileReader class, pass it to a LoopStream which feeds a WaveOutEvent instance. This is the code:

> var reader = new AudioFileReader(soundfieldFilePath);
> var loop = new LoopStream(reader);
> player = new WaveOutEvent();
> player.Init(loop);
> player.Play();

 I followed precisely the instructions given in the demo, so I can't figure out where is the problem. Thanks to anyone who will help!

**Comment by markheath** [comment]
Do you get a `PlaybackStopped` event? Also try putting a breakpoint in the `LoopStream` code to the place where it sets `Position = 0` to check that is getting called

**Comment by tramanz** [comment]
Yes, I get a PlaybackStopped event and, if I leave uncommented the following lines in the Read method of the LoopStream class, it fires immediately and the audio file is never played:

> if (sourceStream.Position >= sourceStream.Length)
>     sourceStream.Position = 0;

Instead, if I comment them, the audio file is played only once. In any case, following your suggestion, the sourceStream.Position is never modified.

**Comment by markheath** [comment]
OK, instead of that check, can you do the rewind if the Read method from sourceStream returns 0.

**Comment by tramanz** [comment]
I tried also this but the Position property is again never modified. The whole Read method code is the following:

> public override int Read(byte[] buffer, int offset, int count)
> {
>    int read = 0;
>    while (read < count)
>    {
>       int required = count - read;
>       int readThisTime = sourceStream.Read(buffer, offset + read, required);
>       if (readThisTime == 0 || readThisTime < required)
>          sourceStream.Position = 0;
>       read += readThisTime;
>       }
>   return read;
>   }

To give some insights, when the execution enters the while block for the first time, count = required readThisTime = 57600. So every time this block is executed only once because it is always read = count after the first execution of the block and it is never readThisTime == 0 or readThisTime < required.

**Comment by markheath** [comment]
That's very strange indeed. But you said that you were getting a `PlaybackStopped` event which can only happen if `Read` returns 0 at some point. Does this still not work if you are looping a WAV file?

**Comment by tramanz** [comment]
I can confirm that with the .m4a file the Position is never updated and the reproduction happens only once. At the end of it, the PlaybackStopped event is raised. With the .wav file instead (I always used the AudioFileReader class), the reproduction does not happen at all and the event is raised immediately.

**Comment by tramanz** [comment]
With some patient debugging i found out that the Position property is actually modified when the Read method reaches the end of the file, but when it is set to zero the PlaybackStopped is immediately raised and the reproduction stops.

**Comment by markheath** [comment]
does LoopStream.Read ever return 0, or a number less than count?

Also check the PlaybackStopped event args for an exception - maybe there's a problem causing playback to fail

**Comment by tramanz** [comment]
Thank you very much Mark! I checked the Exception raised on the PlaybackStopped event and it turned out that there was a bug in an other part of my code which substantially nullified the AudioFileReader. I feel so dumb for this! Thank you again, both for your helpfulnees and your speed!

**Comment by markheath** [comment]
Great, glad we could get to the bottom of this!
