### ISSUE TITLE
Uriel Asio CreateMultiplexedStream

### ISSUE THREAD

**Issue by jimmybanegas93** [naudio/NAudio#411]
Hi Mark, I'm working on a project you helped to develop a few years ago. Currently we're using an Asio Focusrite which multiplexes two inputs with .wav files, I'm having issues with Memory Out Exception, I also would like to know if there's a more efficient way of creating a Multiplexed Stream given that I'm using 10 minutes files, it's kinda slow. What would you recommend? Thanks

**Comment by markheath** [comment]
Presumably you're loading the whole files into memory. You can multiplex on the fly, but for the best results in ASIO, you'd probably want to do so with custom code that prepares audio directly for the individual channel buffers, unlike the NAudio standard produced by the MultiplexingSampleProvider which is interleaved samples
