### ISSUE TITLE
Is there a discussion forum for NAudio?

### ISSUE THREAD

**Issue by tomb18** [naudio/NAudio#412]
Hi,
I was wondering if NAudio can do the following resampling:
I have a signal that is delivered in 16384 doubles at a sampling rate of 250kHz.  I would like to downsample this to 192kHz.  Is this possible?  If so, are the required lowpass filters included? Which function would do this?
Thanks, Tom

**Comment by markheath** [comment]
hi, check out my article on input driven resampling here.
https://www.markheath.net/post/input-driven-resampling-with-naudio-using-acm
Unfortunately, I don't think the ACM resampler does LPF

**Comment by tomb18** [comment]
HiOk, thank you.Best regards, Tom


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Mark Heath <notifications@github.com> Date: 2018-10-30  12:21 PM  (GMT-05:00) To: naudio/NAudio <NAudio@noreply.github.com> Cc: tomb18 <tomb18@videotron.ca>, Author <author@noreply.github.com> Subject: Re: [naudio/NAudio] Is there a discussion forum for NAudio? (#412) 
hi, check out my article on input driven resampling here.

https://www.markheath.net/post/input-driven-resampling-with-naudio-using-acm

Unfortunately, I don't think the ACM resampler does LPF

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/naudio/NAudio","title":"naudio/NAudio","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/naudio/NAudio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@markheath in #412: hi, check out my article on input driven resampling here.\r\nhttps://www.markheath.net/post/input-driven-resampling-with-naudio-using-acm\r\nUnfortunately, I don't think the ACM resampler does LPF"}],"action":{"name":"View Issue","url":"https://github.com/naudio/NAudio/issues/412#issuecomment-434367555"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/naudio/NAudio/issues/412#issuecomment-434367555",
"url": "https://github.com/naudio/NAudio/issues/412#issuecomment-434367555",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [naudio/NAudio] Is there a discussion forum for NAudio? (#412)",
"sections": [
{
"text": "",
"activityTitle": "**Mark Heath**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@markheath",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"naudio/NAudio\",\n\"issueId\": 412,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"naudio/NAudio\",\n\"issueId\": 412\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/naudio/NAudio/issues/412#issuecomment-434367555"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 401920664\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by saurabh-bagchi-mindteck** [comment]
Hi,

Is it possible to implement to play audio files using NAudio in C# 2.0 VS 2005 application? How to download a sample application where NAudio is used to implement using C# 2.0 in a VS 2005 platform? 

Thanks in advance for any support received

Regards,
Saurabh
