### ISSUE TITLE
Listen to this device

### ISSUE THREAD

**Issue by sassub** [naudio/NAudio#414]
Hi , 
I want to create a c# windows  application  that use Speakers & microphone at the same time in windows 7 or windows 10.
In found in windows 10 in my microphone proprieties in Listen tab is a checkbox  labelled Listen to this device.
Is there a possibility to check or uncheck  Listen to this device, or is there a possibility to make a c# application using naudio.

Regards 
Bogdan

**Comment by markheath** [comment]
It's not something I've attempted to do before. You'd need to explore WASAPI to find whether there is a way to programatically check Listen to this device. NAudio does have wrappers for quite a few bits of WASAPI, but not the whole thing.
