### ISSUE TITLE
Console app to instantaneously read midi commands via fader

### ISSUE THREAD

**Issue by tjahnks23** [naudio/NAudio#417]
Hello, I'd like to create a console app that instantaneously reads commands from a midi device. This device is not musical, it only sends note on/off or fader control changes. Is it even possible for this framework to handle fader events? Thanks!

**Comment by markheath** [comment]
Hi, have a try of the [MIDI in demo](https://github.com/naudio/NAudio/blob/master/NAudioDemo/MidiInDemo/MidiInPanel.cs) in the NAudio demo app and see if that meets your needs.

**Comment by tjahnks23** [comment]
I created my own Windows form app that reads input from an Akai APC20 and sends to my lighting program, Daslight. This lighting program can accept input from any midi device, however, it did not behave how I wanted it to. I even purchased Bome Midi Translator Pro and after many months of experimenting and using live at shows - this translator was too difficult to use and configure. Anyways, if you or anyone sees this and is interested in the Windows form app that translates MIDI, let me know.
