### ISSUE TITLE
I can not determine when NAUDIO has finished playing

### ISSUE THREAD

**Issue by AAN3AC** [naudio/NAudio#432]
I am doing this to wait until NAUDIO's buffers are empty:
while (waveProvider.BufferedBytes > 0)
{   // Need to keep transmitting until waveProvider's buffer is empty.
      HowardUtils.sleep(100);
}

But even when waveProvider.BufferedBytes == 0, I need an additional wait to make sure that all the audio has finished playing.

How can I determine exactly when NAUDIO has finished playing audio through the audio card?

**Comment by markheath** [comment]
Well normally I would say subscribe to `PlaybackStopped` as that event tells you you've reached the end of the audio stream, but you're using `BufferedWaveProvider` which never ends. 

If you're using a device that implements `IWavePosition` then you can use `GetPosition()` once the `BufferedBytes` gets to zero, and then wait until `GetPosition()` has increased by more than the size of a read buffer.

**Comment by AAN3AC** [comment]
Mark,

Once the BufferedBytes gets to zero, will this work correctly:

int milliseconds = waveTarget.DesiredLatency;
HowardUtils.sleep(milliseconds);

Will this do it???

Regards,
Howard

**Comment by AAN3AC** [comment]
Thanks Mark
