### ISSUE TITLE
Is it possible to generate piano tones by this library?

### ISSUE THREAD

**Issue by huhu2207** [naudio/NAudio#44]
Hi all, 

I'm planning to make a C# program which can read a text-based script and generate a series of specific piano sound and then merge into a song. Is it possible to use this library to generate piano sound directly? (without using others' audio sources)

Regards,
Jackson Hu

**Comment by markheath** [comment]
NAudio gives you the low level access to send whatever you want to the soundcard, so you can create a synthesizer. However, it does not provide anything more than the most basic synthesis (`SignalGenerator`). So unless you are very comfortable with writing your own algorithms, it might make more sense to go for a sample based approach.

**Comment by huhu2207** [comment]
Thanks for that, I've already found a piano audio source with more than 80 WAV files.
