### ISSUE TITLE
BUG ! ConcateningSampleProvider[] Cutting the Audio !

### ISSUE THREAD

**Issue by Gondlir** [naudio/NAudio#442]
Hi Mark, I'm using your NAudio librarian in my project, but I'm facing a big problem which is this: I use the ConcateningSampleProvider as an Array
Example: ConcateningSampleProvider [] sampleProv = new ConcateningSampleProvider [audiosTrack.Count];
Where: audiosTrack is a List of ISampleProvider
Example: List <list <ISampleProvider="">> audiosTracks;
I'm adding the songs like this:
audiosTracks [indexTrackCurrent] .Add (new AudioFileReader (newPathFile) .ToMono ()); // ToStereo the problem continues.

In this, at the time of concatenating, within a For loop, I have this line:
concatenatingTracks [i] = new ConcatenatingSampleProvider (audiosTracks [i] .ToArray ());

The Code itself works. He concatenates everything right and also his mix is ​​correct. The problem is that it cuts the audio! The original Audio has 8 seconds in total, but by the time it concatenates and saves the folder by clicking the song, it plays for only 4 seconds thus ending.
It is an important and great project, I need to solve this problem and I do not know where else to go. I need your help
Thank you very much for your attention.

Obs: I'm using in a project on Unity 2018.2.18f

**Comment by Gondlir** [comment]
sampleProv[i] = new ConcatenatingSampleProvider(audiosTracks[i].ToArray());
This line in especific is causing the problem... If I not use she can genarete one audio with the 8 seconds, but the other audios get 0 seconds...because the array...
and if I use this line, I get all the audios with 4 seconds just.

**Comment by Gondlir** [comment]
Many thanks for replying, Yes, I have small 8-second audios that, at the time the user clicks the "Share" button of my application, it picks up the audios the user chose, saves each one of them in a folder both in Windows as well as Android, and in the end it generates a "Composition" that would be the MIX, the mixture of those chosen audios, that also are saved in a folder.
But the problem is at the time of concatenating the audios that he is cutting in half, the audios that are to have 8 seconds end up getting 4. That is the problem, he is cutting the audio in half.

**Comment by markheath** [comment]
ConcatenatingSampleProvider is very simple. It just reads all audio from each sample provider in turn.
If you are getting half of the audio, then it may be that you are saving it with the wrong WAV format, since you converted it to mono. Does the audio also play at double speed?

Another reason you might get something like this is if you reuse the same AudioFileReader, as once it has reached the end, it would need to be repositioned to the start before it could be concatenated onto something else.

**Comment by markheath** [comment]
Make the simplest possible repro of the problem. Take two files, concatenate them and save them, and see if the issue persists. If you manage that, post the code here.

**Comment by Gondlir** [comment]
Hi Mark, well, the error wasn't in the Concatening, the system works perfeclty, congratulations ! 
The error was in a script SavWav, that cut the audio when are saving in a path, and when this path was get by the AudioFileReader already the songs cutted. 
Thanks for your time ! Your Library is perfect and super useful !

**Comment by Gondlir** [comment]
We fixed the problem by the way, Thanks.

**Comment by markheath** [comment]
great to hear that you found a solution to your problem
