### ISSUE TITLE
SoundFont sample data has a 12 bytes offset

### ISSUE THREAD

**Issue by faelenor** [naudio/NAudio#444]
In NAudio.SoundFont.SampleDataChunk constructor, only the id of the "sdta" chunk header is read before calling the GetData function. This is wrong because the size of that chunk is still unread, as long as the next "smpl" sub-chunk header! Because of this, the sample data is read from the file 12 bytes before it really starts (4 bytes for "sdta" chunk size + 4 bytes for "smpl" chunk id + 4 bytes for "smpl" chunk size). The total size of the sample data is also wrong because it's set to the size of the "LIST" chunk.

As a side note, there seems to be some confusion with ReadChunkID. This is sometimes called on a chunk created by GetNextSubChunk and this function already calls ReadChunkID. The result of that call is that it will read the _next_ chunk ID!  In the SoundFont constructor, this line is commented:
//RiffChunk r = list.GetNextSubChunk();
This kind of confirms that whoever changed that did not fully understand what he was doing.

**Comment by markheath** [comment]
The SoundFont support was a very early part of NAudio and is only really experimental. I have considered removing it, but I am also happy to accept PRs to fix this

**Comment by oggy22** [comment]
Are there any news on soundfonts progress? I'd be really happy to be able to use them.

**Comment by markheath** [comment]
@sinshu  thanks for sharing, looks like a great project

**Comment by rjjaret** [comment]
> @oggy22
> I've implemented a SoundFont parser and synthesizer which can work with NAudio.
> Please check this out if you are interested.
> https://github.com/sinshu/meltysynth

Hello @sinshu !  I'm having trouble figuring out how to pass rendered audio from MeltySynth to NAudio. Can you help?

Thanks,
Rob

**Comment by sinshu** [comment]
@rjjaret
This is NAudio's issue page, and it's not suitable for asking about MeltySynth.
For questions about MeltySynth, please check the issue page below, and create a new issue if necessary.
https://github.com/sinshu/meltysynth/issues
