### ISSUE TITLE
Question about playing multiple WAV files in the same time?

### ISSUE THREAD

**Issue by huhu2207** [naudio/NAudio#45]
Hi there, 

I have a question about that, I need to play 2~10 WAV wave file at the same time.
Is it possible to do that via NAudio, with less RAM consumption and delay?

Regards,
Jackson

**Comment by markheath** [comment]
You can just open a single output device and use a MixingSampleProvider to mix together multiple streams. This [article](http://markheath.net/post/fire-and-forget-audio-playback-with) might help you get an idea for how this can be accomplished.

**Comment by huhu2207** [comment]
Got it! Great thanks!

**Comment by huhu2207** [comment]
Emm sorry, I still feel a bit confused. What should I do if I want to set different volumes to each wave files? Can I set a fast-forward value to each of them when I need to play them in a faster speed?

Regards,
Jackson

**Comment by markheath** [comment]
well the inputs to the mixer can be things like AudioFileReader, allowing you to reposition within them, and change their volume. There is no playback speed adjustment algorithm build into NAudio though I'm afraid.

**Comment by huhu2207** [comment]
Okay thanks, I will have a try then.
