### ISSUE TITLE
Must read complete blocks: requested 1024, block align is 6'

### ISSUE THREAD

**Issue by GodStar88** [naudio/NAudio#454]
Hello, I used NAudio 6 months ago, it works well,
but now, doesn't work well

I got issue "Must read complete blocks: requested 1024, block align is 6"
![capture](https://user-images.githubusercontent.com/23701978/53245380-8436b080-36e8-11e9-8d47-1bd516de3c07.PNG)

**Comment by markheath** [comment]
You're probably reading a 24 bit WAV file. Just change it to something like

```cs
reader.Read(buffer, 0, buffer.Length - (buffer.Length % waveFileWriter.WaveFormat.BlockAlign))
```

**Comment by GodStar88** [comment]
thanks
