### ISSUE TITLE
naudio windows form as sender, uwp app as receiver

### ISSUE THREAD

**Issue by Sagittarius1218** [naudio/NAudio#456]
I'm currently new to NAudio, just downloaded NAudio example few hours ago and trying to understand the samples. As in the sample I can find the NetworkChatdemo that includes NetworkAudioSender, NetworkAudioPlayer, IAudioSender, IAudioReceiver, and Tcp or Udp sender and receiver. My goal is to use this demo as a server that send microphone audio over network, and an uwp app as a receiver connecting to the server via socket or streamsocket, afer connected the app will receive audio data and play it using NAudio. Is it possible?

**Comment by markheath** [comment]
Yes, it's possible but the NetworkChatDemo is very basic - it depends on your latency requirements as to whether this would work in your use case.

**Comment by Sagittarius1218** [comment]
Thank you very much for letting me know. My very first goal is just use the NAudiodemo to stream microphone to the uwp app. Your demo is very perfect at the moment. I just don't know how to connect to the streamer and then receive and play that sound at uwp app side. Could you please give me any suggestion how I can do it?

**Comment by markheath** [comment]
I don't have much by the way of UWP demos at the moment I'm afraid. However, I did make [a Pluralsight course on UWP Audio programming](https://pluralsight.pxf.io/c/1192349/424552/7490?u=www%2Epluralsight%2Ecom%2Fcourses%2Fuwp-audio-fundamentals) (not specific to NAudio), and so it should be possible to use some of the techniques I show there to send received audio into the AudioGraph (although it will be fairly ugly low-level code)

**Comment by InvaderTor** [comment]
Just an fyi you need to change from IPAddress.loopback to Any if you want the demo to work on different machines.
`
        public UdpAudioReceiver(int portNumber)
        {
            var endPoint = new IPEndPoint(IPAddress.Any, portNumber);
`
