### ISSUE TITLE
SupportedWaveFormat 

### ISSUE THREAD

**Issue by kholt891** [naudio/NAudio#459]
Why are values assigned twice to some of the WAVE_FORMAT...... objects/vars?
This was found in code using a foreach statement on the enum to retreive values.
Some of them appear twice and skip the actual format.
Is this by design?

**Comment by markheath** [comment]
I don't know what part of the code you are talking about. Can you be more specific?

**Comment by kholt891** [comment]
NAudio.Wave. SupportedWaveFormat is the coded enum.

**Comment by markheath** [comment]
`SupportedWaveFormat` contains the values from here: https://docs.microsoft.com/en-us/previous-versions/dd743855(v%3Dvs.85)

It's a "flags" enum, meaning that the values can be logically ORed together

Probably in the windows SDK there is more than one #define for certain values

**Comment by kholt891** [comment]
Possibly. Does that make the public statement of the declaration code
somehow repeat values given to the WAVE_FORMAT_XXXXXX? Where is the
actual enumerated values object given in code. This was a NUGET on
VS2015 development platform and do not see a way to patch this without
post processing the Enum SupportedWaveFormat.

**Comment by kholt891** [comment]
Can the flags in compile be changed to do this preprocessing without
further assignment problems?

**Comment by markheath** [comment]
I don't understand what the problem is. It's perfectly fine for an enum in .NET to define more than one name to the same value.

**Comment by kholt891** [comment]
Wanting to correct that if using the values that some of the available
WAVE_FORMATS are not correct and a compile using those values will
produce undesired results.  Not getting a correct wave format for the
sound device produces errors in the input/output stream or buffer.

**Comment by kholt891** [comment]
Is the code that makes the enum assignments visible in the project files?
