### ISSUE TITLE
Cannot use MediaFoundationResampler - Access violation exception

### ISSUE THREAD

**Issue by troy-lamerton** [naudio/NAudio#464]
When I read from a `MediaFoundationResampler` it is crashing the application. It seems that `MFInitMediaTypeFromWaveFormatEx` is trying to read an invalid location in memory.

The stacktrace leads me to this line in [`MediaFoundationInterop.cs`](https://github.com/naudio/NAudio/blob/e359ca0566e9f9b14fee1ba6e0ec17e4482c7844/NAudio/MediaFoundation/MediaFoundationInterop.cs#L38-L39).

**Stacktrace of the crash**
```

Read from location 00000000000027B0 caused an access violation.

Stack Trace of Crashed Thread 7844:
0x00007FF9F153B208 (mfplat) MFInitMediaTypeFromWaveFormatEx
0x000000004BB8D4B1 (NAudio) NAudio.MediaFoundation.MediaFoundationInterop.MFInitMediaTypeFromWaveFormatEx()
0x000000004BB8CCFB (NAudio) NAudio.MediaFoundation.MediaFoundationApi.CreateMediaTypeFromWaveFormat()
0x000000004BB89303 (NAudio) NAudio.Wave.MediaFoundationResampler.CreateTransform()
0x000000004BB88CAC (NAudio) NAudio.MediaFoundation.MediaFoundationTransform.Read()
0x000000004BB83603 (Assembly-CSharp) SampleConverter.WriteDiscordAudioToVivox() // my method
```

**My environment**
Unity Editor (C# Mono, .NET framework 4.x)
Windows 10, Realtek High Definition Audio, sound card is NVIDIA

**This is how I am using the resampler in my code**
```csharp
// resampling from 48000 Hz to 32000 Hz - 1920 bytes to 1280 bytes

discordMonoStream = new MemoryStream(new byte[1920]);
var noKetchup = new RawSourceWaveStream(discordMonoStream, MonoDiscordFormat);

resamplerDiscord = new MediaFoundationResampler(noKetchup, MonoVivoxFormat);

// < code that writes to the input stream and reset position to 0 >
// discordMonoStream.Write(...) etc

var outputBytes = new byte[1280];
resamplerDiscord.Read(outputBytes, 0, outputBytes.Length); // CRASH!
```

I am happy to look into and fix this myself. Let me know what I can do if you think this is a bug.

**Comment by markheath** [comment]
I've never used NAudio through Unity/mono so not sure whether this ought to work or not. Can you reproduce the same issue with the same code running on regular .NET framework?

**Comment by troy-lamerton** [comment]
I've changed to another library to support more platforms so I'm not using this code anymore.

**Comment by Darth-Carrotpie** [comment]
> I've changed to another library to support more platforms so I'm not using this code anymore.

Could you share what library you changed into? I'm having similar troubles with NAudio, very difficult to properly integrate into Unity :(
