### ISSUE TITLE
waveIn & waveOut Dispose

### ISSUE THREAD

**Issue by jookerq** [naudio/NAudio#465]
hi
i'm kid of unfamiliar to multi-threading & i got stuck in an app.so three is **WPF** app that implements **MVVM**. now i have an **`EventAggregator `** that send messages throw model-views .when i get certain message for an **`EventAggregator`** i create an `IAudioSender `& `IAudioReciver `as **networkChat** example does .it works great.i was able to send sound messages throw Ethernet .but when i want to dispose the objects it says :

> "System.InvalidOperationException: 'Cross-thread operation not valid: Control '' accessed from a thread other than the thread it was created on.'"

this message was originated from `waveIn `& `waveOut ` classes. after adding the `NAduio ` project i realize that the problem is from **`WaveCallbackInfo`** class & **`waveOutWindow`** on **disconnect** function .but no idea how to fix this :(

**Comment by markheath** [comment]
you need to use Control.BeginInvoke for any UI updating operations to perform them on the UI thread, as some events in NAudio can be received on background threads
