### ISSUE TITLE
.wav duration wrong calculation

### ISSUE THREAD

**Issue by sigma7i** [naudio/NAudio#467]
I trying get duration from wav file, which WaveFormat 16 bit, PCM, 44kHz, and 1 channel(!). I get half the duration. 
If i use formula  "time = FileLength / (Sample Rate * Channels * Bits per sample /8)" 
where "Channels" is "1" (constant value), it is calculated correctly.
I think is used incorrectly channel, when calculating the duration. 

		private static double GetDuration(byte[] data)
		{
			using (var stream = new MemoryStream(data))
			{
				using (var reader = new WaveFileReader(stream))
				{
			          return reader.TotalTime.TotalMilliseconds;
				}
			}
		}

version 1.8.5, 4.7.1 Framework

**Comment by sigma7i** [comment]
I have a guess what the problem is. Someone created a custom header, where the channels are listed 2 instead of the real 1.

Now  i use this code, and it's work fine

 		private decimal GetDuration(byte[] data)
		{
			using (var stream = new MemoryStream(data))
			{
				using (var reader = new WaveFileReader(stream))
				{
					// time = FileLength / (Sample Rate * Channels * Bits per sample /8)

					var timefl = data.Length / (reader.WaveFormat.SampleRate * 1.0 * reader.WaveFormat.BitsPerSample / 8.0);

					var time = decimal.Round((decimal)timefl, 3);
					return time;

					//	return Convert.ToDecimal(reader.TotalTime.TotalMilliseconds / 1000);
				}
			}
		}

**Comment by markheath** [comment]
great, glad you found a solution
