### ISSUE TITLE
How could make this support windows xp

### ISSUE THREAD

**Issue by heku** [naudio/NAudio#47]
I tried your demo app on windows xp, but lots of demo crashed. could anyone tell me if this support windows xp? I know some functions dependent on OS, I don`t need all features can be run on windows xp, but is there at least one api can run on both xp and win7/8/10 for playing and recording?

Thank you in advance.

**Comment by markheath** [comment]
The WaveIn... and WaveOut... functions are supported in Windows XP. You can't use WASAPI or MediaFoundation.

**Comment by heku** [comment]
Thanks for reply, I`ll have a try later.
