### ISSUE TITLE
Set specific sample rate WasapiOut

### ISSUE THREAD

**Issue by BenReg** [naudio/NAudio#470]
Hello,

Here : https://github.com/naudio/NAudio/blob/master/Docs/WasapiOut.md
For WasapiOut, it says that "If you choose AudioClientShareMode.Exclusive then you are requesting exclusive access to the sound card. The benefits of this approach are that you can specify the exact sample rate you want"
But I can't find anywhere where I can set a specific sampleRate programmatically.
I created my WasapiOut like this : 

`var enumerator = new MMDeviceEnumerator();
MMDevice device = enumerator.EnumerateAudioEndPoints(DataFlow.Render, DeviceState.Active).FirstOrDefault(d => d.DeviceFriendlyName == name);
outputDevice = new WasapiOut(device, AudioClientShareMode.Exclusive, false,200);`

Thanks

**Comment by markheath** [comment]
In exclusive mode it will try to open the soundcard using the `WaveFormat` of the `IWaveProvider` you pass to the `Init` method. Not everything will be supported though. Usually it must be stereo 44.1kHz or 48kHz with IEEE float 32 bit samples for it to be directly playable without any resampling required

**Comment by BenReg** [comment]
Hey ! Thanks, I also found this, but after how can I play an audio file with Naudio through the same output device since that the "init" method is already taken.
The only way I found how to do both is with a "MixingSampleProvider", am I in the right direction ?

**Comment by markheath** [comment]
All the audio player classes in NAudio implement `IWaveProvider` - so you can pass an `AudioFileReader` or a `Mp3FileReader` or a `MediaFoundationReader` or a `WavFileReader` into init, and it will try to play it at the sample rate of the file.

**Comment by BenReg** [comment]
Thanks, I solved my problem, I used an AudioPlaybackEngine (https://markheath.net/post/fire-and-forget-audio-playback-with) with a MixingSampleProvider, and a try/catch to handle the message error of "the inputs are not a the same sample rate" because that's what I wanted to do.
