### ISSUE TITLE
AsioOut missing in NuGet package

### ISSUE THREAD

**Issue by joergbeckmann** [naudio/NAudio#491]
I'm trying to include the NAudio NuGet package in a .NET Standard 2.0 project. Is there a reason why AsioOut and AsioDriver.GetAsioDriverNames() are missing there? (I've seen the "#if NET35" in AsioDriver)

**Comment by markheath** [comment]
in its current state the ASIO code won't compile as .NET standard. ASIO is Windows only, and the code makes use of some registry access classes. I have started prototyping a fully .NET standard compatible version of the ASIO support but it's not ready to share yet

**Comment by joergbeckmann** [comment]
Thank you for your answer. I'll write a small .NET framework class library wrapping NAudio for now.
