### ISSUE TITLE
Failed convert wav to mp3

### ISSUE THREAD

**Issue by CIO-REMILIA** [naudio/NAudio#500]
when using MediaFoundationEncoder.EncodeToMp3
it throws System.Runtime.InteropServices.COMException
seems the problem happens in MediaFoundationInterop.MFCreateSinkWriterFromURL...
my platform is win10 x64.

**Comment by markheath** [comment]
what is the actual COM error code - that should help narrow things down a bit more. Could be that the WAV input format is not supported by the encoder.

**Comment by CIO-REMILIA** [comment]
System.Runtime.InteropServices.COMException
HRESULT:0xC00D3E85

**Comment by markheath** [comment]
OK, that's MF_E_SHUTDOWN. Can you try calling `MediaFoundationApi.Startup` first

**Comment by CIO-REMILIA** [comment]
the problem solved, thank you very much!
