### ISSUE TITLE
Crashes on Windows 10 N or KN (should inform about missing Media Features Pack instead)

### ISSUE THREAD

**Issue by SimonSimCity** [naudio/NAudio#51]
In some places in this package, you assume that the user has installed the Media Feature Pack installed. Please add it as an optional to the library or at least inform the user about that this package is missing instead of just throwing an error for the missing `mfplat.dll`.

**Comment by markheath** [comment]
There are several reasons why media foundation might not be available. Is typically missing on server versions of Windows, is not available in XP, and also I don't think it's typically there in Azure Cloud Services. So I'm not sure there's one easy error message that will always tell the user why they can't use it. But it's a good suggestion and I'm open to pull requests that improve the error message.
