### ISSUE TITLE
Is it possible to open a loopback ISampleProvider?

### ISSUE THREAD

**Issue by babbag3** [naudio/NAudio#510]
Hi!

Been trying to work out how to get a loopback working so I can generate FFT data from audio going on on my pc and hook it into some existing code. Existing code is using an ISampleProvider to play back audio, and is hooked into a load of code. I can find various examples using wasapicapture or waveinprovider to get loopback, but can't work out an equivalent that will pass something compatible with ISampleProvider. Is that a thing?

Thanks!

**Comment by markheath** [comment]
If you put the recorded audio into a BufferedWaveProvider, that can be easily turned into an ISampleProvider (as the audio will already be IEEE floating point anyway), with the ToSampleProvider extension method.

**Comment by babbag3** [comment]
Thankyou Mark, much appreciated :)
