### ISSUE TITLE
Peek method for IWaveProvider

### ISSUE THREAD

**Issue by Zerseu** [naudio/NAudio#52]
I'm trying to performt FFT using NAudio in Unity game engine. It fails for either WASAPI or ASIO. We want to have visualizations in our application for both local and streamed audio content. The common denominator between these is the IWaveProvider interface. It would be very useful if you could implement a Peek() method so that we could use it to grab audio data without clipping the audio (Read() advances the stream position).
Thank you.

**Comment by markheath** [comment]
I'm not sure what you're asking for. You can construct a pipeline passing your IWaveProvider through to another, so that as it is read it also performs FFT. If you look at the source code for the WPF demo, you'll see the `SampleAggregator` class which shows an example of doing this

**Comment by Zerseu** [comment]
I'll look into it. Thank you.
