### ISSUE TITLE
Creating a wave format with more than 2 channels

### ISSUE THREAD

**Issue by mc0re** [naudio/NAudio#529]
I'm using `WaveFormat.CreateIeeeFloatWaveFormat()` to create an output format. I wanted to test the possibility of producing a wave file with more than 2 channels (i.e. 6 is a possible value according to IEEE),
But upon `WaveOut.Init()` call with an `ISampleProvider` returning that `WaveFormat`, *NAudio* throws an exception "InvalidParameter calling waveOutOpen". Is it something I do wrong, or is it a bug? There is no exception for 1 or 2 channels.

**Comment by markheath** [comment]
Sorry for the delay getting back to you. Audio drivers often only support a very specific number of channels and a few sample rates. In most cases `waveOutOpen` will only support mono or stereo.

**Comment by mc0re** [comment]
Is there a way to check the capabilities of the driver?

**Comment by markheath** [comment]
Yes, for `WaveOut`, use `WaveOut.GetCapabilities`
