### ISSUE TITLE
Mp3FileReader - resulting file slightly behind?

### ISSUE THREAD

**Issue by mb2140** [naudio/NAudio#53]
Hi Mark, I'm using the Mp3FileReader to convert an mp3 to a wav.  When I open the resulting wav file in an audio editor, I noticed it's just slightly behind.

```
  using (Mp3FileReader reader = new Mp3FileReader(filePath))
                {
                    using (WaveStream convertedStream = WaveFormatConversionStream.CreatePcmStream(reader))
                    {
                        WaveFileWriter.CreateWaveFile(newmp3ToWavFile, convertedStream);
                    }
                }
```

Here's a comparison of the result in my audio editor:

![audiocompare](https://cloud.githubusercontent.com/assets/8686664/11014260/7cedd6d6-84f4-11e5-8565-8c3338f0de38.png)

Both files are starting at the same location.  Any ideas how I can account for this offset when converting mp3 to wav?

**Comment by markheath** [comment]
Yes, unfortunately MP3 is not sample accurate (encode some samples and decode and you won't get exactly the same number back), and also, MP3 files often contain some junk data at the start which turns into a short period of silence. The length of the discrepancy might be the duration of a single MP3 "frame"

**Comment by mb2140** [comment]
Thanks Mark, that makes sense to me.  I've found that if I skip a certain number of "granules" in the mp3 it seems to be sample accurate.  How would I get this ISampleProvider back into a wavestream for writing the actual file?  

```
            AudioFileReader readCurrentWAV = new AudioFileReader(waveFileName);
            OffsetSampleProvider offsetSampleProvider = new OffsetSampleProvider(readCurrentWAV);
            offsetSampleProvider.SkipOverSamples = (7 * 576);
```

**Comment by mb2140** [comment]
Ah, you're right.  And on top of that it looks like different encoders use different sizes sample sizes for encoding/decoding sample delays.  I wonder if it would be possible to detect which encoder was used to encode the mp3 and compensate?

**Comment by markheath** [comment]
no easy way that I know of I'm afraid
