### ISSUE TITLE
File is not supported which captured by NAudioWpfDemo

### ISSUE THREAD

**Issue by CasLur** [naudio/NAudio#530]
Hi, I am confused when running NAudioWpfDemo in different Windows.

####  I did the same thing in Win 7 and Win 10.
1. Record some audio data by WASAPI Capture.
![Capture](https://user-images.githubusercontent.com/39762924/64686783-d213da00-d4bb-11e9-88ef-64f728905b4a.jpg)
2. Play these file with Window Media Player.~~(Obviously there is no problem with this step.)~~
3. Play these file with Media Foundation Playback.

#### And I got different result.

- Win 7:

![error in win 7](https://user-images.githubusercontent.com/39762924/64687252-ba892100-d4bc-11e9-9916-0615ef1011bf.jpg)

- Win 10:

![normal in win 10](https://user-images.githubusercontent.com/39762924/64688373-d261a480-d4be-11e9-8d43-cad48fa29ab1.png)

__The NAudio.dll build from commit\<ec5266ca\> on Visual Studio 2019 16.2.4.__

How to properly capture data and playback in NAudioWpfDemo.

**Comment by markheath** [comment]
You should be able to play it with the AudioPlayback demo (which will use WaveFileReader rather than MediaFoundationReader). Media Foundation will have a limited set of formats that it is willing to play directly, and looks like it doesn't want to play IEEE float on your Windows 7 system.

**Comment by CasLur** [comment]
Thanks for your reply.
