### ISSUE TITLE
WaveOut and WaveIn support in netstandard?

### ISSUE THREAD

**Issue by jskeet** [naudio/NAudio#538]
I'm working on a [WPF application for my electronic drum set](https://jskeet.github.io/DemoCode/Drums/) and currently target .NET Core 3.0 and .NET 4.7.2.

While much of NAudio is available in the netstandard2.0 target, WaveIn and WaveOut aren't available - and even WaveInEvent/WaveOutEvent don't allow me to detect the number of devices or get their capabilities.

Is this a fundamental limitation within .NET Standard, or could it be addressed in a future release? Would adding a netstandard2.1 target help? Let me know if there's anything you'd like me to investigate.

**Comment by sipsorcery** [comment]
+1 for `WaveOut`. 

For input devices `WaveInEvent.DeviceCount` is available in `netstandard2.0`. Unfortunately no matching method on `WaveOutEvent`.

**Comment by jwosty** [comment]
This also applies to a lot of the Asio stuff (like AsioOut). I wonder if there's any reason this can't target .net standard (for windows), or even .net core? .net core 3 can actually build WPF apps on windows, and I believe that's what MS wants you to do from now on, considering that .Net Framework 4.8 is going to be the last of the .Net Frameworks.

See how AsioOut.cs is just remove from compilation for .Net standard (are there apis missing from .net standard or .net core that's causing it to fail compilation?): https://github.com/naudio/NAudio/blob/ec5266ca90e33809b2c0ceccd5fdbbf54e819568/NAudio/NAudio.csproj#L28

**Comment by jwosty** [comment]
After some quick investigation, AsioDriver's usage of Microsoft.Win32.Registry seems to be the only thing stopping preventing successful compilation: https://github.com/naudio/NAudio/blob/89dd9528a79d559c80f2bfd4a91600ec9fde2050/NAudio/Wave/Asio/ASIODriver.cs#L33

I've found that Microsoft has released a .net standard (and friends) compatible package for this: https://www.nuget.org/packages/Microsoft.Win32.Registry. I'm really curious now. I'm going to see if I can get this part to work under .net standard

**Comment by jwosty** [comment]
Now that #574 is merged, here is the situation:

- .Net Standard 2.0 supports ASIO
- .Net Core 3.0 supports WaveIn/WaveOut

I think this can be closed, because this should be sufficient for most use cases as new apps should probably be using .Net Core 3.0 anyway.

**Comment by jskeet** [comment]
Sounds good to me. I hadn't spotted the 1.10 release with this in. If it's okay with everyone, I'll leave this open for a few days until I get the chance to actually test migrating my application back to .NET Core 3, by updating the NAudio dependency to 1.10. (I'm hoping it'll be just that simple...)

**Comment by markheath** [comment]
Great, let us know how you get on with this. I've done a bit of testing and it seems the .NET Core support is working nicely (thanks @jwosty). And @jskeet sorry I missed your NDC London talk, I was only there for the Wed & Thu this year.

**Comment by jskeet** [comment]
Works perfectly, thanks :)
