### ISSUE TITLE
MediaFoundationReader (fullPath); appears HRESULT: 0xC00D0029

### ISSUE THREAD

**Issue by bfyq** [naudio/NAudio#543]
Can someone help me see this problem, MediaFoundationReader MediaFR = new MediaFoundationReader (fullPath); an exception HRESULT: 0xC00D0029

**Comment by markheath** [comment]
This error is NS_E_CONNECTION_FAILURE: The network connection has failed.
https://www.hresult.info/FACILITY_MEDIASERVER/0xC00D0029
Check that the path is accessible over the network

**Comment by bfyq** [comment]
Thank you very much, I think it should be some faults in the network inside my home. This audio path can be accessed by Firefox, but I just found out that Google can't access it.




------------------ 原始邮件 ------------------
发件人: "Mark Heath"<notifications@github.com>;
发送时间: 2019年10月14日(星期一) 晚上10:32
收件人: "naudio/NAudio"<NAudio@noreply.github.com>;
抄送: "凤雏"<2452418262@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [naudio/NAudio] MediaFoundationReader (fullPath); appearsHRESULT: 0xC00D0029 (#543)




This error is NS_E_CONNECTION_FAILURE: The network connection has failed.
 https://www.hresult.info/FACILITY_MEDIASERVER/0xC00D0029
 Check that the path is accessible over the network

**Comment by bfyq** [comment]
> This error is NS_E_CONNECTION_FAILURE: The network connection has failed.
> https://www.hresult.info/FACILITY_MEDIASERVER/0xC00D0029
> Check that the path is accessible over the network

Thank you very much, I think it should be some faults in the network inside my home. This audio path can be accessed by Firefox, but I just found out that Google can't access it.
