### ISSUE TITLE
Loud noises when using static WasapiLoopbackCapture

### ISSUE THREAD

**Issue by RedGuys** [naudio/NAudio#560]
When you try to record sounds using WasapiLoopbackCapture as a result there are loud noises, the problem is played on different PCs, for example recorded output to a file.
I use VLC to open file
[soundfile.zip](https://github.com/naudio/NAudio/files/3855937/soundfile.zip)

[code](https://gist.github.com/RedGuys/17b506af976da775bc2e175292dfcb3f)

**Comment by markheath** [comment]
`WasapiLoopbackCapture` captures audio in IEEE floating point format. Whatever is playing your audio needs to expect that format or you will hear a loud noise.

**Comment by RedGuys** [comment]
Is there a way to capture sound without noise?

**Comment by markheath** [comment]
The WAV file you sent is not a valid WAV file. It has no header. You should use WaveFileWriter to create a proper file.
