### ISSUE TITLE
Get duration of VBR Files

### ISSUE THREAD

**Issue by kevinkouketsu** [naudio/NAudio#578]
NAudio can get the **REAL** duration of VBR file or NAudio calculate by estimative?  
In C++, my company created a function to read all content and get every frame to calculate the real duration.  
That is important to me because mixed audio needs to be perfect and longer files can have seconds of difference comparing with the real duration.

I can't get information in any issue or tutorial on web.

**Comment by markheath** [comment]
The `Mp3FileReader` in NAudio attempts to inspect all mp3 frames in the file and in theory should be able to report an accurate length. If you use `MediaFoundationReader`, I don't know what technique is used under the hoold
