### ISSUE TITLE
OffsetSampleProvider - Can't "Take" and "LeadOut" in single operation?

### ISSUE THREAD

**Issue by mb2140** [naudio/NAudio#58]
I'm trying to take the first 6 seconds or so of an audio clip, and then add a couple minutes of silence after it.  When I run this code the resulting wav file is only 6 seconds long instead of 2:06:

```
 offsetSampleProvider.Take = endAudioTimeTimespan.Duration();
 offsetSampleProvider.LeadOut = silenceToAddToEnd.Duration();

WaveFileWriter.CreateWaveFile16(newWavFile, offsetSampleProvider);
````

If I break this into 2 separate AudioFileReader operations (take samples, create wav file, read wav file, add silence) it works as expected.

**Comment by markheath** [comment]
yeah, that's a bug. I'll check in a fix soon

**Comment by mb2140** [comment]
Thanks for looking at this Mark, but it looks like the latest code has an issue using LeadOut by itself now.  For example, adding a LeadOut of 1:10 to a 2:43 wav file produced a wav of 1:14.  When I reverted to the previous OffSetSampleProvider code it produced the correct length (3:53)

**Comment by markheath** [comment]
doh, think I can see what it is. Need another unit test. Will try to get this fixed soon

**Comment by mb2140** [comment]
Thanks again Mark!  Another thought that just occurred to me - perhaps I should just chain multiple OffsetSampleProviders together.  That's how I have it implemented now and all is good.  NAudio is a phenomenal tool and I'm grateful for your help.

**Comment by markheath** [comment]
yes that works too, but its nice to flush out any remaining bugs in `OffsetSampleProvider` so thanks for reporting
