### ISSUE TITLE
WaveFormatConversionStream(Mp3FileReader) returns 0 on Read when finished

### ISSUE THREAD

**Issue by wasabii** [naudio/NAudio#60]
As far as I can tell, when the end of the stream is reached, `.Read` on the `Stream` returned from `WaveFormatConversionStream` returns 0. It should be returning -1.

**Comment by markheath** [comment]
All streams in NAudio work this way. They return 0 from the Read method to indicate end of stream. This is in line with the [MSDN documentation](https://msdn.microsoft.com/en-us/library/system.io.stream.read%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) for `Stream.Read`.

**Comment by wasabii** [comment]
You are correct. Sorry about that. I was reading a sample bit of code using NAudio where the person checked the return value for -1. And for some reason I had assumed this was correct, and invented knowledge about how .Net streams are supposed to work. My bad.
