### ISSUE TITLE
'fmt ' chunk has an extra 2 bytes in it

### ISSUE THREAD

**Issue by bamwu** [naudio/NAudio#604]
The following conversion code produces a wav file with an extra 2 zero-padded bytes (18 total bytes rather than 16) at the end of the 'fmt ' chunk...

                using ( AudioFileReader reader = new AudioFileReader(input) )
                {
                    WaveFormat format = new WaveFormat(44100, 24, 2);

                    using ( MediaFoundationResampler resampler = new MediaFoundationResampler(reader, format) )
                    {
                        resampler.ResamplerQuality = 60;

                        WaveFileWriter.CreateWaveFile(output, resampler);

                        return output;
                    }
                }

I can change my header parsing code to be more flexible with regard to fmt chunk length, but I'm curious if this is a bug or if it's something I missed in the spec.

**Comment by bamwu** [comment]
Actually, after reviewing the spec it looks like a subchunk's length could be longer, though it's unclear why space would be wasted. I'll go ahead and close this case and update my parsing code to not assume subchunk length based on the fields it contains.

**Comment by markheath** [comment]
It's because NAudio uses [WAVEFORMATEX ](https://docs.microsoft.com/en-us/windows/win32/api/mmeapi/ns-mmeapi-waveformatex) by default which is 18 bytes, unlike WAVEFORMAT which is 16
