### ISSUE TITLE
Record system audio in UWP projects

### ISSUE THREAD

**Issue by singhwong** [naudio/NAudio#605]
I want to record system audio in UWP projects, when will this feature be added.

**Comment by markheath** [comment]
You might be able to do this directly with https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Audio.AudioDeviceInputNode without needing NAudio

**Comment by Arlodotexe** [comment]
Unless I'm missing something, this doesn't actually work. (see [here]( https://stackoverflow.com/questions/53026841/using-audiorender-device-as-input-for-audiograph-uwp))

**Comment by singhwong** [comment]
> Unless I'm missing something, this doesn't actually work. (see [here](https://stackoverflow.com/questions/53026841/using-audiorender-device-as-input-for-audiograph-uwp))

If you want record system audio in uwp,you can use MediaCapture API,not use Naudio Lib.
`MediaCaptureInitializationSettings settings = new MediaCaptureInitializationSettings
            {
                StreamingCaptureMode = StreamingCaptureMode.Audio,
                AudioDeviceId = yourSelectedAudioCaptureDevice
            };`
`var audioCaptureDevices = await DeviceInformation.FindAllAsync(Windows.Media.Devices.MediaDevice.GetAudioCaptureSelector());         
            foreach (var device in allVideoDevices)
            {
                //to do.
            }`

**Comment by Arlodotexe** [comment]
@singhwong Could you provide some more details? These APIs seem to be used for camera capture, and while I can easily get the default output device, create a `MediaCapture` and `MediaCaptureInitializationSettings` object, and tell it to use these, it still uses the Microphone, not the audio render device I gave it.

**Comment by singhwong** [comment]
@Arlodotexe You can use loopback recoding with WASAPI, about the loopback, you can refer to this [document](https://docs.microsoft.com/en-us/windows/win32/coreaudio/loopback-recording) and here is a [sample](https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/windowsaudiosession/) you can download it.
