### ISSUE TITLE
Some audio formats not being accepted by AudioFileReader despite codecs installed

### ISSUE THREAD

**Issue by bamwu** [naudio/NAudio#609]
Codecs for the following types: flac, ogg, aac, ac3 are installed, but AudioFileReader() throws an exception (0xC00D36C4) every time I try to pass test files to it. Several other formats work perfectly using this same block of code...

                using ( AudioFileReader reader = new AudioFileReader(input) )
                {
                    WaveFormat format = new WaveFormat(44100, 24, 2);

                    using ( MediaFoundationResampler resampler = new MediaFoundationResampler(reader, format) )
                    {
                        resampler.ResamplerQuality = 60;

                        WaveFileWriter.CreateWaveFile(output, resampler);

                        return output;
                    }
                }

**Comment by markheath** [comment]
Under the hood, this is just using `MediaFoundationReader`, which may not have the ability to load those files. NAudio is just calling through to Windows APIs.

**Comment by bamwu** [comment]
Any ideas about a path forward?

**Comment by markheath** [comment]
Unless you can find something that lets media foundation play those files, then there's not a lot NAudio can do to help. it might be possible to use ACM codecs to play them, but that is quite a complex task to work out what the expected WAVEFORMAT structure required is.

**Comment by bamwu** [comment]
Is the general rule of thumb: if Windows Media Player can play it, NAudio should be able to play it?

**Comment by bamwu** [comment]
Scratch that last question. WMP looks for an MFT first and then falls back to DirectShow codec if it can find one.

Is there a DirectShow equaivalent to AudioFileReader in NAudio?

**Comment by markheath** [comment]
unfortunately not. Would be a nice feature, but not something available at the moment.

**Comment by bamwu** [comment]
Fair enough.

Sorry if this sounds redundant, but I framed that last question a little too narrowly...

Is NAudio able to utilize DirectShow decoders in its current state?

**Comment by markheath** [comment]
Unfortunately not. I don't think there's an easy way to achieve that.

**Comment by bamwu** [comment]
Ok. Thanks for answering my questions, Mark.
