### ISSUE TITLE
ProductName properties truncates device 

### ISSUE THREAD

**Issue by MalcolmSharp** [naudio/NAudio#612]
I am using NAudio to run a PCB 633A01 Accelerometer which mimics microphone functionality. So far so good as NAudio finds it and I can happily stream data from it as a WaveIn device.

![image](https://user-images.githubusercontent.com/34167180/77529494-a2408880-6e87-11ea-87d0-e9cf38f3622b.png)

The problem is when I used the ProductName property of the WaveInCapabilities class the Product Name returned is truncated to 31 characters. The full Product Name of 43 characters: 

Microphone (633A01 10002203488369689190712)

is required as the full name also carries the device serial number, calibration data and calibration date in the long number string following the 633A01 which is needed to operate the device. Is there a current workaround to access the full string programmatically for this?

Thanks and regards,

Malcolm Sharp

**Comment by volkans80** [comment]
I tried to use MMDeviceEnumerator and its getting full device names correctly but i can't figure out how to use this device list with WaveIn class for sound recording. Device order maybe changes.

**Comment by markheath** [comment]
It's a fundamental limitation of the waveIn capabilities structure that it can't report long device names. I've tried many workarounds over the years but it's very hard to find something that works reliably.
