### ISSUE TITLE
WasapiCapture buffer size bug?

### ISSUE THREAD

**Issue by jfrank14** [naudio/NAudio#618]
Given the WASAPI wave format, the `AverageBytesPerSecond` is 384000.

So if I specify, say, 500ms for the `audioBufferMillisecondsLength` parameter in the constructor, I would expect the actual buffer size to be 192000, but in fact it is only 96000.

If I simply double the parameter, I get the right amount of data and the rest of the signal chain works fine, but I'd like to understand if this is a bug or if the parameter is misnamed or if i'm just not understanding what this parameter means.

**Comment by markheath** [comment]
When playing and capturing audio you usually work with two buffers - one is being accessed by the soundcard while the other one is being processed by your code. So the buffer length gets halved. I regret naming the parameter that way though as it has confused plenty of people.
