### ISSUE TITLE
HRESULT: 0xC00D5212 when trying to play an mp2 encoded wav file.

### ISSUE THREAD

**Issue by luluname** [naudio/NAudio#619]
I am writing a simple audio player with ASIO and MIDI control support that is going to be used by a local radio station. The station uses some weird ancient piece of software that uses mp2 encoded .wav files. The file itself plays fine on all windows versions in WMP or VLC Players it also plays fine with my NAudio based player on Windows 10, but many computers there are still running Windows 7 and when I try to play the file on windows 7, the program throws an exception:

`System.Runtime.InteropServices.COMException (0xC00D5212): Výjimka na základě hodnoty HRESULT: 0xC00D5212
   v NAudio.MediaFoundation.IMFSourceReader.SetCurrentMediaType(Int32 dwStreamIndex, IntPtr pdwReserved, IMFMediaType pMediaType)
   v NAudio.Wave.MediaFoundationReader.CreateReader(MediaFoundationReaderSettings settings)
   v NAudio.Wave.MediaFoundationReader.Init(MediaFoundationReaderSettings initialSettings)
   v NAudio.Wave.MediaFoundationReader..ctor(String file)`

which I believe is "Missing codec", do any of you have any idea how to get around this? I am using the MediaFoundationReader() in the NAudio library.

**Comment by ioctlLR** [comment]
You might try [NLayer](https://www.nuget.org/packages/NLayer.NAudioSupport/) instead of using MediaFoundationReader.  It understands MP1 and MP2 files, as well as MP3.  NLayer.NAudioSupport.ManagedMpegStream is probably the type you want.

NOTE: I haven't ever tried it with mp2 audio wrapped in a wav file, but in theory it should "just work".

A no-code solution would also be to find and install a Media Foundation-enabled MP2 codec, though I have no insight into finding one.

**Comment by luluname** [comment]
Thank you Andrew! I will take a look at NLayer tomorrow, but it would be great to get a MF MP2 codec, if anyone knows anything that could possibly work, please let me know. I have googled whole afternoon, but no luck.

Lu.

**Comment by luluname** [comment]
NLayer plays the file just fine, but i still need to support ordinary wav files. maybe it is a dumb question, sorry, but is it somehow possible to combine more readers? I could filter the files by extension, but since the mp2 is wrapped into wav, I don't know how to sort the files. Any advice?

Thanks.

**Comment by ioctlLR** [comment]
Probably the easiest solution is to load the file stream into a WaveFileReader instance and check the WaveFormat.Encoding.  If it's not Mpeg then just use the instance as-is.  If it is Mpeg, then pass the original stream to ManagedMpegStream and use that (and dispose the WaveFileReader instance).

I'm mostly guessing on the encoding value, BTW.  You'll probably need to examine the different output files you're loading to verify which encoding is used by each source.

**Comment by luluname** [comment]
Ok, I think I solved the problem, have edited the AudioFileReader and it now recognises the mp2 wav and passes it to ManagedMpegStream. Thank you!

**Comment by ioctlLR** [comment]
Sounds great!
