### ISSUE TITLE
VS 2013 Cannot find NAudio.Wave.ASIO

### ISSUE THREAD

**Issue by laserbeak** [naudio/NAudio#63]
Hello,
installed NAudio into a project using nuget, added:

    using NAudio.Wave;
    using NAudio.CoreAudioAPI;

I get an error when I try:
    waveOutDevice = new NAudio.Wave.AsioOut();

> Error	1	The type or namespace name 'AsioOut' does not exist in the namespace 'NAudio.Wave' (are you missing an assembly reference?)

**Comment by markheath** [comment]
what sort of a project are you making? AsioOut cannot be used with the Windows 8 / UWP builds.

**Comment by laserbeak** [comment]
That's probably what it was then. I was just taking a tutorial I found online. I decided to do a WPF version instead and everything works.
I'm working on a MIDI project. Thanks for the reply, and your library!!
