### ISSUE TITLE
There was an error in the mix

### ISSUE THREAD

**Issue by luchong0813** [naudio/NAudio#652]
I managed to record speaker audio using WasapiLoopbackCapture and save it to a WAV file, also I managed to record and save microphone audio using WaveIn. The main problem is that I cannot mix these 2 files into a single file. Prompt me during the mix "file is being used by another process, so this process cannot access this file"  What should I do 

`  using (var reader1 = new AudioFileReader(soundcard))
   using (var reader2 = new AudioFileReader(microphone))
    {
             reader1.Volume = 2.0f;
             reader2.Volume = 2.0f;
             var mixer = new MixingSampleProvider(new[] { reader1, reader2 });
             WaveFileWriter.CreateWaveFile16(mixed, mixer);
    }`

**Comment by markheath** [comment]
Did you definitely close the files before attempting to mix them?
That's most likely explanation. Otherwise some other process on your PC is accessing the files
