### ISSUE TITLE
Try to capture the systemsound with WasapiLoopbackCapture

### ISSUE THREAD

**Issue by T4G99** [naudio/NAudio#655]
Hey,

I want to capture the systemsound.
There is something like capturing the sound but its not about the sinus-wave i expected.
If there is any sound the feedback shows me something like on oder off and not the volume and sound sensitive wave. Like this:

![image](https://user-images.githubusercontent.com/59883412/84890343-90dbd680-b09a-11ea-94df-401e16bf79ae.png)

 
And with the micro i captured:

![image](https://user-images.githubusercontent.com/59883412/84890236-71dd4480-b09a-11ea-98e5-0459dbc76075.png)

Can someone help me to decode the sound i captured or fix my code?

**Comment by T4G99** [comment]
The code I used: (pls dont burn me too hard its my hobby and i collected the code from other projects):

(start recording):
 cap = new WasapiLoopbackCapture();
cap.DataAvailable += new EventHandler<WaveInEventArgs>(AudioDataAvailableInt);
capbwp = new BufferedWaveProvider(cap.WaveFormat);
capbwp.BufferLength = buffer * 2;
capbwp.DiscardOnBufferOverflow = true;

(WaveInEvent)
capbwp.AddSamples(e.Buffer, 0, e.BytesRecorded)

**Comment by markheath** [comment]
What code is in AudioDataAvailableInt?

**Comment by T4G99** [comment]
The code is:
private void AudioDataAvailableInt(object sender, WaveInEventArgs e) { capbwp.AddSamples(e.Buffer, 0, e.BytesRecorded); }

capbwp is  "BufferedWaveProvider"


Im sorry for my lare reply, i had some exams last week

**Comment by T4G99** [comment]
I have spotted the problem at  the "BufferedWaveProvider".
The return if i capture "WaveInEvent" is a very differently to "WasapiLoopbackCapture" and the "BufferedWaveProvider" i have used in both cases. 
I think its "just" about this format and the way of changing it. 

Many thanks in advance for your help.
