### ISSUE TITLE
problems in an aiff header (I think)

### ISSUE THREAD

**Issue by Jockey4her** [naudio/NAudio#658]
I used NAudio to write an app that prepares audio files for embedded processors.  I use the resampler feature to move everything to mono,8bit/22k, then save out the file as an aiff file.  

The original app worked just great for years.  Last year I copied it and added a few UI features when something broke. The audio began playing back distorted.  Finally got some time so I've been trying to spot where the problem crept in.

I used HxD to compare a good output file with a bad one.  See attached.  The problem is in the aiff header someplace.  In the good file there are a few extra characters in the header. If I copy that header to the bad file it plays fine.  You can see the data in each file matches, meaning the resampler went fine and the outStream should be correct getting to this point. 

The header is created by NAudio's CAiffWriter feature.  

![GOOD](https://user-images.githubusercontent.com/4777206/86029528-e4361900-b9f8-11ea-9ea2-5b8b2808e994.jpg)
![BAD](https://user-images.githubusercontent.com/4777206/86029536-e5ffdc80-b9f8-11ea-94b6-b3268ec68c04.jpg)

CAiffFileWriter.cs -- this is the method from NAudio I use that should be writing the header.  I didnt change it, but maybe.. something it does changed. IDK.  Stuck.

        /// <summary>
        /// AiffFileWriter that actually writes to a stream
        /// </summary>
        /// <param name="outStream">Stream to be written to</param>
        /// <param name="format">Wave format to use</param>
        public CAiffFileWriter(Stream outStream, WaveFormat format)
        {
            this.outStream = outStream;
            this.format = format;
            this.writer = new BinaryWriter(outStream, System.Text.Encoding.UTF8);
            this.writer.Write(System.Text.Encoding.UTF8.GetBytes("FORM"));
            this.writer.Write((int)0); // placeholder
            this.writer.Write(System.Text.Encoding.UTF8.GetBytes("AIFF"));

            CreateCommChunk();
            WriteSsndChunkHeader();
        }

**Comment by Jockey4her** [comment]
I tried to do some more detective work:  Both the good and bad versions use BinaryWriter method which is in the System.IO class in mscorlib.  In the good version it uses .NETFramewor\v4.6.1\mscorlib.dll, while the bad uses .NETFramework\v4.7.2\mscorelib.dll.

Not much to go on, but .. maybe?

**Comment by markheath** [comment]
NAudio doesn't have a class called CAiffWriter so not sure where you found that.
The NAudio AiffWriter class must be disposed before the resulting file is valid.
Looks like you haven't done this for this file, as both the placeholder sizes are still 0.

**Comment by Jockey4her** [comment]
By golly, Mark you really have a head for this. You were absolutely right. The error was a lack of Dispose.  Cheers and thanks so much.
