### ISSUE TITLE
Build errors with NAudio-master

### ISSUE THREAD

**Issue by Jockey4her** [naudio/NAudio#659]
I downloaded the NAudio-master archive and, selected NAudioUniversalDemo as the Startup Project, hit build and get 4 errors:
Figured you might want to know, or else let me know how to repair it/use it properly. Thanks.

C:\Users\BMT\Documents\Visual Studio 2019\NAudio-master\NAudio-master\NAudio\Wave\WaveInputs\WasapiCaptureRT.cs(9,15,9,22): error CS0234: The type or namespace name 'Devices' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\BMT\Documents\Visual Studio 2019\NAudio-master\NAudio-master\NAudio\Wave\WaveInputs\WasapiCaptureRT.cs(10,15,10,20): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\BMT\Documents\Visual Studio 2019\NAudio-master\NAudio-master\NAudio\Wave\WaveOutputs\WasapiOutRT.cs(8,15,8,20): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\BMT\Documents\Visual Studio 2019\NAudio-master\NAudio-master\NAudio\Wave\WaveOutputs\WaveFileWriterRT.cs(6,15,6,22): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
1>C:\Users\BMT\Documents\Visual Studio 2019\NAudio-master\NAudio-master\NAudio\Wave\WaveInputs\WasapiCaptureRT.cs(105,46,105,63): error CS0246: The type or namespace name 'DeviceInformation' could not be found (are you missing a using directive or an assembly reference?)

**Comment by markheath** [comment]
hmm, not sure why - I can build on my machine. Do you have the UWP SDK's installed?

**Comment by Jockey4her** [comment]
I thought I installed them, this right? I have not coded in c# for a while so I am probably chumping it in the tool somewhere.  I open NAudio-master\NAudio.sln  then in the Solution Explorer to go Samples/NAudioUniversalDemo, right click set as Startup. Then clean, then rebuild?  That's where I get the error.

![Annotation 2020-07-02 153315](https://user-images.githubusercontent.com/4777206/86406851-7d736280-bc79-11ea-99b4-91222678b3cb.jpg)

**Comment by markheath** [comment]
here's what I've got installed: 
![image](https://user-images.githubusercontent.com/147668/86407296-b24cdd00-bcac-11ea-9790-008b3dafd3f7.png)

**Comment by Jockey4her** [comment]
I had the 17134 but didnt have the 17763.0 ticked. When I did that, it works like a champ. Thanks again.
