### ISSUE TITLE
Cannot play .ogg or .adts (containing aac)

### ISSUE THREAD

**Issue by asdfgasdfsafgsdfa** [naudio/NAudio#66]
Hi,
the title says all.
I'm using MediaFoundationReader and it worked well so far.

I installed the ogg codec but it still doesnt work.
I always get  HRESULT: 0xC00D36C4. That means something like format not supported I read on google.

Using the https://github.com/naudio/Vorbis project and using its reader also doesnt work. It says "cannot determine container format".

What can/should I do?
Should I upload the files here maybe?

Edit: I have a few other "adts" files (all files are from youtube) that MediaFoundationReader plays with no problem.
Do I have to install something else besides the ogg codec thing?

**Comment by markheath** [comment]
I'm afraid I don't know what Media Foundation codecs would be needed to support this. You would need both something that can understand the container format, and decode the audio within it.
