### ISSUE TITLE
File stays open when an exception occurs in an constructor which accepts a filename

### ISSUE THREAD

**Issue by DirkFEng** [naudio/NAudio#660]
Hi,

I use two classes AudioFileReader and Mp3FileReader in my projects. If I use the constructor with a filename and the file is corrupt or not the expected type an exception is raised. 

The problem is the file is still opened and there's no possibility to close it (only if I use a FileStream as parameter - but this is not possible with AudioFileReader).

example:
			Mp3FileReader reader = null;
			try
			{
				reader = new Mp3FileReader("MyInvalidFile.wav");
			}
			catch (Exception ex)
			{
				// do anything
			}
			finally
			{
				// but its clearly null when exception is raised
				if (reader != null)
				{
					reader.Dispose();
				}
			}

			// raises an Exception, because file is still opened
			FileStream fs = new FileStream("MyInvalidFile.wav", FileMode.Open);

Solution: close the internal streams in case of error and raise the exception after that.
If I overlooked something - sorry for your effort.

Regards
Dirk

**Comment by markheath** [comment]
`Mp3FileReader` will close the file stream if it encounters an invalid file, so not sure what issue you are running into.

I tested with this code and it works just fine:
```cs
var fileName = @"C:\Test.jpg";
try
{
    var reader = new Mp3FileReader(fileName);
}
catch(Exception e)
{
    e.Dump();
}
var open = File.OpenRead(fileName);
Console.WriteLine("Opened OK");
open.Dispose();
```

**Comment by DirkFEng** [comment]
Why I include an example code ??

First: You use a different test code!
Second: Why your code works? File.OpenRead opens a write protected stream - read only.

And now look at the source of Mp3FileReader or AudioFileReader. In case of an exception the internal stream is not closed. 
Append this line of code after your examples and it dont work anymore because I open the file with read AND write accesss,
FileStream fs = new FileStream(fileName, FileMode.Open);

**Comment by markheath** [comment]
I did look at the source code of Mp3FileReader and it disposes the internal stream in the case of an exception. 
I can open the file with write access as well in my example.

**Comment by DirkFEng** [comment]
Haha - i did the stupid mistake many others did before --- my version is a "little" older than the actual one. 
But the only whitewash to me is - as I look for the source of AudioFileReader I found also a older one for the first time.
I tried the newerst version and now it works. Also looked at the actual code which was a little different than the code I found before. 
So sorry for your patience and you can close it. Have a nice day.

Tipp: next time ask for the version that was used ^^
