### ISSUE TITLE
Change volume of a currently running program

### ISSUE THREAD

**Issue by IanRawz** [naudio/NAudio#665]
Is it possible to change the audio volume of a specific session/program (like Firefox)?

My current code allows me to change the volume of a device, but I can't figure out how to change the volume of a program...

```
class Program
    {
        static void Main(string[] args)
        {

            try
            {
                MMDeviceEnumerator MMDE = new MMDeviceEnumerator();

                MMDeviceCollection DevCol = MMDE.EnumerateAudioEndPoints(DataFlow.All, DeviceState.Active);
                
                foreach (MMDevice dev in DevCol)
                {
                    try
                    {
                            var newVolume = (float)Math.Max(Math.Min(10, 100), 0) / (float)100;
                       
                            dev.AudioEndpointVolume.MasterVolumeLevelScalar = newVolume;

                            Debug.WriteLine("Volume of " + dev.DeviceFriendlyName + " is " + dev.AudioEndpointVolume.MasterVolumeLevelScalar.ToString());
                    }
                    catch (Exception ex)
                    {
                        Debug.WriteLine(dev.DeviceFriendlyName + " could not be muted " + ex);
                    }
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Error: " + ex.Message);
            }
                            Console.ReadKey();
       }
 }
```

**Comment by IanRawz** [comment]
Well, I guess I figured it out:

                       var sessions = dev.AudioSessionManager.Sessions;
                        for (int i = 0; i < sessions.Count; i++)
                        {
                            Process process = Process.GetProcessById((int)sessions[i].GetProcessID);
                            if (process.ProcessName == "foobar2000" && !String.IsNullOrEmpty(process.MainWindowTitle))
                            {
                                pID = process.Id;
                                sessions[i].SimpleAudioVolume.Volume = 0.2f;
                            }
                        }

**Comment by markheath** [comment]
great, glad you figured it out, and thanks for sharing the solution

**Comment by roblatour** [comment]
sessions[i].SimpleAudioVolume.Volume  is a read only property, so the above is not working for me.

**Comment by markheath** [comment]
You can set the Volume property on SimpleAudioVolume. The VolumePanel in NAudioDemo does this.

**Comment by roblatour** [comment]
Thank you, turns out I was using an older version for the library.  Upgrading to 2.1 allow the SimpleAudioVolume property to be set.
