### ISSUE TITLE
Trying to use MixingWaveProvider32 

### ISSUE THREAD

**Issue by billhaynes99** [naudio/NAudio#669]
In Windows using C#, I'm recording the microphone using WaveIn and the speakers using WasapiLoopbackCapture.  I want to mix the two (if possible).  I create WaveInProvider from both and pass them as inputs to MixingWaveProvider32.  I've attempted both a thread to read from the MixingWaveProvider32 as well as just done a CreateWaveFile to dump directly to disk but I can't seem to get usable audio using either method.  Am I missing something in how to use MixingWaveProvider32?  Do I need to still handle DataAvailable messages for both of my sources and put the data somewhere so that it is available?  I assumed if I passed the WaveInProviders that I wouldn't need to do that.  I'm worried about audio latency if I try to deal with event handlers.

**Comment by markheath** [comment]
It's likely that the audio from WaveIn is 16 bit and the audio from WasapiLoopbackCapture is 32 bit IEEE floating point, so you'll need to convert the 16 bit audio to floating point. I'd probably suggest using a BufferedWaveProvider for each input, and then using ToSampleProvider on both before passing into a MixingSampleProvider. Then you need to write custom logic that reads out of both providers when they have audio available as CreateWaveFile will attempt to read as fast as possible which will be too fast. Sadly this requires a fair amount of custom code as it stands.

**Comment by billhaynes99** [comment]
Thanks for that feedback!  As a test, I'm only doing the speaker recording using WasapiLoopbackCapture so I can see if I get audio from the MixingSampleProvider.  Can you clarify how I should be using MixingSampleProvider while doing my own reads from BufferedWaveProvider as you mentioned?  Even though I only have one BufferedWaveProvider, I'm attempting to read from the MixingSampleProvider and it returns more samples than what I have added to the BufferedWaveProvider on DataAvailable events.  Not quite sure which source I should be reading from and how to control it so that when I have two sources, they get mixed properly.

**Comment by billhaynes99** [comment]
Through much trial and error, I actually got the MixingSampleProvider to work for me with two different sources (microphone recording and speaker recording).  I force the microphone recorder to be the same WaveFormat as the speaker recorder so that solved any format concerns.  I also had to add each of the BufferedWaveProvider inputs separately to the mixer as ToSampleProvider doesn't convert them like calling AddMixerInput does.   I'm now doing additional testing because I have some concerns over the timing of the audio since I have to add OnDataAvailable events to each BufferedWaveProvider and I'm aware that may cause some sync issues.  I also know that the speaker recorder doesn't put anything out if nothing is actually playing so I'm working on adding "silent" audio so something is always playing.  Thanks for your help and if you have thoughts on the timing problem, I would appreciate that!

**Comment by billhaynes99** [comment]
I have now completed my implementation and to my surprise, there is no timing issue.  Seems that adding buffers to the two BufferedWaveProviders via events stays ahead of how fast I can read them and since I read them together, they are coming out synchronized.  I added the playing of silent audio to ensure I'm always getting something from the speaker recording and that solved that problem as well.  Thanks for your help and I couldn't have done this without all of your NAudio code!

**Comment by Henderz** [comment]
Would you mind sharing your code on how you are reading from MixingSampleProvider? I think I have the exact same requirement as yours and got until adding the samples to the MixingSampleProvider but unclear on how to read the mixed audio chunks from it...

**Comment by Henderz** [comment]
I could now read with the following code but the merged audio is sped up to 2x speed. I don't know what I am missing.. Can you please help?

float[] buffer;
Timer readTimer = new Timer((_obj) => {
	buffer = new float[1000];
	objMixingSampleProvider.Read(buffer, 0, buffer.Length);
	writer.WriteSamples(buffer, 0, buffer.Length);
}, null, 0, 50);

**Comment by markheath** [comment]
Audio playing at 2 speed is almost always because you are trying to play mono audio as though it was stereo
