### ISSUE TITLE
Licensing for https://github.com/naudio/varispeed-sample

### ISSUE THREAD

**Issue by jtorjo** [naudio/NAudio#670]
Hi Mark,

Your lib is beyond awesome! 

I'd also like to use the varispeed-sample project (modify it a bit) in a commercial app. What's the licensing for it? Is it still MS-PL (besides soundtouch's licensing which is LGPL 2.1)? 

Thanks!

Best,
John

**Comment by markheath** [comment]
hi John, yes the code I've written is all MS-PL. SoundToich has its own license.

**Comment by jtorjo** [comment]
Awesome, thanks!
I was asking, since the varispeed sample didn't have a license :)
