### ISSUE TITLE
Add an option to create a new MediaFoundationReader from stream

### ISSUE THREAD

**Issue by emiliano84** [naudio/NAudio#675]
I'm using your amazing library in UWP and I would love  if the `new MediaFoundationReader()` constructor would accept also preferably a stream (or bytes or buffer) instead of a file path only, in this way I'll be able to use it directly with no need to copy the file to an app folder or ask for a broader filesystem permission, hopefully it's possible.

Thanks

**Comment by wtywtykk** [comment]
Actually I have written one (not for UWP, but I think it will also work) 

However I used some code from Microsoft (https://referencesource.microsoft.com/#PresentationFramework/src/Framework/MS/Internal/IO/Packaging/managedIStream.cs) 

I'm not sure whether the license is compatible. If it's ok to use, I can create a pull request.....

**Comment by emiliano84** [comment]
> Actually I have written one (not for UWP, but I think it will also work)
> 
> However I used some code from Microsoft (https://referencesource.microsoft.com/#PresentationFramework/src/Framework/MS/Internal/IO/Packaging/managedIStream.cs)
> 
> I'm not sure whether the license is compatible. If it's ok to use, I can create a pull request.....

@wtywtykk can you kindly point me out where did you implemented it, if it's open source, would help me to save some time.

Also sorry to ask you out of the blue, I saw you have many audio repos and I didn't went trough all of them, did you implement by any chance a way to calculate the beats per minute/tempo of a song? thanks

**Comment by wtywtykk** [comment]
In MediaFoundationReader.cs the original CreateReader function uses MFCreateSourceReaderFromURL to read files. And MFCreateSourceReaderFromByteStream is the stream version. Here's the code I used:
```c#
System.Runtime.InteropServices.ComTypes.IStream managedStream=new WaveStreams.ManagedIStream(stream);
IMFByteStream byteStream;
MediaFoundationInterop.MFCreateMFByteStreamOnStream(managedStream, out byteStream);
MediaFoundationInterop.MFCreateSourceReaderFromByteStream(byteStream, null, out reader);
Marshal.ReleaseComObject(byteStream);
```

I don't know how to calculate the BPM. But maybe you can check this out https://github.com/stengerh/foo_bpm

**Comment by emiliano84** [comment]
> In MediaFoundationReader.cs the original CreateReader function uses MFCreateSourceReaderFromURL to read files. And MFCreateSourceReaderFromByteStream is the stream version. Here's the code I used:
> 
> ```cs
> System.Runtime.InteropServices.ComTypes.IStream managedStream=new WaveStreams.ManagedIStream(stream);
> IMFByteStream byteStream;
> MediaFoundationInterop.MFCreateMFByteStreamOnStream(managedStream, out byteStream);
> MediaFoundationInterop.MFCreateSourceReaderFromByteStream(byteStream, null, out reader);
> Marshal.ReleaseComObject(byteStream);
> ```
> 
> I don't know how to calculate the BPM. But maybe you can check this out https://github.com/stengerh/foo_bpm

thanks a lot, I'll give it a try as soon I can :)

**Comment by emiliano84** [comment]
thanks a lot, I made it works like with few small changes :)
`
var stream = await file.OpenStreamForReadAsync();
IMFByteStream byteStream;
MediaFoundationInterop.MFCreateMFByteStreamOnStreamEx(stream.AsRandomAccessStream(), out byteStream);
MediaFoundationInterop.MFCreateSourceReaderFromByteStream(byteStream, null, out reader);
Marshal.ReleaseComObject(byteStream);
`

**Comment by wtywtykk** [comment]
Not until I searched the reference of MFCreateMFByteStreamOnStreamEx did I realize there's already something called StreamMediaFoundationReader..... So it's just unnecessary to write our own wrappers....

**Comment by emiliano84** [comment]
Amazing :) I didn't notice it neither, I switched to StreamMediaFoundationReader, thanks a lot
