### ISSUE TITLE
modifying volume of sound

### ISSUE THREAD

**Issue by jtorjo** [naudio/NAudio#679]
I want to modify the volume of a ISoundProvider.  Initially, I though just multiplying every float with the volume, i'd be fine.

However, it seems that for a lot of music, I should treat the volume exponentially. Like, volume 0.5 is pretty much the same as volume=1. So, to achieve true volume 50%, I would use 0.05

Is there a function that would convert "audible" volume to "internal" volume (the one where I'd multiply each float sample).

Anything to point me in the right direction? Thanks!

**Comment by ImBunky** [comment]
From what I have read, halving the perceived volume level would be somewhere between -8 to -10 dB. A noticeable change is usually to be considered around 3dB.

v2 = v1 * 10^(dB/20)

**Comment by jtorjo** [comment]
@ImBunky Thanks!

Is this the correct way to calculate the amplitude : https://stackoverflow.com/questions/2445756/how-can-i-calculate-audio-db-level ?

From that, I would compute the dB. Then, I would compute v2 = v1 * 10 ^ (dB/20)

Assuming the initial volume is -8dB, that would mean to get 50% of that , v2 = 0.398

Is this correct?

**Comment by ImBunky** [comment]
I think that I might be missing what your end goal is. I thought that you were trying to create a volume slider or something, in which case you wouldn't need to calculated the amplitude you just apply the appropriate dB change to your signal (-8 to -10) at the halfway point on the slider.

If you are trying to get different audio files to sound at relatively the same level (I am doing this in an app that I created), you want to look into utilizing replay gain. foobar2000 will calculated this and add it as a tag to the file, then you can plug that dB value into the above formula.

Of hand I don't know how the replay gain is calculated, but you have to analyze the whole file and it would take way to long to calculate on the fly (observe how long it takes foobar2000 to process a batch of files.

**Comment by jtorjo** [comment]
@ImBunky You're right!

I was overthinking it :D I may want to do this at a later time, but for now I should be fine with that formula. Thanks again!
