### ISSUE TITLE
Microphone And Speaker recording is throwing an exception

### ISSUE THREAD

**Issue by varz29** [naudio/NAudio#680]
Hi,
When i try to record microphone using **WaveInEvent** , iam getting the below error

Exception thrown: 'NAudio.MmException' in NAudio.dll
InvalidParameter calling waveInOpen.

               `var waveIn = new WaveInEvent();
                WaveFileWriter writer = null;
                writer = new WaveFileWriter(microphoneRecordingPath, waveIn.WaveFormat);
                waveIn.StartRecording();
                waveIn.DataAvailable += (s, a) =>
                {
                    writer.Write(a.Buffer, 0, a.BytesRecorded);
                    if (writer.Position > waveIn.WaveFormat.AverageBytesPerSecond * 30)
                    {
                        waveIn.StopRecording();
                    }
                };
                waveIn.RecordingStopped += (s, a) =>
                {
                    writer?.Dispose();
                    writer = null;
                    waveIn.Dispose();
                };
                `
And when i also try to use **WasapiLoopbackCapture** for recording speaker out i get a below exception
Exception thrown: 'System.ArgumentException' in NAudio.dll

               `WasapiLoopbackCapture capture = new WasapiLoopbackCapture();
                var writer = new WaveFileWriter(speakerRecordingPath, capture.WaveFormat);

                capture.DataAvailable += (s, a) =>
                {
                    writer.Write(a.Buffer, 0, a.BytesRecorded);
                    if (writer.Position > capture.WaveFormat.AverageBytesPerSecond * 20)
                    {
                        capture.StopRecording();
                    }
                    Console.Out.WriteLine("Data");
                };

                capture.RecordingStopped += (s, a) =>
                {
                    writer.Dispose();
                    writer = null;
                    capture.Dispose();
                    Console.Out.WriteLine("Recording stopped");
                };

                capture.StartRecording();`

They seem to work normally couple of days back , i dont understand why it isnt working now

Im using Windows 10 pro 1909

**Comment by varz29** [comment]
Hi @markheath  ,
What can be causing this exception , it was working normally till the last week and suddenly it started raising those exceptions.
I have tested with multiple windows PC's and some Pc's seems to work, could not find a pattern between them.
Can you please help me with this ?
Thank you

**Comment by varz29** [comment]
It is because of **Kaspersky Endpoint Security** software which i installed last week.

**Comment by markheath** [comment]
Glad you found the cause and thanks for sharing what it was
