### ISSUE TITLE
WaveInProvider.Read always returns the buffer length

### ISSUE THREAD

**Issue by wtywtykk** [naudio/NAudio#683]
Hi,
When I tried to get data from WaveIn with some polling mechanism:
```vb.net
            Dim Buf(4095) As Single
            Dim RetSize As Integer
            Do
                RetSize = SampleProvider.Read(Buf, 0, Buf.Length)
                Debug.WriteLine(RetSize)
                Dest.Write(Buf, 0, RetSize)
            Loop While RetSize
            Debug.WriteLine("ReadEnd")
```
It never get to the last line because SampleProvider.Read always returns 4096. 

After some debugging, I found bufferedWaveProvider.ReadFully in WaveInProvider.cs is set to true (default value used). This makes the Read method return non-zero even there are no data. I tried to set it to false, the issue is solved. 

My question is: is this by design or just someone forgot to set it to false? 

PS: I can't use the data length from WaveInEventArgs because the audio is resampled.

**Comment by markheath** [comment]
WaveInProvider is not recommended to be used for this reason as it's behaviour is surprising and what you want here depends on how you are consuming it. But generally set ReadFully to true if you are playing the audio as you are receiving it, and to false if you are recording to file.
