### ISSUE TITLE
NUGet Package

### ISSUE THREAD

**Issue by tomitrescak** [naudio/NAudio#686]
Hi, I am trying to use NAudio in my UWP application via NUGet pacage. It seems that this package is missing a lot of classes, including WaveIn and others. I tried to comile from source, but seems to fail.

**Comment by jwosty** [comment]
The way it's set up right now, NAudio includes different sets of classes for different targets. You can tell what it decides to include for any given target by peeking into the csproj: https://github.com/naudio/NAudio/blob/master/NAudio/NAudio.csproj

For example the UWP build lacks a lot of things due (usually) to the necessary APIs not being accessible from UWP. If you notice something that should actually be able to be implemented, definitely check back here! It's not hard to mess with the CSProj and the source files to include more things into targets; the code's already all there.

**Comment by markheath** [comment]
Yes, UWP does not allow you to call many of the APIs that NAudio uses, so it has a very limited set of functionality.
