### ISSUE TITLE
how to i can implement STFT with Naudio

### ISSUE THREAD

**Issue by hungcuiga1** [naudio/NAudio#699]
Hi everybody!
How to i can implement STFT with Naudio?
Thanks you for any answer!

**Comment by ToGoOrNotToGo** [comment]
NAudio has nothing to do with DSP and STFT. It is a library, e.g. for audio recording and playback. You can use NWaves for DSP:
https://github.com/ar1st0crat/NWaves

**Comment by hungcuiga1** [comment]
Thanks you.

**Comment by markheath** [comment]
Yes, NAudio has only limited DSP, with just a basic FFT implementation. I hadn't come across NWaves before - looks a really useful library
