### ISSUE TITLE
How to play a Sound on a specific Channel？

### ISSUE THREAD

**Issue by xzyyjy** [naudio/NAudio#70]
Is there any function or easy way to play a Sound on a specific Channel?
Such as:
play(int DeviceID, int ChannelID);

There are many mono audio data coming from different devices. Which I want to do is playing data in different channels (I'm planning to use the USB Sound Devices).

**Comment by markheath** [comment]
The `MultiplexingWaveProvider` and `MultiplexingSampleProvider` classes are intended for this use
