### ISSUE TITLE
ResamplerDmoStream or WaveFileWriter hangs up.

### ISSUE THREAD

**Issue by VicLo2020** [naudio/NAudio#706]
Hello. When transcoding an MP4 file, the program hangs without throwing an exception.
See comment in code.  [https://yadi.sk/d/YPTb9vQd0BVLqQ](url) - 1.mp4
Format 1.mp4 :

      Format                      : MPEG-4
      Format profile              : Base Media / Version 2
      Codec ID                    : mp42 (mp42/isom)
      File size                   : 235 KiB
      Duration                    : 33 s 684 ms
      Overall bit rate mode       : Variable
      Overall bit rate            : 57.3 kb/s
      Encoded date                : UTC 2012-07-22 17:48:31
      Tagged date                 : UTC 2012-07-22 17:48:31
      Writing application         : Fraunhofer IIS MPEG-4 Audio Encoder 03.02.11.01_MPEGScbr_SXPro

      Audio
      ID                          : 1
      Format                      : AAC
      Format/Info                 : Advanced Audio Codec
      Format profile              : HE-AACv2 / HE-AAC / LC
      Codec ID                    : 40
      Duration                    : 33 s 684 ms
      Source duration             : 33 s 855 ms
      Bit rate mode               : Variable
      Bit rate                    : 56.0 kb/s
      Maximum bit rate            : 59.5 kb/s
      Channel(s)                  : 2 channels / 1 channel / 1 channel
      Channel positions           : Front: L R / Front: C / Front: C
      Sampling rate               : 44.1 kHz / 44.1 kHz / 22.05 kHz
      Frame rate                  : 21.533 FPS (1024 SPF)
      Compression mode            : Lossy
      Stream size                 : 230 KiB (98%)
      Source stream size          : 231 KiB (98%)
      Encoded date                : UTC 2012-07-22 17:48:31
      Tagged date                 : UTC 2012-07-22 17:48:31

I have code:

                using (reader = new MediaFoundationReader("1.mp4"))
                using (resampledReader = new ResamplerDmoStream(reader,
                    new WaveFormat(
                        reader.WaveFormat.SampleRate,  // <---- 22050
                        reader.WaveFormat.BitsPerSample,
                        reader.WaveFormat.Channels)
                    ))
                using (WaveFileWriter waveWriter = new WaveFileWriter("1.wav", resampledReader.WaveFormat))
                {
                    resampledReader.CopyTo(waveWriter);  //   <---- At this point, it hangs.
                }

**Comment by markheath** [comment]
I've replied to this elsewhere - avoid CopyTo, or at least use the overload which constrains the number of bytes copied each chunk
