### ISSUE TITLE
Put several sine functions over each other

### ISSUE THREAD

**Issue by JoFo-IT** [naudio/NAudio#709]
I would like to put several sine functions over each other and output them as sound. On the output sound a FFT should be performed in another program.

I have now tried to create several signals with the "SignalGenerator" and to overlay them with the "WaveMixerStream32". I can't get the "SignalGenerator" converted to a "WaveStream", so I can mix them.

I also tried "RawSourceWaveStream". Unfortunately the sine was not clean enough.
https://github.com/naudio/NAudio/blob/master/Docs/RawSourceWaveStream.md

**Comment by markheath** [comment]
You should use MixingSampleProvider to mix together multiple SignalGenerators. And you should make sure you have enough headroom so you don't cause clipping.
