### ISSUE TITLE
Resampling from arbitrary sample rate to another by ACM Resampler

### ISSUE THREAD

**Issue by jakubbukaj** [naudio/NAudio#71]
Hello,
I am using ACM Resampler (WaveFormatConversionStream) for resampling. Source sample rate is 17896Hz, target sample rate is 44100Hz. When using WaveFormatConversionStream I am getting poor quality output. If I tried to resample to double sample rate (35792Hz) sound is great. I suppose that poor output quality for 44100Hz is result of aliasing,right? Is there any simple way to improve result quality?

When using MediaFoundationResampler for resampling 17896Hz -> 44100Hz result if perfect.

**Comment by markheath** [comment]
yes, ACM resampler does not appear to do anything to avoid aliasing. You'd need to implement your own filter, or just use MediaFoundationResampler which is good quality.
