### ISSUE TITLE
Exception opening mp4 file with AudiofileReader

### ISSUE THREAD

**Issue by mikemorton** [naudio/NAudio#72]
I have some code that works on my local dev system but fails on my Windows 2008 Server.  I have installed the Desktop Experience on the server and my code works for mp3 files but I get the following exception when I execute the `AudioFileReader` constructor with an mp4 file:

Error: System.Runtime.InteropServices.COMException (0xC00D5212): Exception from HRESULT: 0xC00D5212   at NAudio.MediaFoundation.IMFSourceReader.SetCurrentMediaType(Int32 dwStreamIndex, IntPtr pdwReserved, IMFMediaType pMediaType)   at NAudio.Wave.MediaFoundationReader.CreateReader(MediaFoundationReaderSettings settings)   at NAudio.Wave.MediaFoundationReader..ctor(String file, MediaFoundationReaderSettings settings)   at NAudio.Wave.AudioFileReader.CreateReaderStream(String fileName)   at NAudio.Wave.AudioFileReader..ctor(String fileName)

**Comment by markheath** [comment]
you also will need an MP4 Media Foundation Transform installed on your PC - I suspect there isn't one with Windows 2008 server.

**Comment by mikemorton** [comment]
Thank you Mark!  Your response + a bit of googling led me to [this superuser post](http://superuser.com/a/819386) which led me to [this kb download](https://www.microsoft.com/en-us/download/confirmation.aspx?id=13283) which solved my issue!
