### ISSUE TITLE
How to pause single Audio Track in MixingProvider with NAudio

### ISSUE THREAD

**Issue by DSaladinCH** [naudio/NAudio#721]
I'm using NAudio for a small Soundboard. For playing multiple sounds in different volumes, I'm using the MixingProvider.
For each Sound I'm creating a new AudioFileReader and add it to the MixingProvider.
The MixingProvider itself is initialized in the WaveOutEvent.

Now I would like to pause or stop a specific file/sound. How can I achieve this?
Because the AudioFileReader has no Pause or Stop function.
I only found a Pause and Stop function on the WaveOutEvent, which would pause or stop all sounds...

Is there anything I can do?

**Comment by markheath** [comment]
You'd have to make a pausing ISampleProvider that when it's pause flag is enabled, just returns 0 filled buffers from the Read method, and when it isn't, reads through from the source ISampleProvider

**Comment by DSaladinCH** [comment]
The MixingProvider deletes the source if I return 0 in the Read function.
Am I doing something wrong?

**Comment by markheath** [comment]
You have to return `count` and fill `buffer` with zeros:
```
for(var n = 0; n < count; n++)
    buffer[offset+n] = 0;
return count;
```
