### ISSUE TITLE
How to rebuild NAudio to .Net Framework 4.8?

### ISSUE THREAD

**Issue by SmokinLeather** [naudio/NAudio#722]
Hi All, I want to rebuild NAudio 1.10 with .Net 4.8 as the target framework. I used to just download the zip file, open it in VS and reset the target framework in the Project Properties dialog. It worked like a charm. But now the Target framework pulldown in the Project Properties dialog is disabled. Any idea how I can make it build to .Net 4.8 now.  Thanks for any suggestions.

PS I know it builds to .Net 3.5 but I really want 4.8 to pick up any .Net bug fixes and performance improvements.

**Comment by markheath** [comment]
You already benefit from the bugfixes and performance improvements of the framework you are running on, so I doubt this change will make any difference. But you could easily add net48 to the TargetFrameworks by editing the csproj directly

**Comment by SmokinLeather** [comment]
Yes I tried that. Changed  net35 to net48 on the vsproj file but the build failed.
Oh well, if I use the NAudio net35 build and it runs under the .net 4.8 libraries with my app, that's all I really wanted to achieve. 
Thanks Mark for the quick reply. Happy holidays.
