### ISSUE TITLE
MidiOut.Send(ChannelAfterTouchEvent) loses afterTouchPressure [with FIX]

### ISSUE THREAD

**Issue by brianavid** [naudio/NAudio#725]
This is a trivial bug, trivially fixed.

class ChannelAfterTouchEvent has no override for GetAsShortMessage(), so sending this event (in my code as a pass-thru) uses the base method MidiEvent.GetAsShortMessage() which effectively results in a zero value for the data byte - the afterTouchPressure.

The fix is trivially to add to ChannelAfterTouchEvent,cs:

        /// <summary>
        /// <see cref="MidiEvent.GetAsShortMessage" />
        /// </summary>
        public override int GetAsShortMessage()
        {
            return base.GetAsShortMessage() + (afterTouchPressure << 8);
        }

I have tested this fix in my own code, but am unsure about my GitHub access, so haven't tried a Pull Request.

**Comment by brianavid** [comment]
And a ToString() override would help too for diagnostic logging (midi monitor)

**Comment by markheath** [comment]
Good suggestions, I have added these
