### ISSUE TITLE
Support for NRPN

### ISSUE THREAD

**Issue by micdah** [naudio/NAudio#73]
As far as I can tell by looking at the code, there is no support for NRPN control change messages - are there any plan to include this support at some time?

**Comment by markheath** [comment]
I'm not currently working in that area at the moment. Will gladly take any contributions though

**Comment by micdah** [comment]
Sorry for not responding - I ended up implementing it on top of another midi framework; midi dot net, as another developer had already added SysEx to this library - so I figured having both SysEx and NRPN support would be a greater asset.

If it can provide any help, you can check out my fork at https://github.com/micdah/midi-dot-net
