### ISSUE TITLE
Not playing file

### ISSUE THREAD

**Issue by sachinkanadia** [naudio/NAudio#734]
Hi There,

Here is my code:

```
var waveOut = new WaveOut();
var file = new Mp3FileReader("[file name + path here]");
waveOut.Init(file);
waveOut.Volume = 1;
waveOut.Play();
```

I have checked that the file path exists and that sound is working on my PC all is fine.
When I check the PlaybackState it is set to "Playing" and no exception is raised.
No sound plays.

Please can could you help in pointing out what I'm doing wrong here.

Many Thanks

**Comment by sachinkanadia** [comment]
Solved. Didn't block the thread hence play back was cut short.

**Comment by BryanT423** [comment]
Hello, I am having the same issues as you did. What do you mean by 'block the thread'? My program is executing but it ends as soon as I start it and says it has completed.

**Comment by BryanT423** [comment]
Figured it out. Thanks. I was looking in the wrong place.
https://github.com/naudio/NAudio/blob/master/Docs/PlayAudioFileConsoleApp.md
