### ISSUE TITLE
Playing 1 input file to multiple output devices simultaneously

### ISSUE THREAD

**Issue by sachinkanadia** [naudio/NAudio#736]
Hi All,

I have managed to create a rough C# program that plays to multiple output devices using NAudio. The problem is that the music is slightly out of sync. Is there a way I can achieve 'perfect' synchronicity between the output devices that are playing the same file?

**Comment by markheath** [comment]
It's a very challenging problem to solve well. If I needed to do this, I'd try to use as low a latency as possible, and start all devices as close to the same moment as possible. I might even try to make a special `IWaveProvider` implementation that knew about where the other devices were up to so could skip ahead if necessary.

**Comment by sachinkanadia** [comment]
@markheath Yes I'm using a ManualResetEvent to allow multiple blocking threads to continue in order to start playing the track. I have not tried using low latency so I will give this a go. I'm assuming that you would use the position property to inspect where the track is up to?

**Comment by markheath** [comment]
Yes, that's also a good idea to use the IWavePosition interface as it should give the most accurate indication of exactly how far through playback each device is

**Comment by sachinkanadia** [comment]
Hi @markheath

I could have swore I saw the implementation of WaveOut and WaveOutEvent on Github a few days ago? I can't see this now. Has it been removed?

Thanks Sachin

**Comment by markheath** [comment]
Some things have moved around with the release of NAudio 2 yesterday, but all the code is still here

**Comment by sachinkanadia** [comment]
Ah my bad, I can see the implementation of WaveOut and WaveOutEvent now. Indeed they have moved.

Thank you

**Comment by sachinkanadia** [comment]
Hi @markheath

I'd like to be able to filter the device capabilities by determining whether the device is connected by Bluetooth.

Is this possible and if so how would I achieve this?

Too add, I notice that the Product Id from the device capabilities is the same Guid for all Bluetooth connected devices. This would seem like a good starting point but I don't know what the Product Id is, and how I would obtain this Guid from the system.

**Comment by sachinkanadia** [comment]
Hi @markheath 

Hope all is well. 

I have written an Auto-Sync program that will sync a number of audio file readers to the master audio file reader as they are playing. It works fine until setting the stream position which lags a little every 3 executions of the Timer. Other executions work well, but there seems to be a something happening somewhere which is causing the consistent lag. The lag is noticeable until the next timer execution which fixes the previous execution. Would you know what could be causing this lag? It maybe a lock somewhere, the stream buffering or something completely different? Here is my code for the Auto-Sync:

```
public void AutoSync(            
            IDictionary<int, NAudioPlayItem> playItems,
            IWavePosition getMasterPosition,
            Func<long> getMasterStreamPosition, 
            Func<NAudioPlayItem, bool> isMasterPlayItem
        )
        {
            foreach (var pi in playItems)
            {
                if (isMasterPlayItem(pi.Value))
                    continue;
                var playerPosition = pi.Value.Player.GetPosition();
                var masterPosition = getMasterPosition.GetPosition();
                if (playerPosition == masterPosition)
                {
                    Debug.WriteLine("**STANDARD AUTO-SYNC CANCELLED. PLAYER POS: {0}, MASTER POS: {1}**", playerPosition, masterPosition);
                    continue;
                }
                pi.Value.Reader.StreamPosition = getMasterStreamPosition();
                Debug.WriteLine("**STANDARD AUTO-SYNC APPLIED. PLAYER POS: {0}, MASTER POS: {1}**", playerPosition, masterPosition);
            }
        }
```

**Comment by sachinkanadia** [comment]
Hi All,

Would anyone have an idea about this?
