### ISSUE TITLE
WasapiLoopbackCapture fails to start with a WaveFormat that has more than 2 channels 

### ISSUE THREAD

**Issue by veler** [naudio/NAudio#737]
Hello,

I'm desperately trying to record what gets out of my speakers. For this, I'm using a WasapiLoopbackCapture with default constructor.

```csharp
_audioCapturer = new WasapiLoopbackCapture();
```

Then simply do the following on a background thread:

```csharp
_audioCapturer.DataAvailable += AudioCapturer_DataAvailable;
 _audioCapturer.RecordingStopped += AudioCapturer_RecordingStopped;
_audioCapturer.StartRecording();
```

However I'm getting a `COMException` `0x88890008`, apparently corresponding to a [AUDCLNT_E_UNSUPPORTED_FORMAT](https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudioclient-initialize).

After investigation and try, I figured out the issue is linked to the number of channel. I have an Alienware Aurora R10. The sound card supports up to 8 channels (left, right, rear, back, center...etc).
I don't know if that matters, but I only plugged a stereo speaker (left & right) to the PC.
I figured out with a small hack that creating a `WasapiCapture` with a IEEE format with only 2 channels (even if the `MMDevice`'s MixFormat indicates 8) fixes the issue.

**My questions are:**
1. Is it expected from the WASAPI api?
2. Would a WaveFormat with 8 channels work if I actually plugged speaker(s) supporting 8 channels?
3. What would be the best practice here?

Thanks in advance, and thanks for this library :-)

**Comment by markheath** [comment]
Working with more than 2 channels is something I've rarely needed to do, and when I do I always use ASIO. So afraid I don't know what you need to do to persuade WASAPI to support additional channels. I'm sure it must be possible.

**Comment by veler** [comment]
Oh, I thought I answered here, sorry for the delay.

I ended up doing a loop and try many configurations until it works.

```c#
        private WasapiSystemSoundCapturer FindAppropriateSoundCapturer()
        {
            int channels = _device.AudioClient.MixFormat.Channels;

            for (; channels > 0; channels--)
            {
                try
                {
                    using var audioCapturer = new WasapiSystemSoundCapturer(_device, UseWasapiEventSync, channels);

                    // We may crash here based on the channel count.
                    audioCapturer.StartRecording();

                    break; // succeeded.
                }
                catch
                {
                }
            }

            if (channels == 0)
            {
                throw new Exception("Unable to record the operating system sound.");
            }

            return new WasapiSystemSoundCapturer(_device, UseWasapiEventSync, channels);
        }

    public sealed class WasapiSystemSoundCapturer : WasapiCapture
    {
        public WasapiSystemSoundCapturer(MMDevice mDevice, bool useEventSync, int channels)
            : base(mDevice, useEventSync)
        {
            var format = mDevice.AudioClient.MixFormat;

            WaveFormat = WaveFormat.CreateIeeeFloatWaveFormat(
                format.SampleRate,
                channels: channels);
        }

        protected override AudioClientStreamFlags GetAudioClientStreamFlags()
        {
            return AudioClientStreamFlags.Loopback;
        }
    }
```
