### ISSUE TITLE
2.0.0 VorbisWaveReader no longer supports ToWaveProvider?

### ISSUE THREAD

**Issue by Noobicle** [naudio/NAudio#739]
Hello,

I've just upgraded to 2.0.0 and have hit a snag;

I used to be able to call ToWaveProvider() to then pass it to a SampleChannel. In 2.0.0 it appears this function is no longer available. Little bit lost how to achieve this now. 

var oggReader = new NAudio.Vorbis.VorbisWaveReader(fileName).ToWaveProvider();

**Comment by markheath** [comment]
It's still in NAudio ([here](https://github.com/naudio/NAudio/blob/master/NAudio.Core/Wave/WaveExtensionMethods.cs)), so not entirely sure why that would be. But will try to get NAudio.Vorbis updated to the latest which might help.
