### ISSUE TITLE
Create interfaces for MidiIn and MidiOut

### ISSUE THREAD

**Issue by residuum** [naudio/NAudio#77]
I am currently developing a [C# binding for libjack](https://github.com/residuum/JackSharp), and have started implementing a `IWaveIn` and `IWavePlayer` for binding it with NAudio.

libjack also has MIDI capabilities, and it would be great, if NAudio had interfaces similar to those for audio to implement, so that programmers can use NAudio and libjack e.g. to develop MIDI enabled synthesizers with low latency on Windows, Linux and Mac OS X.

**Comment by markheath** [comment]
yes, that's a decent idea but to be honest, the MIDI in / out in NAudio is very rudimentary. Most of the effort went into supporting read/write of MIDI files.
