### ISSUE TITLE
cross_platfrom

### ISSUE THREAD

**Issue by usef1370** [naudio/NAudio#771]
Is NAudio cross Platfrom?

**Comment by markheath** [comment]
Many parts of NAudio are wrappers for Windows audio APIs so those are not cross platform. This includes the audio playback and recording APIs.
But there are still a lot of things that you can use cross platform (e.g. reading/writing WAV files, and all the audio mixing/processing)

**Comment by RigoLigoRLC** [comment]
Should've been written to the README. We were developing a Windows/macOS audio application and didn't first think of that... (ASIO support reads driver names from registry. duh)
