### ISSUE TITLE
Crash in WasapiCapture when device is unplugged

### ISSUE THREAD

**Issue by loics2** [naudio/NAudio#772]
I have implemented something similar to ["How to record and play audio at the same time with NAudio"](https://markheath.net/post/how-to-record-and-play-audio-at-same), but using a USB audio device, `WasapiCapture` and `IWaveProvider`. Everything works correctly until I unplug the device.

When the device is unplugged, an exception seems to be thrown in the capture thread of `WasapiCapture`, here's the stack trace :

```
System.IO.FileNotFoundException
  HResult=0x80070015
  Message=Non implémenté

Non implémenté

  Source=NAudio.Wasapi
  StackTrace:
   at NAudio.CoreAudioApi.Interfaces.IAudioClient.Stop()
   at NAudio.CoreAudioApi.AudioClient.Stop()
   at NAudio.CoreAudioApi.WasapiCapture.CaptureThread(AudioClient client)
   at NAudio.CoreAudioApi.WasapiCapture.<StartRecording>b__35_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
(`Non implémenté` means `Not implemented`)

It looks like the call to [`client.stop()` in the `finally` block of `CaptureThread`](https://github.com/naudio/NAudio/blob/fb35ce8367f30b8bc5ea84e7d2529e172cf4c381/NAudio.Wasapi/WasapiCapture.cs#L220) fails, and I cannot catch the exception.

**Comment by JacqiPan** [comment]
@loics2 When an audio endpoint device is unplugged, the MMDevice.[AudioClient](https://github.com/naudio/NAudio/blob/master/NAudio.Wasapi/CoreAudioApi/AudioClient.cs) is "disposed", along with its [AudioClient.AudioCaptureClient](https://github.com/naudio/NAudio/blob/master/NAudio.Wasapi/CoreAudioApi/AudioCaptureClient.cs) child. The [WasapiCapture ](https://github.com/naudio/NAudio/blob/master/NAudio.Wasapi/WasapiCapture.cs) client rely on these two classes to work.

WasapiCapture on the other hand, does not detect when the AudioClient is disposed, meaning that both `DoRecording(AudioClient client)` and `client.Stop()` will throw an exception once the device is disconnected. 
```cs
  private void CaptureThread(AudioClient client)
        {
            Exception exception = null;
            try
            {
                DoRecording(client);
            }
            catch (Exception e)
            {
                exception = e;
            }
            finally
            {
                client.Stop(); // Since AudioClient client is null, client.Stop() fails
            }
            captureThread = null;
            captureState = CaptureState.Stopped;
            RaiseRecordingStopped(exception);
        }
```


To circumvent this problem, you could try to use a try/catch block and/or a guard clause within the` WasapiCapture.DataAvailable` event to handle the disconnection.

**Comment by loics2** [comment]
I don't really see where I could put a try-catch in `OnDataAvailable`, it's called by `DoRecording`, I won't catch anything.

I could do some dubious things to get the `audioClient` private variable and check if it's null, but I don't think it's a good solution.

**Comment by loics2** [comment]
After some debugging, I don't think it has to do with the `client` being null. If I make something like this :

```cs
// ...
finally
{
    if(client != null)
        client.Stop();
}
// ...
```

it still crashes with the same exception. If I add a `Thread.Sleep(500)`, it crashes way less, which makes me think there's some kind of race condition or something like that. For now, I just wrapped `client.Stop()` in a try-catch and it works correctly.

Should I investigate further on this issue, or is this try-catch solution enough?

**Comment by JacqiPan** [comment]
Since AudioClient is a COM object, it simply loses its reference as soon as it's unplugged. So it's not technically null and will always throw an exception when you try to access it after the endpoint device disconnects, like with `if (client != null)` or if `(client.Equals(null))`. The try-catch solution works, since it catches the exception for AudioClient just like it did within `DoRecording()`

I used something like this:
```cs
 private void OnDataAvailable(object sender, WaveInEventArgs waveInEventArgs)
    {
        try
		{
			if (AudioClient != null) // Will throw as soon as the device is unplugged
				bufferedWaveProvider.AddSamples(waveInEventArgs.Buffer,0, waveInEventArgs.BytesRecorded);
		}
		catch
		{
			WasapiCaptureClient.Stop();
			WasapiCaptureClient -= OnDataAvailable;
		}
		
    }
```

**Comment by loics2** [comment]
Oh I wasn't aware the audio client was accessible from the `MMDevice`, and I store it in a variable somewhere. It works correctly, thanks!

**Comment by wojciesh** [comment]
@JacqiPan @loics2 
>                 if (CaptureMMDevice.AudioClient != null) // Will throw as soon as the device is unplugged

Using that code in this way will make a new Audio Client on each check, see the source:
```
// Summary:
//     Audio Client Makes a new one each call to allow caller to manage when to dispose
//     n.b. should probably not be a property anymore
public AudioClient AudioClient => GetAudioClient();
```
https://github.com/naudio/NAudio/blob/a106da4eed61774e9bd3eda1fa7922581aee04e1/NAudio.Wasapi/CoreAudioApi/MMDevice.cs#L106
