### ISSUE TITLE
Why working with string file path? Is there any way to work with stream?

### ISSUE THREAD

**Issue by jcvegan** [naudio/NAudio#780]
I saw that readers expect a file path. 
Why is that? Isn't better to expect a Stream (can be FileStream or MemoryStream), I think it is more flexible

**Comment by Panda-Sharp** [comment]
I'm not really sure if it can solve your issue, but take a look here
https://github.com/naudio/NAudio/issues/675

**Comment by jcvegan** [comment]
@Panda-Sharp Thx 👍🏽

**Comment by samkuls** [comment]
Hi,How to pass blob instead filepath while converting wave stereo to mono?
