### ISSUE TITLE
WaveInEvent does not record audio in .Net 5

### ISSUE THREAD

**Issue by Hromon** [naudio/NAudio#791]
o/
I wrote the following code:
![image](https://user-images.githubusercontent.com/29508584/121763076-e463f180-cb41-11eb-9fda-bc80b03607fe.png)
This code works on the .Net Framework, but does not work on .Net 5. WaveInEvent does not write (its buffers are empty) and does not generate an event about data availability for reading, respectively.  :C

**Comment by Zintom** [comment]
Why are you clearing the `BufferedWaveProvider` each time there is data available? From your example you appear to be wanting to play back audio that has been recorded by the Default Mic Device, `BufferedWaveProvider` is a circular buffer so all you need to do is make its buffer big enough to fit a few seconds of audio in it and so long as you are consuming from the buffer as quickly as you are putting data in, it will never fill up.

As for why you're not getting any data, are you sure the default input device is setup correctly? i.e is the default set to your microphone. Alternatively you can manually select the audio device using the `MMDeviceEnumerator.EnumerateAudioEndPoints(..)` API.

**Comment by Hromon** [comment]
> Why are you clearing the `BufferedWaveProvider` each time there is data available? From your example you appear to be wanting to play back audio that has been recorded by the Default Input Device, `BufferedWaveProvider` is a circular buffer so all you need to do is make its buffer big enough to fit a few seconds of audio in it and so long as you are consuming from the buffer as quickly as you are putting data in, it will never fill up.
> 
> As for why you're not getting any data, are you sure the default input device is setup correctly? i.e is the default set to your microphone. Alternatively you can manually select the audio device using the `MMDeviceEnumerator.EnumerateAudioEndPoints(..)` API.

Yes, I'm sure, because if you put a breakpoint, then I will never come to WaveIn_DataAvailable.

As for the default input device - this code was written in .Net 5 and .Net framework in one solution and was run sequentially. The result is that the framework works, Core 5 does not.

**Comment by Zintom** [comment]
Hmm, very possibly related to #789 or some unknown bug causes by the 5.0.7 patch.

One other thing to try is to enlarge BufferMilliseconds to something a bit bigger, maybe the buffer isn't large enough to store the data recorded (honestly that's just a total guess but may be worth checking).

**Comment by Hromon** [comment]
> Hmm, very possibly related to #789 or some unknown bug caused by the 5.0.7 patch.
> 
> One other thing to try is to enlarge BufferMilliseconds to something a bit bigger, maybe the buffer isn't large enough to store the data recorded (honestly that's just a total guess but may be worth checking).

I tryid, but it not work

**Comment by Zintom** [comment]
Would you mind trying with the new 2.0.1 (NuGet) patch please.

**Comment by Hromon** [comment]
> Would you mind trying with the new 2.0.1 (NuGet) patch please.

Work, thanks.
