### ISSUE TITLE
RPG style dialog sounds

### ISSUE THREAD

**Issue by MaxDeBy** [naudio/NAudio#799]
Hello

For a project of mine I need to play a sound file, refered to as blip in this context. That sound is played while a character's dialog is printed on the screen. That dialog is printed character by character and the blip should play every 3rd character. That system already exists but apparently lags on slower CPUs so now I'm trying to use the MixingSampleProvider to keep the sound channel (WasapiOut in this case) open and just add the blip samples when they're being played. 

In theory it works but there are 2 flaws I noticed.
1) It takes a small amount of time before the first blip is played. It's less than a second but it's noticable. This is also the reason, I decided not to use the MixingSampleProvider for normal sound effects as timing them is hard with that slight delay at the beginning. For whatever reason, it's apparently faster to create a WasapiOut, Init it with a RawSourceWaveStream and then play it, rather than adding it to the MixingSampleProvider.
2) The blips are short but long enough to overlap if they are played every 3rd character. However, with the MixingSampleProvider, they just queue. The next blip is played when the previous one finished.

What I'm doing is: Create a RawSourceWaveStream from a byte array, put it in a MonoToStereoProvider16 in case it's mono,
then add it to the MixingSampleProvider using AddMixerInput. 

How can I achieve the goal (playing all blips in the same sound channel while keeping it open if no blip is playing), but still eliminate the two issues. Especially 2).

**Comment by markheath** [comment]
Sorry for the delay replying. There will always be some latency due to buffer sizes (which NAudio does let you control). For these types of application I recommend a "fire and forget" audio engine, a bit like I describe here: https://www.markheath.net/post/fire-and-forget-audio-playback-with
