### ISSUE TITLE
Creating mp4/m4a file

### ISSUE THREAD

**Issue by KeithLJones** [naudio/NAudio#8]
Hi
I'm trying to create an m4a file, but have been unable to find the necessary method. So far I have an AAC file, but need to wrap it in the M4A container. Is this supported in NAudio and if so are there any samples or docs relating to this.

Cheers

Keith

**Comment by markheath** [comment]
NAudio basically exposes the ability to use the Media Foundation API in C#. As I understand it, when you create a Media Foundation "sink writer" it should choose an appropriate container based on the file extension you pass in. So for AAC you can use AAC or MP4/M4A, and it should create the correct format. Note that not all containers are supported on all versions of Windows. For example, on Windows 7 you can't make AAC files, but you can make MP4 with AAC in it.
