### ISSUE TITLE
Current MidiConverter.cs file generates error on build

### ISSUE THREAD

**Issue by realmgate** [naudio/NAudio#81]
I just updated my local repo with the latest code, and on solution build the following error appears:

```
2>C:\...\NAudio\MidiFileConverter\MidiConverter.cs(404,25,404,26): error CS1525: Invalid expression term '.'
2>C:\...\NAudio\MidiFileConverter\MidiConverter.cs(404,26,404,39): error CS1003: Syntax error, ':' expected
```

On examination, there appears to be a question mark in the code at line 404 in `MidiConverter.cs` that shouldn't be there:

```
401  private bool IsEndTrack(MidiEvent midiEvent)
402  {
403      var meta = midiEvent as MetaEvent;
404      return meta?.MetaEventType == MetaEventType.EndTrack;
405  }
```

Removing the question mark results in a successful build.

**Comment by NeoLegends** [comment]
This is the new C# 6-syntax. You should update your VS / C#-Compiler, I guess.

**Comment by markheath** [comment]
Yes, I should update the sln file to be VS2015

**Comment by realmgate** [comment]
Okay.  I was trying it in VS2013, so maybe that's the reason for the problem.  I'm updating VS2015 now and I'll try it again.

**Comment by realmgate** [comment]
Yeah, just to confirm that there are no issues at all with the original source in VS2015.  Thanks guys.
