### ISSUE TITLE
Naudio Recording.  Where is the Wav file written to BEFORE you close it?

### ISSUE THREAD

**Issue by CTI-Tim** [naudio/NAudio#815]
Trying to find a way to save any recordings that were made and the computer crashed.  Watching the file as it records, it's not actually writing into the file specified but it does that at the end when you close the file.  so where is it really going to and can I control that?

 RecordWriter = new WaveFileWriter(FilePath, CaptureInstance.WaveFormat);
 
 WaveFileWriter  is not writing the file to the Filepath specified UNTIL its instance is disposed of.  which means it's actually writing to a temp file somewhere.   Where can I specify that or uncover that location?   I am looking at finding that data and trying to recover it if/when a application is crashed by the user or the operating system does a crash.
 
 Or is there a better writer that will actually wite to the specified file without using a temporary location?

**Comment by markheath** [comment]
There is no temporary location but .NET buffers writes to files for performance reasons. You can call the `Flush` method at any point to ensure that the data is written to disk
