### ISSUE TITLE
Impossible to use nAudio with Docker

### ISSUE THREAD

**Issue by pmengal** [naudio/NAudio#817]
The error message below disappear if I remove all references to nAudio.

`It was not possible to find any compatible framework version`
`The framework 'Microsoft.WindowsDesktop.App', version '3.1.0' was not found.`
`  - No frameworks were found.`
``
`You can resolve the problem by installing the specified framework and/or SDK.`
``
`The specified framework can be found at:`
`  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=3.1.0&arch=x64&rid=win10-x64`
`The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. ``This may be expected if the target process did not run on .NET Core.`
`The program '[1648] dotnet.exe' has exited with code -2147450730 (0x80008096).`

**Comment by pmengal** [comment]
@jwosty thanks for your reply. Yes, I figured it out and started to use FFMPEG instead which provided the results I was looking for.

**Comment by jwosty** [comment]
Good, I’m glad you figured it out!

This can probably closed as resolved then
