### ISSUE TITLE
WASAPI built-in resampler: Add AUDCLNT_STREAMFLAGS_AUTOCONVERTPCM flag

### ISSUE THREAD

**Issue by feoff3** [naudio/NAudio#819]
I discovered that there is a built-in resampler in WASAPI that allows to use any wave format with WASAPI.
It is turned on by AUDCLNT_STREAMFLAGS_AUTOCONVERTPCM flag , see
https://docs.microsoft.com/en-us/windows/win32/coreaudio/audclnt-streamflags-xxx-constants
The flag is succesfully used in miniaudio and portaudio C++ open source libraries. 

Adding this option to NAudio WASAPI implementation would greatly simplify the life of Windows-based developers as manual resampling is cumbersome and sometimes results in pretty much unpredictable results. Use of something built-in instead looks like a more reliable and simple option.

I was wondering if it works in NAudio. I was able to change the NAudio code inserting the flag into NAudio lib+disabling IsFormatSupported() call for NAudio.Wasapi/WasapiCapture.cs. 
This allowed me to specify any format for WasapiCapture even if it is not supported by the endpoint device. 

For this, I changed  AudioClientStreamFlags() code:
```
        protected AudioClientStreamFlags GetAudioClientStreamFlags()
        {
            // autoresampling flags. works starting from Win8
            uint AUDCLNT_STREAMFLAGS_AUTOCONVERTPCM = 0x80000000;
            uint AUDCLNT_STREAMFLAGS_SRC_DEFAULT_QUALITY = 0x08000000;
            uint streamFlags = AUDCLNT_STREAMFLAGS_AUTOCONVERTPCM | AUDCLNT_STREAMFLAGS_SRC_DEFAULT_QUALITY;
            return (AudioClientStreamFlags)streamFlags;
        }
```

and deleted IsFormatSupported() check from https://github.com/naudio/NAudio/blob/fb35ce8367f30b8bc5ea84e7d2529e172cf4c381/NAudio.Wasapi/WasapiCapture.cs#L127

Let me know how to proceed: propose a patch or let you incorporate this flag in a way you prefer (e.g. having a separate class, or  whatever that suits NAudio code design)

**Comment by markheath** [comment]
Wow, didn't know that was in there, and would be great to get in there (especially if this works for playback too)

In terms of fitting with NAudio design - a couple of thoughts
1. I'd probably make auto-resampling optional but on by default. e.g. a class property that you can change before beginning capture
2. I still think you need to check if the format is supported since the user could have asked for something unusual like MP3 format

**Comment by feoff3** [comment]
Thanks for sharing the thoughts:
1. Agreed. I think changing the default behaviour posses some risk in terms of backward-compatbility but I can hardly imagine a client code that seeks for the best fitting format by simply trying out all the possible formats within a loop or something.  
2. Well, a sanity check for PCM\IEEE floating is needed indeed.

**Comment by markheath** [comment]
Sorry it took me so long to get round to this, but finally have implemented it and it will be in the next NAudio release. Many thanks for making me aware of this capability - it makes WASAPI so much easier to work with. 
Sadly, you can't use it with WASAPI exclusive mode playback, but that's not too surprising.
