### ISSUE TITLE
AudioFileReader that reads a stream

### ISSUE THREAD

**Issue by ghosttie** [naudio/NAudio#826]
I'm writing a web app where people can upload audio files.

The first thing I want to do is check the audio file's length, so I believe I do this by creating an AudioFileReader and getting TotalTime.

The problem that I have is that the AudioFileReader (and MediaFoundationReader) constructor only takes a filename, not a stream, and what I have is the stream that was uploaded.  I could write the stream out to a temporary file, but it seems excessive to add that much disk IO just to get the audio length.

**Comment by Panda-Sharp** [comment]
check here :)

https://github.com/naudio/NAudio/issues/675

**Comment by ghosttie** [comment]
That's perfect, thank you!

**Comment by EitanRa** [comment]
If anybody other faces this issue, there is a good & simple solution - use some reflection to create an instance of an AudioFileReader with Stream, if you only know the type of the file (".wav", ".mp3", ".aif" or ".aiff"). Just paste this class somewhere in your code:

`
namespace NAudio.Extensions
{
    public static class Extensions
    {
        public static AudioFileReader GetAudioFileReaderFromStream(Stream stream, string fileExt)
        {
            try
            {
                AudioFileReader reader = (AudioFileReader)FormatterServices.GetUninitializedObject(typeof(AudioFileReader));

                // this is how the constructor looks
                //lockObject = new object();
                //FileName = fileName;
                //CreateReaderStream(fileName);
                //sourceBytesPerSample = readerStream.WaveFormat.BitsPerSample / 8 * readerStream.WaveFormat.Channels;
                //sampleChannel = new SampleChannel(readerStream, forceStereo: false);
                //destBytesPerSample = 4 * sampleChannel.WaveFormat.Channels;
                //length = SourceToDest(readerStream.Length);

                Type type = reader.GetType();
                type.GetField("lockObject", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(reader, new object());
                var readerStream = GetWaveStream(stream, fileExt);
                type.GetField("readerStream", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(reader, readerStream);
                var sbps = readerStream.WaveFormat.BitsPerSample / 8 * readerStream.WaveFormat.Channels;
                type.GetField("sourceBytesPerSample", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(reader, sbps);
                var sampleChannel = new SampleChannel(readerStream, forceStereo: false);
                type.GetField("sampleChannel", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(reader, sampleChannel);
                var dbps = 4 * sampleChannel.WaveFormat.Channels;
                type.GetField("destBytesPerSample", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(reader, dbps);
                var std = dbps * (readerStream.Length / sbps);
                type.GetField("length", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(reader, std);

                return reader;
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                return null;
            }
        }

        private static WaveStream GetWaveStream(Stream stream, string fileExt)
        {
            WaveStream readerStream = null;
            if (fileExt.Equals(".wav", StringComparison.OrdinalIgnoreCase))
            {
                readerStream = new WaveFileReader(stream);
                if (readerStream.WaveFormat.Encoding != WaveFormatEncoding.Pcm && readerStream.WaveFormat.Encoding != WaveFormatEncoding.IeeeFloat)
                {
                    readerStream = WaveFormatConversionStream.CreatePcmStream(readerStream);
                    readerStream = new BlockAlignReductionStream(readerStream);
                }
            }
            else if (fileExt.Equals(".mp3", StringComparison.OrdinalIgnoreCase))
            {
                if (Environment.OSVersion.Version.Major < 6)
                {
                    readerStream = new Mp3FileReader(stream);
                }
                else
                {
                    readerStream = new StreamMediaFoundationReader(stream);
                }
            }
            else if (fileExt.Equals(".aiff", StringComparison.OrdinalIgnoreCase) || fileExt.Equals(".aif", StringComparison.OrdinalIgnoreCase))
            {
                readerStream = new AiffFileReader(stream);
            }
            else
            {
                readerStream = new StreamMediaFoundationReader(stream);
            }
            return readerStream;
        }
    }
}
`

and then you can use it like this:
`AudioFileReader reader = NAudio.Extensions.Extensions.GetAudioFileReaderFromStream(myStream, ".wav");`
