### ISSUE TITLE
Suggestion: Don't allow issues that are code help questions

### ISSUE THREAD

**Issue by jwosty** [naudio/NAudio#833]
There's a lot of issue here which I would consider off-topic. Many people are asking questions about how to use the library in the form of GH issues, which causes a lot of noise and makes it hard to find the *real* issues pertaining to NAudio itself. These can be valid questions, I just don't think they belong here.

If we were to disallow Q&A style issues on this repo and instead redirect them somewhere more appropriate (i.e. StackOverflow or make a separate repo), it would benefit the quality of this repo and do more to encourage contributions (as there will be less wading through the issues to find something to fix).

I would recommend only allowing issues that are bug reports or direct feature suggestions. For example, a bad issue is one titled "How can I do XYZ in NAudio?" while a better one would be "Please support XYZ in NAudio."

**Comment by KvanTTT** [comment]
It is also possible to use [GitHub Discussions](https://docs.github.com/en/discussions) for Q&A style issues.

**Comment by Zintom** [comment]
GH Discussions looks like the way to go with this.

**Comment by markheath** [comment]
The main issue is that I don't really have time to stay on top of all the communication I get about NAudio. But am happy to turn on GitHub discussions if people think it would help. I haven't looked into discussions too much, but could help if its easy to turn issues into discussions.

**Comment by markheath** [comment]
Discussions are enabled now, so we can see how that goes.
