### ISSUE TITLE
Streaming youtube video through naudio?

### ISSUE THREAD

**Issue by JackRyder** [naudio/NAudio#84]
Hi!

I'm currently working with Naudio and VideoLibrary in order to make a youtube player that can play audio through a different audio device. I've figured out how to change the audio output, but playing using the videolibrary stream is really difficult, do you have any implementation on how to do this?

**Comment by markheath** [comment]
I'm afraid I don't know how this can be done

**Comment by Emyr42** [comment]
One option would be to create a windows device driver which acts as an audio output device, runs the stream through whatever filters you want then outputs to other "real" audio outputs.
