### ISSUE TITLE
How to build the dll?

### ISSUE THREAD

**Issue by AndRo-Marian** [naudio/NAudio#842]
[Log.txt](https://github.com/naudio/NAudio/files/7206449/Log.txt)

**Comment by hansmbakker** [comment]
Please use a gist instead of making us download the txt file.

Also, it is helpful if you describe the steps you took and the version of your Visual Studio etc. instead of just dumping your build log.

**Comment by markheath** [comment]
Make sure you have the latest Dev tools and SDKs. I recommend Visual Studio 2022
