### ISSUE TITLE
Hardware Mic Mute Status

### ISSUE THREAD

**Issue by brandonUcw** [naudio/NAudio#846]
Using a USB microphone such as a Jabra and a few other devices, some applications are capable of detecting the microphone mute state when it is toggled by the hardware's physical mute button.
I am looking to detect when the device has its mute state toggled.
Here's some sample code I tried using:

`static void Main()
        {
                NAudio.CoreAudioApi.MMDeviceEnumerator MMDE = new NAudio.CoreAudioApi.MMDeviceEnumerator();              
                NAudio.CoreAudioApi.MMDeviceCollection DevCol = MMDE.EnumerateAudioEndPoints(NAudio.CoreAudioApi.DataFlow.Capture, NAudio.CoreAudioApi.DeviceState.Active);
                //Loop through all devices
                foreach (NAudio.CoreAudioApi.MMDevice dev in DevCol)
                {
                        Console.WriteLine("Volume of " + dev.FriendlyName + " is " + dev.AudioEndpointVolume.Mute.ToString());
                }
                Console.ReadLine();
        }`

**Comment by markheath** [comment]
afraid I don't have any expertise in this area. Might be worth checking the EarTrumpet project to see if they can detect hardware mute - https://github.com/File-New-Project/EarTrumpet
