### ISSUE TITLE
Looking for a simple noise suppressor

### ISSUE THREAD

**Issue by billsheh** [naudio/NAudio#850]
Hi, Mark,

I am looking for a simple noise suppressor to remove noise in the recorded audio. Can you advise how to do that with NAudio?

Thanks,

Bill

**Comment by markheath** [comment]
I'm afraid NAudio doesn't include a noise suppression algorithm. But using a gate effect can make a big difference. There is a very simple gate example in the NAudio codebase but it's not exposed easily for usage unfortunately as it was never properly tested. Other options include using EQ (such as the Equalizer in NAudio.Extras) which could help with noise in a particular frequency range.
