### ISSUE TITLE
Merge two mp3 file, get one file, duration is wrong

### ISSUE THREAD

**Issue by nowayout** [naudio/NAudio#854]
I have two mp3 FileA.mp3 and FileB.mp3 merge to FileC.mp3. The code like this:
`
void Main()
{
     var mp3Path = @"C:\Users\Ronnie\Desktop\podcasts\hanselminutes_0350.mp3";  
     var outputPath = Path.ChangeExtension(mp3Path,".trimmed.mp3");
 
     TrimMp3(mp3Path,outputPath,TimeSpan.FromMinutes(2),TimeSpan.FromMinutes(2.5));
}

void TrimMp3(string inputPath,string outputPath,TimeSpan? begin,TimeSpan? end)
{
    if (begin.HasValue && end.HasValue && begin > end)
        throw new ArgumentOutOfRangeException("end","end should be greater than begin");
 
    using (var reader = new Mp3FileReader(inputPath))
    using (var writer = File.Create(outputPath))
    {           
        Mp3Frame frame;
        while ((frame = reader.ReadNextFrame()) != null)
        if (reader.CurrentTime >= begin || !begin.HasValue)
        {
            if (reader.CurrentTime <= end || !end.HasValue)
                writer.Write(frame.RawData,frame.RawData.Length);         
            else break;
        }
    }
}
`

When the merge operation finished, use NAudio TotalTime, the TotalTime is correct, it's FileA.mp3 TotalTime add FileB.mp3 TotalTime. Such as, FileA.mp3 TotalTime is 00:07:03, FileB.mp3 TotalTime is 00:00:24, the FileC.mp3 TotalTime is 00:07:27.
Play the FileC.mp3, it contains FileA.mp3 and FileB.mp3 all data. But, Media Player / ffmpeg / CoolEdit, show the FileC.mp3 time is only 00:07:15.
What can I do, FileC.mp3 will show the correct time 00:07:27 ?

**Comment by markheath** [comment]
I suspect the merge is either copying invalid metadata or results in a file that's an odd mix of CBR and VBR. You might be better decoding the inputs to WAV and then re-encoding the combined file to MP3

**Comment by nowayout** [comment]
> I suspect the merge is either copying invalid metadata or results in a file that's an odd mix of CBR and VBR. You might be better decoding the inputs to WAV and then re-encoding the combined file to MP3

Okey, thank you very much.
