### ISSUE TITLE
net6.0 requires -window

### ISSUE THREAD

**Issue by curia-damiano** [naudio/NAudio#855]
Hi,
I am migrating an Azure Function that uses NAudio 2.0.1 from netcoreapp3.1 to net6.0.
During compilation, I get errors that I should change the target framework to net6.0-windows.
The same happens with a console application: it needs net6.0-windows.

I have checked with the [NuGet Package Explorer](https://nuget.info/packages/NAudio/2.0.1) and it confirms that the library generated a .NET Standard 2 assembly.

So, why do I need to choose explicitly net6.0-windows and not simply net6.0? Do I miss anything?

**Comment by hansmbakker** [comment]
If you use the NAudio umbrella package it fetches all its contents. Most of them have a dependency on Windows APIs. One of them is the NAudio.WinForms package.

Also, the dependency tree is a bit inconvenient. Work on that is being done (see #591), but I'm not sure what the current status of that is as the discussion there is quite old. I asked a question about it at https://github.com/naudio/NAudio/issues/591#issuecomment-1002292511

@markheath pushed changes on splitting up NAudio in separate packages (https://github.com/naudio/NAudio/commit/ab81961377a975a7b0d2815c9a9cc4fa67da4c35) before the 2.0 release and wrote some more about it at https://markheath.net/post/naudio-2-plans.

**Comment by markheath** [comment]
Yes, it's a bit annoying that you now need -windows. I'm thinking that there might be something I can do to optionally reference Windows-specific assemblies if you're on Windows but haven't had a chance to test it. If you can get away with just using NAudio.Core then I recommend doing that.

**Comment by curia-damiano** [comment]
Thank you @markheath for your tip!
In my case I am using Mp3FileReader, included in NAudio.Wave, that doesn't seem to be part of Core (I have tried to simply exchange the NuGet package, but it can't find this class).

My supposition is that reading a Mp3 file would have been cross platform, but I deduct that in your implementation you might use some platform specific APIs.

**Comment by markheath** [comment]
Mp3FileReader by default uses the ACM MP3 frame decompressor which is Windows specific. It was hard to change that without making a breaking change to NAudio which is why it sits at the top level. However, all the functionality has moved down into Mp3FileReaderBase which you can use directly with NLayer if you want cross-platform MP3 file reading

**Comment by curia-damiano** [comment]
I have analyzed the two generated files and I get these properties:

- for the Windows-only PCM conversion:
  <img width="532" alt="WindowsOnly" src="https://user-images.githubusercontent.com/18611507/148394183-1daabeca-ae09-4af7-97e5-871630b5e932.png">
- for the cross platform conversion:
  <img width="529" alt="CrossPlatform" src="https://user-images.githubusercontent.com/18611507/148394234-e45a1c1a-3aa6-4df8-83cb-fef69331afc6.png">

Both files have one channel and 48000 samples per second; the Windows only (code name: PCM signed 16-bit little-endian) has 16 bits per sample, while the cross-platform (code name: PCM 32-bit floating point little-endian) has 32 bits per sample.

Can I generate with NAudio.Core the same file, with 16 bits per sample?

**Comment by markheath** [comment]
Closing as the main issue net6.0 requires -window has been resolved
