### ISSUE TITLE
Play back wav file and display spectrum diagram

### ISSUE THREAD

**Issue by ananadult** [naudio/NAudio#858]
How to obtain the actual DB value through FFT conversion for the value obtained by Read (float [] buffer, int offset, int count) in ISampleProvider class?

**Comment by markheath** [comment]
I'm not an expert in how FFTs should be interpreted for spectrum plots, but there is a simple example here in the NAudio demo code: https://github.com/naudio/NAudio/blob/master/NAudioWpfDemo/SpectrumAnalyser.xaml.cs
