### ISSUE TITLE
NAudio will not install.

### ISSUE THREAD

**Issue by ChrisWFowler** [naudio/NAudio#859]
Could not install package 'NAudio 2.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:01.0816701
========== Finished ==========

**Comment by markheath** [comment]
NAudio 2 requires netstandard2.0 compatibility, which means you should ideally be targeting at least .NET Framework 4.7. Is there any reason you can't?
Otherwise you still need to use NAudio 1.10
