### ISSUE TITLE
Add meter on audio decoding in shoutcast streaming sample

### ISSUE THREAD

**Issue by fabcal24** [naudio/NAudio#86]
I suggest this modifications in audiostreamer sample shoutcast:

//add a new declaration
     private MeteringSampleProvider vuMeter = null;
     public double LevelLeftValue = 0;
     public double LevelRightValue = 0;

//In timer event add this rows
                    vuMeter = new MeteringSampleProvider(volumeProvider.ToSampleProvider());
                    waveOut.Init(new SampleToWaveProvider(vuMeter));
                    vuMeter.StreamVolume += Meter_StreamVolume;   

//Add this method

 private void Meter_StreamVolume(Object sender,StreamVolumeEventArgs e)
        {
              try
              {
                  
                  LevelLeftValue = (Math.Truncate(e.MaxSampleValues[0] * 150));
                  LevelRightValue =(Math.Truncate(e.MaxSampleValues[1] * 150));
               
              }
                catch
              {
                  LevelLeftValue = 0;
                  LevelRightValue = 0;
                }
        
        
        }

//Change stop method with this:

 public void Stop()
        {
            if (playbackState != StreamingPlaybackState.Stopped)
            {
                if (!fullyDownloaded)
                {
                    webRequest.Abort();
                }
                
                playbackState = StreamingPlaybackState.Stopped;
                if (waveOut != null)
                { 
                    waveOut.Stop();
                    waveOut.Dispose();
                    waveOut = null;
                    vuMeter.StreamVolume -= Meter_StreamVolume;
                    vuMeter = null;
                }
                timer1.Enabled = false;
                LevelLeftValue = 0;
                LevelRightValue = 0;
                // n.b. streaming thread may not yet have exited
                Thread.Sleep(500);
                ShowBufferState(0);
             
            }
        }

Thanks :-)

**Comment by markheath** [comment]
thanks, you're welcome to submit a pull request for this
