### ISSUE TITLE
Can't build in VS 2019

### ISSUE THREAD

**Issue by MOAMaster** [naudio/NAudio#866]
I opened solution and trying to build in latest version of VS 2019.
I just keep getting a lot of errors but no building.
See notes below.

Failed to download package 'runtime.win10-x86.Microsoft.Net.UWPCoreRuntimeSdk.2.2.9' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk/2.2.9/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk.2.2.9.nupkg'.
Cannot access a disposed object.
Object name: 'SslStream'.
Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/index.json'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/index.json' has timed out after 100000ms.
Failed to download package 'runtime.win10-x64.Microsoft.Net.Native.Compiler.2.2.7-rel-27913-00' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.native.compiler/2.2.7-rel-27913-00/runtime.win10-x64.microsoft.net.native.compiler.2.2.7-rel-27913-00.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.native.compiler/2.2.7-rel-27913-00/runtime.win10-x64.microsoft.net.native.compiler.2.2.7-rel-27913-00.nupkg' has timed out after 100000ms.
Failed to download package 'runtime.win10-arm.Microsoft.Net.Native.Compiler.2.2.7-rel-27913-00' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/2.2.7-rel-27913-00/runtime.win10-arm.microsoft.net.native.compiler.2.2.7-rel-27913-00.nupkg'.
Cannot access a disposed object.
Object name: 'SslStream'.
Failed to download package 'runtime.win10-arm64.Microsoft.Net.Native.Compiler.2.2.7-rel-27913-00' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm64.microsoft.net.native.compiler/2.2.7-rel-27913-00/runtime.win10-arm64.microsoft.net.native.compiler.2.2.7-rel-27913-00.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm64.microsoft.net.native.compiler/2.2.7-rel-27913-00/runtime.win10-arm64.microsoft.net.native.compiler.2.2.7-rel-27913-00.nupkg' has timed out after 100000ms.
Failed to download package 'runtime.win10-arm.Microsoft.Net.Native.Compiler.2.2.7-rel-27913-00' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/2.2.7-rel-27913-00/runtime.win10-arm.microsoft.net.native.compiler.2.2.7-rel-27913-00.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/2.2.7-rel-27913-00/runtime.win10-arm.microsoft.net.native.compiler.2.2.7-rel-27913-00.nupkg' has timed out after 100000ms.
Failed to download package 'runtime.win10-x86.Microsoft.Net.Native.Compiler.2.2.7-rel-27913-00' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/2.2.7-rel-27913-00/runtime.win10-x86.microsoft.net.native.compiler.2.2.7-rel-27913-00.nupkg'.
Cannot access a disposed object.
Object name: 'SslStream'.
Failed to download package 'runtime.win10-arm64.Microsoft.Net.Native.Compiler.2.2.7-rel-27913-00' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm64.microsoft.net.native.compiler/2.2.7-rel-27913-00/runtime.win10-arm64.microsoft.net.native.compiler.2.2.7-rel-27913-00.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm64.microsoft.net.native.compiler/2.2.7-rel-27913-00/runtime.win10-arm64.microsoft.net.native.compiler.2.2.7-rel-27913-00.nupkg' has timed out after 100000ms.

**Comment by markheath** [comment]
I recommend using VS2022. You also need to make sure that you have installed the exact version of the Windows 10 SDK used by some of the projects (currently 10.0.17763) but I might change that in the future
