### ISSUE TITLE
No longer builds for Linux

### ISSUE THREAD

**Issue by mconradiesa** [naudio/NAudio#868]
v1.9.0 works when building for Linux
v2.0.1 fails to build with error "The target platform must be set to Windows (usually by including '-windows' in the TargetFramework property) when using Windows Forms or WPF, or referencing projects or packages that do so." (code: NETSDK1136)

**Comment by DecidedlyHuman** [comment]
I'm also running into this issue. I'm going to start digging into it to see if I can find a way around it, at least.

**Comment by markheath** [comment]
Hoping that this works with v2.1.0. You can also just reference NAudio.Core which doesn't have any Windows specific components included.
