### ISSUE TITLE
What is the highest sampling Rate you can use for CreateIeeeFloatWaveFormat  ?

### ISSUE THREAD

**Issue by btb4198** [naudio/NAudio#874]
What is the highest sampling Rate you can use for CreateIeeeFloatWaveFormat to produce the highest possible song ? That can Correctly produce the highest sound frequency? I am trying to see what is the Highest frequency I can produce.

I know with nyquist frequency you have to sample two time the desire frequency.

I set sampling Rate to 88200 and I made a 44K sound file and dropped it in Audacity and verify that it was making a 44K sound wave and that work fine, but When I tried to play that sound wave and record it with Audacity, Audacity did not pick it up. And I just got noise.

So I do not know if it my computer was playing the 44K or not.

So my question is what is the highest combination of sampling Rate and frequency, I can actually play?

**Comment by markheath** [comment]
It depends on your sound card drivers. There are some valid reasons to use high sample rates for audio production, but for a file intended to be listened to there is very little point going above 44.1kHz as the additional frequency range that can be represented with higher sample rates is all above the range of human hearing.
