### ISSUE TITLE
Align WasapiLoopbackCapture and WaveIn to be same length

### ISSUE THREAD

**Issue by andreamisu** [naudio/NAudio#880]
Good evening!
As current implementation, I'm dealing with recording both WaveIn from a Microphone and Wasapi Loopback at the same time.

The data is written on the buffer using the _DataAvailable_ callback, and this doesn't write anything before there are any data to recollect (Microphone is silent or System is not reproducing any audio), there is any way to just start writing on the buffer using WaveFileWriter without waiting for any data to be available, in order to make both recordings of the same length?

Thank you!

**Comment by markheath** [comment]
It's a bit of a pain with loopback capture. I sometimes use the trick of playing silence to get round this! There is a `SilenceProvider` you can use in NAudio for this purpose!
