### ISSUE TITLE
Does NAudio 2.0.1 support cross-platform?

### ISSUE THREAD

**Issue by wuliangtdi** [naudio/NAudio#883]
I hope NAudio 2.0.1 can support cross platform, because I can do cross platform application.

**Comment by markheath** [comment]
NAudio consists of some cross-platform components, but it also has a lot of wrappers for Windows Audio APIs and codecs. Those wrappers can obviously only be used on Windows. As a general rule, if its in the NAudio.Core NuGet package you can use it cross-platform
