### ISSUE TITLE
Get Wav Peak Data as Int16 Values

### ISSUE THREAD

**Issue by ozdogans** [naudio/NAudio#886]
I want to use NAudio to extract the peak values of wav audio files like the _audiowaveform_ library provides. Which is an array of short values like:

```
{
  "version": 2,
  "channels": 2,
  "sample_rate": 48000,
  "samples_per_pixel": 512,
  "bits": 8,
  "length": 3,
  "data": [-65,63,-66,64,-40,41,-39,45,-55,43,-55,44]
}
```
https://github.com/bbc/audiowaveform/blob/master/doc/DataFormat.md

I saw that NAudio has a built-in WaveformRenderer that outputs png images, but I just need the raw peak data. Built-in NAudio classes like MaxPeakProvider (which is initialized with waveReader.ToSampleProvider()) etc. works with floats, I need them as short values. Is it possible?

**Comment by markheath** [comment]
You can convert them back into floats by multiplying the float value by `short.MaxValue` and then casting to a short. You if your incoming audio is already as shorts, then just make your own version of `MaxPeakProvider` that takes an `IWaveProvider`, and uses `BitConvertor` or similar to read out the float values as they pass through.
