### ISSUE TITLE
OffsetSampleProvider delayby only works when seconds are a multiple of 4

### ISSUE THREAD

**Issue by mozzak** [naudio/NAudio#889]
Hi:

I experience an issue with OffsetSampleProvider.

In the following code I am adding sound every x seconds and write a file in the end.:

                    for (int i=1; i<= totalIteractions; i++)
                    {                      
                        MusicSampleProvider msp = new MusicSampleProvider(ss);

                        OffsetSampleProvider sp1 = new OffsetSampleProvider(msp);

                        sp1.DelayBy = TimeSpan.FromSeconds(repeatSeconds * i);

                        mixer.AddMixerInput(sp1);                                               
                    }

                    WaveFileWriter.CreateWaveFile16(outputFile, mixer);

All that works fine only when repeatSeconds is a multiple of 4.

So for example setting repeatSeconds to 4,8,12, .... the resulting file has the sound at those seconds.
If you set the repeatSeconds to 5,10,15 the resulting sound is placed all over.

Any ideas what is going wrong?

Thanks,
Moz

**Comment by markheath** [comment]
I suspect there is a bug in your `MusicSampleProvider` class but obviously don't know how you've implemented it
