### ISSUE TITLE
How to Use Skypefx Effects library.

### ISSUE THREAD

**Issue by Delaley** [naudio/NAudio#89]
Please I want to use the Skypefx library written by you to process wav files and play.
How do I do it.

**Comment by markheath** [comment]
well the demo windows application shows it being used to play and process audio files, so you can try it out. It's quite an old project. These days I'd implement the effects as ISampleProvider instances, and then chain them together passing my input file through and into a sound device.

**Comment by Delaley** [comment]
Please do u know Unity3D

**Comment by markheath** [comment]
sorry I'm afraid I've never used Unity3D
