### ISSUE TITLE
Error APPX3217

### ISSUE THREAD

**Issue by Kwyrky** [naudio/NAudio#892]
A fresh clone from GitHub and it gives me an error when I try to build the solution:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	APPX3217	SDK folder containing 'UAP.props' for 'UAP 10.0.17763.0' cannot be located. See http://go.microsoft.com/fwlink/?LinkID=798187 for more information.	NAudio.Wasapi	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppXPackage.Targets	1097`

![grafik](https://user-images.githubusercontent.com/21105488/160854527-ff71c995-8881-4ccb-868c-bf05e80e0597.png)

**Comment by AbedKarmi** [comment]
I have same issue. I installed latest version of SDK 10.0.22000.0, but did not try to install the exact required version 10.0.7763.0.

**Comment by markheath** [comment]
Unfortunately you have to have the exact SDK installed to build.
