### ISSUE TITLE
How to play in wpf application 

### ISSUE THREAD

**Issue by ohmygodoh** [naudio/NAudio#893]
I create a wpf application and create a button  in this application. In the method of application initialization, I play a song in asio mode,when I click the button continuously, I hear the music is intermittent, how can I fix it, Is there any way to solve it

**Comment by markheath** [comment]
ASIO tends to work at very low latencies. That means that the code you use to provide audio needs to be very well optimised or you'll get dropouts. If you're just playing a song, you might find one of the other output modes is more appropriate.
