### ISSUE TITLE
Cannot record with the built-in microphone in laptop

### ISSUE THREAD

**Issue by McTopaz** [naudio/NAudio#894]
My company use NAudio V1.10.0 in one of our applications.
We have a problem that we cannot record while using headphones.

**Setup**
On my laptop there is a built in microphone.
There is also a standard input (3.5mm?) jack to connect a headphone with combined ear speakers and microphone.
I have connected such a headphone to the input jack on my laptop.

**Problem**
But it seems that NAudio cannot distinguish between the headphone's mic and the built in microphone.
As if they share the same the same resource(s) internally.

**Some testing**
I have made a test application as a Console Application with NAudio 2.1 to check if that version works better. But unfortunately not.
Here is the source of my test application at this [Gist](https://gist.github.com/McTopaz/b3b30a7bead10c44767ee8a4318b1339).

**List of microphone**
Here is the list of microphone detects by NAudio when running the application.
```
 === WaveIn / WaveInCapabilities ===
ProductName:    Microphone Array (Realtek(R) Au
ProductGuid:    e36dc311-6d9a-11d1-a21a-00a0c9223196

ProductName:    External Mic (Realtek(R) Audio)
ProductGuid:    e36dc311-6d9a-11d1-a21a-00a0c9223196


 === MMDeviceEnumerator / MMDevice ===
FriendlyName:   External Mic (Realtek(R) Audio)
ID:             {0.0.1.00000000}.{1ba4ea63-6306-4ac6-a192-6c84193111da}

FriendlyName:   Microphone Array (Realtek(R) Audio)
ID:             {0.0.1.00000000}.{aeb09118-c6c5-4d17-b9e3-4ed5b8313316}
```

**Microphones**
- _External Mic (Realtek(R) Audio)_ is the headphone.
- _Microphone Array (Realtek(R) Audio)_ is the built-in microphone.

Notice the _WaveIn / WaveinCapabilities_ detects the two microphones, but:
- The full name of the _Microphone Array (Realtek(R) Audio)_ is not printed. Minor bug?
- Both microphones share the same ProductGuid. Why?

Compare two the _MMDeviceEnumerator / MMDevice_ listing which clearly distinguish the microphones.

**Further problem when recording**
In my code, at Gist, I have also shown the bareback code how we test a microphone with NAudio.
I cannot get the audio I record to playback, so just ignore the playback stuff there.

In our application we can hear what we record if we use the Devicde Id = 0.
Device Id = 0 seems to be the built-in microphone.
If we try to use the headphone, which has device Id = 1, it doesn't work :(

What is going on here?
Is there a solution?

**Comment by markheath** [comment]
NAudio simply calls the Windows audio APIs. WaveIn uses the WinMM APIs which are really old and have a maximum product name length that you can't work around. The capabilities exposed are controlled by the device driver authors, and not by NAudio, so it is not always possible to access the device you want to. MMDeviceEnumerator uses the much newer and more advanced WASAPI audio API, and so that is usually preferable if you want control over devices, although WASAPI does not feature built-in sample rate conversion which can make it awkward to use in some circumstances.

**Comment by markheath** [comment]
Now that NAudio 2.1.0 supports sample rate conversion for `WasapiCapture`, I recommend using that instead of `WaveIn` or `WaveInEvent`
