### ISSUE TITLE
audio watermarking question

### ISSUE THREAD

**Issue by HamidLaktarash** [naudio/NAudio#897]
I gonna implement program that embed and hide 12 digits decimal number
into .wav file audio signal and it`s don`t affect to file sound human
hear, then after while I want extract same 12 digits decimal number
from those files. I know somethings about NAudio .net , Fast Fourier
Transform.
I have below algorithm idea but I can`t implement it.
Through Using Fourier Transform, I change main .wav file to frequency
domain then make a signal in frequency domain form 12 digits number in
less than 20 hz ( because it`s not hear by human ) and then merge two
signal to one signal in frequency domain and finally operate Inverse
Fourier Transform to back to time domain. in other hand I should
process some file and extract numbers

**Comment by markheath** [comment]
NAudio can write any samples you like to a file, but I'm afraid you'll need to implement your own algorithm for something like this as its very bespoke
