### ISSUE TITLE
Decoupling Windows dependencies for Mp3FileReader 

### ISSUE THREAD

**Issue by SergeBerwert** [naudio/NAudio#898]
I try to use NAudio to convert an MP3 stream into a wav stream, which dos work on my computer without a problem. The problem is I try to run this on a Linux server, which does not work because there are windows dependencies. I do not understand the project organization very well, but for some reason is Mp3FileReader is in the main project which has de most Windows dependencies. It references the project NAudio.WinMM which has only one registry access.

It would be nice if the MP3 format could be decoupled from the windows dependencies.

**Comment by Zintom** [comment]
As a temporary fix, off the top of my head you can just copy the Mp3FileReader.cs file into your own class, maybe (Mp3FileReaderLinux?), remove the windows dependency from it and use that instead.

**Comment by markheath** [comment]
There is an `Mp3FileReaderBase` class that you can use for this, with the NLayer project if you want a managed MP3 decoder

**Comment by isolin** [comment]
What I did is to change the `NAudio/NAudio,csproj` file as follows (just the middle part  with all the includes):
```xml
  <ItemGroup>
    <ProjectReference Include="..\NAudio.Asio\NAudio.Asio.csproj" />
    <ProjectReference Include="..\NAudio.Core\NAudio.Core.csproj" />
    <ProjectReference Include="..\NAudio.Midi\NAudio.Midi.csproj" />
    <ProjectReference Include="..\NAudio.Wasapi\NAudio.Wasapi.csproj" />
    <ProjectReference Include="..\NAudio.WinMM\NAudio.WinMM.csproj" />
  </ItemGroup>
  <!--ItemGroup Condition=" '$(TargetFramework)' != 'net6.0' ">
    <ProjectReference Include="..\NAudio.WinForms\NAudio.WinForms.csproj" />
  </ItemGroup-->
```
Simply comment out the `WinForms` reference and you are good to go.
