### ISSUE TITLE
Build on mac os doesn't work

### ISSUE THREAD

**Issue by gurgendav** [naudio/NAudio#899]
Trying to build a project with NAudio 2.0.1 on mac os fails with error.

> Microsoft.NET.Sdk.DefaultItems.Shared.targets(250, 5): [NETSDK1136] The target platform must be set to Windows (usually by including '-windows' in the TargetFramework property) when using Windows Forms or WPF, or referencing projects or packages that do so.

`  <Target Name="_CheckForTransitiveWindowsDesktopDependencies"
          AfterTargets="ResolvePackageAssets"
          Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp' and $([MSBuild]::VersionGreaterThanOrEquals($(_TargetFrameworkVersionWithoutV), '5.0')) and '$(TargetPlatformIdentifier)' != 'Windows' and '@(TransitiveFrameworkReference)' != ''">
    <ItemGroup>
      <_WindowsDesktopTransitiveFrameworkReference Include="@(TransitiveFrameworkReference)"
                                                   Condition="'%(Identity)' == 'Microsoft.WindowsDesktop.App' Or
                                                              '%(Identity)' == 'Microsoft.WindowsDesktop.App.WPF' Or
                                                              '%(Identity)' == 'Microsoft.WindowsDesktop.App.WindowsForms'" />
    </ItemGroup>
    <NetSdkError Condition="'@(_WindowsDesktopTransitiveFrameworkReference)' != ''"
                 ResourceName="WindowsDesktopTargetPlatformMustBeWindows" />
  </Target>`

**Comment by gurgendav** [comment]
Is there any way to fix this?

**Comment by markheath** [comment]
.NET 6 is more fussy about this unfortunately. You can just reference NAudio.Core which is NETStandard. But I am also trying to improve the situation by multitargeting and leaving out the non-windows parts. If you could try with 2.1.0-beta.1 and let me know how you get on on Mac OS that would be super helpful https://www.nuget.org/packages/NAudio/2.1.0-beta.1

**Comment by markheath** [comment]
Hoping that NAudio 2.1.0 resolves this issue

**Comment by csukuangfj** [comment]
I suggest that you have a look at

https://github.com/csukuangfj/PortAudioSharp2

It is a wrapper for [portaudio](https://github.com/PortAudio/portaudio) and it works on Linux, macOS, and Windows. Everything is pre-compiled.

An example of using it for speech recognition from a microphone can be found at
https://github.com/k2-fsa/sherpa-onnx/tree/master/dotnet-examples/speech-recognition-from-microphone
