### ISSUE TITLE
Convert to MIT

### ISSUE THREAD

**Issue by sirinath** [naudio/NAudio#91]
Since even MS now uses MIT is it possible to convert to MIT, BSD or ASL 2.0?

**Comment by markheath** [comment]
MS-PL is a nice permissive license. Is there anything it is stopping you doing?

**Comment by sirinath** [comment]
Re package under a different license. Say license hole project with dependencies under ASL 2.0.

**Comment by markheath** [comment]
Why? Is there a problem with the current license?

**Comment by residuum** [comment]
Ms-PL is incompatible with the GPL: http://www.gnu.org/licenses/license-list.en.html

**Comment by markheath** [comment]
Why is this a problem? I chose Ms-PL to be commercially friendly license, and there is no GPL code included in NAudio. Is it stopping you from doing something you need to do?

**Comment by residuum** [comment]
This might be a reason for switching licenses. Compatibility with GPL is necessary, if someones wants to use parts of the code in a GPL project.
