### ISSUE TITLE
Include API documentation in all NuGet packages

### ISSUE THREAD

**Issue by KPHIBYE** [naudio/NAudio#917]
I noticed that IntelliSense does not display the API documentation of the `NAudio.WinMM` library since it is not contained as XML file in the NuGet package and this seems to be the case for all libraries except `NAudio`.

I would suggest to add a [Directory.Build.props](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build) file that contains the `GenerateDocumentationFile` configuration from the [NAudio.csproj](https://github.com/naudio/NAudio/blob/52491103dd368ebc243d2d5ff57fcdfaddc5cf42/NAudio/NAudio.csproj#L13) file to apply the configuration to all projects in the solution as demonstrated in this [StackOverflow post](https://stackoverflow.com/a/47118584). This should lead to the XML files being included in the NuGet packages.

Directory.Build.props:
```xml
<Project>
  <PropertyGroup>
    <GenerateDocumentationFile Condition=" '$(Configuration)' == 'Release' ">true</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
```

I would love to see this as it would basically be a free quality of life improvement for all users of these libraries.

**Comment by markheath** [comment]
Thanks. This was an oversight when NAudio got split up into multiple sub-libraries. I've restored it so it will be part of the next release

**Comment by KPHIBYE** [comment]
Thanks for including them again in https://github.com/naudio/NAudio/commit/0cd2aba4dc69353cb25e5cf09d3c9d63f19daf9a
