### ISSUE TITLE
Can captured samples be amplified before written to file?

### ISSUE THREAD

**Issue by wiiNinja** [naudio/NAudio#918]
I'm trying to find a way to amplify the samples as it's being received because I know that my audio is inherently low. Reading through the Docs, I found a reference to the use of WaveBuffer. I was hoping that something like this would work (my simple brain's first thought):

m_CaptureDevice.DataAvailable += (s, a) =>
{
    var buffer = new WaveBuffer(a.Buffer);
    // interpret as 32 bit floating point audio
    for (int index = 0; index < a.BytesRecorded / 4; index++)
    {
        // Boost input the received samples
        buffer.FloatBuffer[index] = buffer.FloatBuffer[index] * 1.1f;  // Doesn't work
    }
    m_WavWriter.Write((byte[])buffer, 0, a.BytesRecorded);
};

But it doesn't. I am providing the user with the ability to boost the playing level at play back time, but I also would like to provide the user the opportunity to amplify the audio as it's being recorded. Is there a simple way to do this? Thank you.

**Comment by markheath** [comment]
You can only interpret the incoming data as 32 bit floating point if that's what it actually is. And so I expect you're recording 16 bit audio. The WaveFormat of m_CaptureDevice will tell you

**Comment by wiiNinja** [comment]
Thanks Mark. That was it. No more garbled audio after fixing the bits per sample.
