### ISSUE TITLE
WaveFileChunkReader class not public

### ISSUE THREAD

**Issue by sound00d** [naudio/NAudio#92]
NAudio.FileFormats.Wav.WaveFileChunkReader class is not explicitly set to public, so is unreachable from user code.

I'd like to use this to check whether a .wav file has valid header information (RIFF header) before trying to open it with WaveFileReader where it will throw an exception.

**Comment by markheath** [comment]
this was not made public as it was a refactoring work in progress and I wanted freedom to be able to change the public interface. For now you can easily take a copy of the class. Maybe in the future we can make it public
