### ISSUE TITLE
MediaFoundationResampler is not resampling 2 bytes 

### ISSUE THREAD

**Issue by Jakobi-mirsk** [naudio/NAudio#926]
hi
great library, but i have a strange issue when using MediaFoundationResampler to resample streamed audio.
I have the following code, that resamples blocks of audio. I am converting 8kHz 16bit mono audio to 16kHz 16bit mono.
The problem is when calling ResampleAudio with 3200 bytes of audio the MediaFoundationResampler only returns 6398 bytes. I would have expected a return of 6400 bytes, because i am effectively just dobling the audio data size. Can anyone tell me why this is?

`public class MediaFoundationResample
    {
        private WaveFormat SourceWaveFormat { get; set; }
        private WaveFormat TargetWaveFormat { get; set; }
        private int SourceBytesPrSec { get; set; }
        private int TargetBytesPrSec { get; set; }
        private int BytesPrSecRatio { get; set; }
        private BinaryWriter bw = null;
        private MemoryStream ms = new MemoryStream();
        private RawSourceWaveStream rs = null;
        private MediaFoundationResampler resampler = null;
        public MediaFoundationResample(int sourceSamplerate, int sourceBitdepth, int sourceChannels, int targetSamplerate, int targetBitdepth, int targetChannels)
        {
            SourceWaveFormat = new WaveFormat(sourceSamplerate, sourceBitdepth, sourceChannels);
            TargetWaveFormat = new WaveFormat(targetSamplerate, targetBitdepth, targetChannels);

            SourceBytesPrSec = (SourceWaveFormat.SampleRate * SourceWaveFormat.BitsPerSample * SourceWaveFormat.Channels) / 8;
            TargetBytesPrSec = (TargetWaveFormat.SampleRate * TargetWaveFormat.BitsPerSample * TargetWaveFormat.Channels) / 8;
            BytesPrSecRatio = TargetBytesPrSec / SourceBytesPrSec;

            bw = new BinaryWriter(ms);
            rs = new RawSourceWaveStream(ms, SourceWaveFormat);
            resampler = new MediaFoundationResampler(rs, TargetWaveFormat);
            resampler.ResamplerQuality = 1; //between 1 and 60
        }
        public byte[] ResampleAudio(byte[] audio)
        {
            bw.Write(audio);
            ms.Position = ms.Position - audio.Length;
            Trace.WriteLine("audio length:" + audio.Length + " ms length:" + ms.Length + " ms pos:" + ms.Position);
            int outputSize = audio.Length * BytesPrSecRatio;
            byte[] outputbuffer = new byte[outputSize];
            
            int read = resampler.Read(outputbuffer, 0, outputbuffer.Length);
            Trace.WriteLine("audio length:" + audio.Length + " read:" + read + " ms length:" + ms.Length + " ms pos:" + ms.Position);
            if (read != outputbuffer.Length)
            {
                LogWriter.WriteError("We didn't convert everything. " + audio.Length + " bytes input, " + read + " bytes converted");
            }
            return outputbuffer.Take(read).ToArray();
        }
        public void Close()
        {
            ms.Close();
            bw.Close();
            rs.Close();
            
            resampler.Dispose();
        }
    }`

I am also hearing some strange phenomena in the output. It does not matter what quality i use, but i hear some sporadic glitches (don't know how to describe it other than if a single or a small amount of sample are wrong and high pitched)

**Comment by markheath** [comment]
I don't know why it is slightly shorter - if anything I'd expect slightly longer to account for latency.
Also you have chosen the lowest possible quality (1), the default is 30

**Comment by goddogthedoggod** [comment]
It appears that, in contrast to some other resamplers, MediaFoundationResampler interprets the data as a piece of audio beginning at the first and ending at the last sample. In other words: each sample represents a point in time and the length of the piece of audio is defined by the accumulated number of tiny gaps between consecutive samples, each gap having the same duration in accordance with the sample rate.

In your case: 3200 bytes at 16bit are 1600 input samples – that's 1599 gaps between them at a duration of 1/8000 seconds each and 1599/8000 seconds overall. Converted to 16 kHz, this same duration of 3198/16000 seconds results in 3198 gaps between 3199 16bit samples which take up 6398 bytes.

For another approach at an explanation and a little more information, read the last paragraph of #606.

**Comment by Jakobi-mirsk** [comment]
Thank you for the explanation, but is this a bug then? I am wondering if i only input 2 samples, will i get only one back.

**Comment by goddogthedoggod** [comment]
It's not a bug and no, as long as you're upsampling, you'll never get less samples back than you put in.

Think of a sample as the position a membrane inside the microphone or inside the speaker is in at that point in time. If you have only 2 samples, that means that the membrane starts at the first sample's position and then transitions over time to the second sample's position. At a sampling rate of 8 kHz, this transition takes 1/8000 seconds. If you then add a third sample, you describe a second transition from the second to the third sample and you can think of the length of that whole piece of audio as the combined length of both transitions, that is 2/8000 seconds. If you upsample these 3 samples from 8 to 16 kHz like MediaFoundationResampler, you would split each transition in half by inserting an additional sample in the middle of each one, so you would end up with 5 samples and not 6.

There are other resamplers that treat each sample as if it had a duration in accordance with the sample rate. Those resamplers would actually double the number of samples when you double the sample rate, as you would expect.

**Comment by Jakobi-mirsk** [comment]
That makes sense. Thank you for taking the time to explain. It was this part that made the difference: 
_ If you upsample these 3 samples from 8 to 16 kHz like MediaFoundationResampler, you would split each transition in half by inserting an additional sample in the middle of each one, so you would end up with 5 samples and not 6._
