### ISSUE TITLE
How do i get the total duration of a mp3 file in .net core

### ISSUE THREAD

**Issue by michaelonz** [naudio/NAudio#937]
I have a .net core web app that i am allow users to upload audio - and i want to get the duration - i have installed the Naudio.core nuget package. 
I have the following code to get the duration of a wav file and this works fine:

  WaveFileReader wf = new WaveFileReader(fileName);
 return wf.TotalTime;

How do i do the same for .mp3 files - i went looking for Mp3FileReader but it doesnt appear to be in the Naudio.core pacakge?

I dont need to play these files - all i want is to get the duration of the audio.

Am I missing a package or what am i missing here?

Also is there a smarter way that tries to determine the encoding and return the duration without me relying on the file extension for the type?

**Comment by Mauricio-MN** [comment]
If I remember correctly:

```
WaveStream mp3Stream = new Mp3FileReader("file.mp3");
TimeSpan timeSpan = mp3Stream.TotalTime;
```

**Comment by markheath** [comment]
You can also use `MediaFoundationReader` which should be slightly quickly
The `NAudio.Core` package only contains the cross-platform parts of NAudio. Reading MP3s whether by Mp3FileReader or MediaFoundationReader uses Windows-specific APIs. If you just reference the top-level NAudio NuGet package you'll get everything you need

**Comment by michaelonz** [comment]
Thanks guys
