### ISSUE TITLE
Play two waveoutevent player volume issue

### ISSUE THREAD

**Issue by AthiVarathan** [naudio/NAudio#94]
Hi ,

I have using Two waveoutevent player. Play the msuic. if i set volume waveouteventplayer1 set 0.0f . Alll volume is muted. how to solve tis problem.

Thank You.
Athi varathan

**Comment by markheath** [comment]
Yes, setting volume does it for the device not the instance of the device. For control individually, you should just inclde something with volume in your IWaveProvider/ISampleProvider signal chain that you pass to Init
