### ISSUE TITLE
Problem with ICY 200 OK response

### ISSUE THREAD

**Issue by Nekromancer** [naudio/NAudio#95]
I have this code to listen to stream

```
var mediaFoundationReader = new MediaFoundationReader(StreamUrl);
```
It works perfectly for most of the streams, but when i'm trying to listen to this `http://zet-net-01.cdn.eurozet.pl:8400` the exception is thrown:

```
The byte stream type of the given URL is unsupported. (Exception from HRESULT: 0xC00D36C4)

   at NAudio.MediaFoundation.MediaFoundationInterop.MFCreateSourceReaderFromURL(String pwszURL, IMFAttributes pAttributes, IMFSourceReader& ppSourceReader)
   at NAudio.Wave.MediaFoundationReader.CreateReader(MediaFoundationReaderSettings settings)
   at NAudio.Wave.MediaFoundationReader..ctor(String file, MediaFoundationReaderSettings settings)
   at AudioUtilities.AudioStreamDumper.OverlapingAudioStreamCapture.Start(TimeSpan dumpInterval, TimeSpan dumpDuration) in C:\Users\jsyty\Documents\Visual Studio 2015\Projects\EmuRm\MusicRecognition.Service\AudioUtilities\AudioStreamDumper\OverlapingAudioStreamCapture.cs:line 122
```
I checked on VLC what type of codec is that:
```
MPEG AAC Audio (mp3a) with SBR extension
```

Any idea what can i do to support this?

**Comment by markheath** [comment]
basically the Windows Media Foundation APIs are trying to interpret the stream under the hood, so I'm not sure what could be done about this unfortunately.

**Comment by Nekromancer** [comment]
That's not helpful. There's possibility that I have to change crucial library just before project demo :-/

**Comment by markheath** [comment]
sorry, but it's all down to what Media Foundation can offer

**Comment by Nekromancer** [comment]
Thanks anyway. You know some alternative library that i can use to listen to streams?

**Comment by markheath** [comment]
probably I'd try to automate VLC. I think it can be embedded as an ActiveX

**Comment by Nekromancer** [comment]
Hmm. I need to listen to stream and save 30 seconds long chunks to file, every 7 seconds (so the chunks are overlapping). VLC could make that possible?

**Comment by markheath** [comment]
sorry, can't help you with that I'm afraid

**Comment by Nekromancer** [comment]
The same stream opened like that:

```
string streamUrl = "http://zet-net-01.cdn.eurozet.pl:8400";

var webRequest = (HttpWebRequest)WebRequest.Create(streamUrl);
HttpWebResponse resp;
try
{
  resp = (HttpWebResponse)webRequest.GetResponse();
}
catch (WebException e)
{
  return;
}
MemoryStream mp3Buffered = new MemoryStream();
using (var responseStream = resp.GetResponseStream())
{
  byte[] buffer = new byte[65536];
  int bytesRead = responseStream.Read(buffer, 0, buffer.Length);
  while (bytesRead > 0 && stopwatch.Elapsed < TimeSpan.FromSeconds(5))
  {
    mp3Buffered.Write(buffer, 0, bytesRead);
    bytesRead = responseStream.Read(buffer, 0, buffer.Length);
  }
}

mp3Buffered.Position = 0;
using (var mp3Stream = new Mp3FileReader(mp3Buffered))
{
  WaveFileWriter.CreateWaveFile("file.wav", mp3Stream);
}
```

With `useUnsafeHeaderParsing` set to true is working fine. Is it possible to bypass this on MediaFoundationReader? And if not - can you point me how to get average bytes per second with this method? (i need this so i can create buffer for exactly last 30 seconds of music)

**Comment by Nekromancer** [comment]
As far as i can tell - MediaFoundationReader can't handle streams that returns `ICY 200 OK` instead of standard `HTTP 200 OK`

**Comment by Nekromancer** [comment]
Actually, this is a problem on Windows 10. **Windows Server 2008 R2** with installed **Desktop Experience** handles this stream properly
