### ISSUE TITLE
Naudio Gain calculation

### ISSUE THREAD

**Issue by AthiVarathan** [naudio/NAudio#96]
Hi ,

I have using "WaveoutEvent" player in NAUDIO. in that I want all sound play in same frequency. If i have some sound is low  and another is too high. Very urgent requirement So Please help me to do this? Is it possible to calc Gain automatically ?

Thank You.

**Comment by markheath** [comment]
what you would need is an AGC or Compressor algorithm. NAudio doesn't include one out of the box, but you can find open source compressors that you can port to C#.
