### ISSUE TITLE
Does this Library provide spacial audio rendering (i.e. for games)?

### ISSUE THREAD

**Issue by tilkinsc** [naudio/NAudio#965]
The README didn't specify, wiki didn't, and couldn't find an issue here on it.

**Comment by markheath** [comment]
afraid not, haven't had any experience working with spatial audio

**Comment by tilkinsc** [comment]
Gotcha. Since 10 days ago I've been implementing SoLoud and dreading it. Audio libraries aren't up to pace with what I would expect. Currently struggling with writing a function that determines the logarithmic distance a sound is at gain = 0 (20db or less). Proprietary audio libraries have that certain exclusivity which makes free software puke.
