### ISSUE TITLE
Typo in Source Code Prevents Successfully Compiling

### ISSUE THREAD

**Issue by TekuConcept** [naudio/NAudio#97]
`NAudio/MidiFileConverter/MidiConverter.cs`
MidiConverter.cs -> IsEndTrack(...)

`return meta?.MetaEventType == MetaEventType.EndTrack;` should be
`return meta.MetaEventType == MetaEventType.EndTrack;`

**Comment by markheath** [comment]
this is C# 6. You need Visual Studio 2015 or newer to compile it

**Comment by TekuConcept** [comment]
Interesting!

So it does compile without the change as suggested in VS2015.
It also compiles successfully with the change in VS2013.

Might I ask what exactly that operation does or what the benefit of using it is?

**Comment by tzachshabtay** [comment]
It's called the null conditional operator, a simpler way to check for nulls on some scenarios: https://msdn.microsoft.com/en-us/library/dn986595.aspx

**Comment by TekuConcept** [comment]
Thank you @tzachshabtay! That is a curious feature indeed.
